### ISSUE TITLE
[Feature] Add revision mechanism for Application

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1018]
**Is your feature request related to a problem? Please describe.**

`Application CRD` is a mutable object that represents an app, when users try upgrade their app, they change the `Application Object`, the missing part is the revision which record the snapshot of every change.

Without a revision, we can hardly do rolling update.

**Describe the solution you'd like**

In our architecture, the ApplicationConfiguration(AppConfig) Object behind the Application Object can be an immutable object which record the revision. In other word, Application controller can generate AppConfig with a version as suffix.

For our cue template, we should record the revision information in the `context`, then the user can choose how to name their underlying workload.

The workflow could like below:

1. user create an application object
  ```
  application(myapp) with component(myweb) -> appConfig(myapp-v1, myweb-v1)
                                           -> template(context.appName=myapp, context.name=myweb context.revision=v1)
  ```

2. user change some fields of the application object
  ```
  application(myapp) with component(myweb) -> appConfig(myapp-v2, myweb-v2)
                                         -> template(context.appName=myapp, context.name=myweb context.revision=v2)
  ```

3. By default, if we don't name the underlying workload, the workload created by appconfig will have the same name with appconfig.component , which means the underlying workload will have a revision as name. In our example, it will be `myweb-v2`.

4. The user can specify name in CUE template so it can also be a fixed workload name. For example, below is a workload that will generate a fixed name with a concat of AppName and the componentName. The interesting part is the workload can mark a label to record the revision for more convenience.

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: example
spec:
  definitionRef:
    name: deployments.apps
  template: |
    output: {
    	apiVersion: "apps/v1"
    	kind:       "Deployment"
    	metadata: name: context.appName+context.name
    	spec: {
    		selector: matchLabels: {
    			"app.oam.dev/component": context.name
    			"app": context.name+"-"+context.revision
    		}
    
    		template: {
    			metadata: labels: {
    				"app.oam.dev/component": context.name
    				"app": context.name+"-"+context.revision
    			}
    
    			spec: {
    				containers: [{
    					name:  context.name
    					image: parameter.image
    			}
    		}
    	}
    }
    
    parameter: {
    	image: string
    }
```

5. This mechanism also works with trait.

related https://github.com/oam-dev/kubevela/issues/922

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanzhang-oss** [comment]
Good start, I have a few questions

1. There is a "name" in the component in the application. How does that work with the name in the workloadDefinition?
2. Does this mechanism also work with trait?  There is also a "name" field in the traits part of a "component" in an application. How does that work?

**Comment by wonderflow** [comment]
> Good start, I have a few questions
> 
> 1. There is a "name" in the component in the application. How does that work with the name in the workloadDefinition?
> 2. Does this mechanism also work with trait?  There is also a "name" field in the traits part of a "component" in an application. How does that work?

For 1, let's assume:

- the name in the component in the application is `myweb`
- the name of application is `myapp`
- the revision is `v1`
 
then in the context, it will be:

* context.name = myweb
* context.appName = myapp
* context.revision = v1

context is component oreinted.

For 2, yes, this also works for trait. The `name` field in the traits part of a "component"  is the type of the trait.

**Comment by ryanzhang-oss** [comment]
> 1. user change some fields of the application object

reconcile logic can not detect this type of changes for two reasons
1. it is level triggered instead of edge triggered
2. the definition can change behind the back of the application CR.

**Comment by ryanzhang-oss** [comment]
Also, the current implementation uses comp.name as the generated component name and the component name in the AC. This needs to change

**Comment by ryanzhang-oss** [comment]
https://github.com/oam-dev/kubevela/issues/1074

**Comment by ryanzhang-oss** [comment]
#1166
