### ISSUE TITLE
[Feature] Missing parts in catalog design

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1019]
We have a neat catalog design in https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md (https://github.com/oam-dev/kubevela/pull/881) and the experimental implementation is on going.

At the meantime, there are several issues not covered yet in the existing doc per discussed with @hongchaodeng , specifically:

1. How to install the system modules on target cluster? (ideally by CLM?)
2. How handle system modules conflicts in target cluster?
3. How to handle the template modules in `Definition` objects? (critical issue)

Will use this thread to track these following issues.

**Comment by resouer** [comment]
4. How to set values for the system modules? An example is:
   ```
   system-modules
   └── add-ons
       ├── grafana
       │   ├── Chart.yaml
       │   └── values.yaml
       └── prometheus-operator
           ├── Chart.yaml
           └── values.yaml
   ```

**Comment by resouer** [comment]
5. What happens if the platform team make change to system modules in catalog? How vela control plane sync the change to target clusters? Should we enable GitOps?

**Comment by barnettZQG** [comment]
1.2 provides addon management capabilities to solve this issue.  https://github.com/oam-dev/catalog
