### ISSUE TITLE
vela cap install error message is wrong

### ISSUE THREAD

**Issue by WangYikewyk** [oam-dev/kubevela#1028]
When use “cap install” install an capability that doesn't exist , the error message is wrong

![image](https://user-images.githubusercontent.com/77846369/107118548-aa958c80-68bc-11eb-9b80-b63bac20a299.png)

**Comment by wonderflow** [comment]
Yes, the command was changed and we forgot to fix this line https://github.com/oam-dev/kubevela/blob/master/pkg/serverlib/capability.go#L194

**Comment by wangkai1994** [comment]
/assign
i can try to fix it while familiaring with vela
