### ISSUE TITLE
 "vela traits" will make  installed traits become “uninstalled”

### ISSUE THREAD

**Issue by WangYikewyk** [oam-dev/kubevela#1029]
I‘m not sure whether this is a bug.  After run "vela traits" my  installed capabilities become “uninstalled”
vela version:0.3.2
kubernetes cluster version:1.19.1
![image](https://user-images.githubusercontent.com/77846369/107119506-fea36f80-68c2-11eb-8c5e-d4bc860ed720.png)
It's seem to be "vela traits" refresh local trait info, and make source info lost.
Before:
![image](https://user-images.githubusercontent.com/77846369/107119592-aae55600-68c3-11eb-929b-b3cc2904c34d.png)
After:
![image](https://user-images.githubusercontent.com/77846369/107119639-e6802000-68c3-11eb-9cb1-9fdb288d453a.png)

**Comment by wonderflow** [comment]
Yes, I think it's a bug that we didn't record the reource in the definition Object in the K8s cluster, so when `vela traits` synced from cluster, it will update local capability which will cover the local config and the `source` field missed.

Maybe a quick fix is to record the source info into the extension field of definition and sync into K8s cluster.

**Comment by WangYikewyk** [comment]
Noted. By doing this could solve this problem indeed. But I found that the cap center is a local concept,It's means that every member's repo name maybe different. I thought it's not  perfect idea to  syncing the source info into workload/trait definition CR.

**Comment by WangYikewyk** [comment]
I will fix this bug by adding source field in trait definition CR.Maybe in the future can we design something like "cap center CRD" to solve this problem? : )

**Comment by wonderflow** [comment]
@WangYikewyk Yes, my suggestion is a quick fix, not long term, and it just use the extension field.
