### ISSUE TITLE
[Dashboard]update kubevela logo

### ISSUE THREAD

**Issue by sunny0826** [oam-dev/kubevela#1043]
Upload `logo.svg` to OSS and update the [`dashboard/config/defaultSettings.ts`](https://github.com/oam-dev/kubevela/blob/da523678977f630465b16d502231cf092345aee8/dashboard/config/defaultSettings.ts#L18) file

**Comment by zzxwill** [comment]
We have logos image here https://github.com/oam-dev/kubevela/tree/master/docs/resources. Let's try to store the logo in somewhere under dashboard.

![image](https://user-images.githubusercontent.com/2805315/108328350-75b3fe80-7207-11eb-894a-bb7a7d4ef1eb.png)
