### ISSUE TITLE
Replace Vela up in the github CI

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/kubevela#1059]
**Describe the bug**

`vela up` is being deprecated but we are still using it to setup e2e test in CI.

**To Reproduce**

**Expected behavior**
Use `helm install` instead as recommended in our documents.  

**Additional context**
Currently, the e2e/setup test suite is empty and we somehow relies on it in the e2e test setup to make sure the setup is correct.  We need to add some setup tests.

**Comment by zzxwill** [comment]
@ryanzhang-oss Ryan, do you mean replacing `vela install`?

**Comment by wonderflow** [comment]
> @ryanzhang-oss Ryan, do you mean replacing `vela install`?

This will be fixed in #1005

**Comment by kushthedude** [comment]
hi @ryanzhang-oss , is this issue still valid?
