### ISSUE TITLE
[Feature] Evaluate renaming WorkloadDefinition to ComponentDefinition

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1061]
**Is your feature request related to a problem? Please describe.**

This was brought up by Oracle folks that `WorkloadDefinition` is not accurate to describe what it is doing, we actually agree  and also had similar discussion internally before (sorry, naming is so hard).

Since KubeVela is heading to 1.0, it worth to discuss and evaluate if we want to rename existing `WorkloadDefinition` to `ComponentDefinition` (or sth else which can reflect its purpose of registering components by component providers).

**Describe the solution you'd like**

If we decide to do this, `WorkloadDefinition` of OAM spec v0.2.1 will still be there for backward compatibility.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
From my view, I will vote for `WorkloadDefinition`, because `Component` can be a concept contain both workload and traits.

**Comment by wonderflow** [comment]
https://github.com/oam-dev/kubevela/issues/976#issuecomment-781794802

**Comment by wonderflow** [comment]
align with https://github.com/oam-dev/spec/issues/443
