### ISSUE TITLE
vela traits --sync does not sync traitdefinitions from the cluster to .vela locally

### ISSUE THREAD

**Issue by stigtermichiel** [oam-dev/kubevela#1063]
**Describe the bug**

`vela traits --sync` does not sync traitdefinitions from the cluster to .vela locally.

**Expected behavior**
Traits that are defined in the targeted cluster should be synced to the .vela/capabilities/traits folder. This does not happen.

**Cluster information**
Describe your kubernetes cluster information.
- Kubernetes Version 1.19.7-GKE.800

**Comment by stigtermichiel** [comment]
Ah we've found that we needed to do `-r` to force a sync. What is the `-s` useful for?

**Comment by wonderflow** [comment]
Yes, it seems it's a bug and the `--sync` was not needed.

**Comment by just-do1** [comment]
By reading the source code, I found the following logical 

```go
// NewTraitsCommand creates `traits` command
func NewTraitsCommand(c types.Args, ioStreams cmdutil.IOStreams) *cobra.Command {
	var workloadName string
	var syncCluster, enforceRefresh bool
	...
		RunE: func(cmd *cobra.Command, args []string) error {
			if syncCluster {
				if err := RefreshDefinitions(ctx, c, ioStreams, true, enforceRefresh); err != nil {
					return err
				}
			}
	...
	}

	cmd.SetOut(ioStreams.Out)
	cmd.Flags().StringVar(&workloadName, "apply-to", "", "Workload name")
	cmd.Flags().BoolVarP(&syncCluster, "sync", "s", true, "Synchronize capabilities from cluster into local")
	cmd.Flags().BoolVarP(&enforceRefresh, "", "r", false, "Enforce refresh from cluster even if cache is not expired")
	return cmd
}
```

![vela traits --sync](https://user-images.githubusercontent.com/20176249/108468712-1e269900-72c2-11eb-8a08-d212e3d770cf.png)

`--sync` means whether the traits information will be synchronized ； `refreshInterval = 5 * time.Minute`

`-r`  represents forced synchronization and does not need to wait for the synchronization cycle to arrive

If `--sync` is false, the information is never synchronized.

**Comment by just-do1** [comment]
> Yes, it seems it's a bug and the `--sync` was not needed.

Do you mean to remove the logic of `--sync` and sync directly from the cluster each time with parameter `-r`?

**Comment by wonderflow** [comment]
@just-do1  Hi, may I assign this issue to you?

> Do you mean to remove the logic of --sync and sync directly from the cluster each time with parameter -r?

Yes, by default the `--sync` is true, we can just remove this parameter and leave it as the default behavior

**Comment by just-do1** [comment]
Ok, I'll finish it as soon as possible

**Comment by stigtermichiel** [comment]
This is the same for `vela workloads` by the way.

**Comment by wonderflow** [comment]
> This is the same for `vela workloads` by the way.

yes, ping @just-do1  please fix together，thanks

**Comment by just-do1** [comment]
ok
