### ISSUE TITLE
Forbid names in the template/CR when use applications to render resources

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/kubevela#1074]
Currently, there are many places that a user can insert the resource names. For example, they can fill in the `metadata.name` in the cue template. They can also put the name in any embedded CR in the component or trait. This is not very desirable, especially in the rollout case since we need to locate the workload from outside of the applicationConfiguration controller which is the only place that the final workload name is determined. 

Here is the proposal

- We will add a special annotation on all the applicationConfigurations generated by the application controller. This allows us to put in the new naming convention only on those application generated appConfig.
- applicationConfiguration controller will ignore any name fields in the embedded CR when it knows the appConfig is generated by an application.
- the exact workload name depends on the workload itself. 
     - we will use the component name in the application (not the component type name) as the name of the workload that has in place upgrade ability (i.e. cloneset)
     -  we will use the component name plus the revision as the name of the workload that does not have in place upgrade ability (i.e. deployment)
- the trait name in the application plus the revision as the name of most of the traits if the trait doesn't need to stay the same between different applicationConfiguration. The exact list of such traits is TBD.

In this way, it will be pretty straightforward to get the real k8s resources given an application definition.

**Comment by wonderflow** [comment]
We should also support user specified revision name , for example:

```
kind: Application
metadata:
  annotations:
     revision-name:"myapp-v0001"
```

**Comment by ryanzhang-oss** [comment]
what does the "revision-name" field mean?
