### ISSUE TITLE
check outputs:resource should be unique in application webhook

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1093]
The trait can use `context.outputs.<xx>`  to do simple data passing.

This rely on the trait resource name is unique, or the former outputs resource data will be covered by the latter one.

We should add [a webhook validate rule](https://github.com/oam-dev/kubevela/tree/master/pkg/webhook/core.oam.dev/v1alpha2/application) to check for it.

https://github.com/oam-dev/kubevela/pull/1087/files#diff-05b89d808deaa1f5a7e06ea0b6de559283ab1e2ea28e006299af38a200fa9bcaR354

_Originally posted by @zzxwill in https://github.com/oam-dev/kubevela/pull/1092#r580846972_

**Comment by captainroy-hy** [comment]
May I help with this issue? If @Cweiping is busy with other tasks.

**Comment by wonderflow** [comment]
Sure, please carry on @captainroy-hy Thanks!
