### ISSUE TITLE
[Feature] TraitDefinition should tell if it will restart the workload pod

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1123]
**Is your feature request related to a problem? Please describe.**

Now when we deploy/upgrade an Application, only change some fields of trait , we don't know whether the underlying pod will restart or not, we should let the TraitDefinition tell.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hongchaodeng** [comment]
I think this is more like a description field at the beginning. So we probably could add a field like this:

```yaml
TraitDefinition:
  spec:
    podDisruptive: false | true
```

In the future, we can have more complex policy to indicate whether we allow such traits to apply during production runtime.

**Comment by wonderflow** [comment]
Yes, I think a flag is enough, for extensibility, what about a string type for this flag?

```
TraitDefinition:
  spec:
    podDisruptive: yes | no | unknown
```

By default, it's unknown.

**Comment by wonderflow** [comment]
1. add field into traitdefinition
2. display in cli
3. add docs

\cc @yangsoon
