### ISSUE TITLE
[Dashboard] Application can't be deleted

### ISSUE THREAD

**Issue by kinsolee** [oam-dev/kubevela#1129]
**Describe the bug**
Cannot delete the application listed on the page. Seems like there is a bug in api-server, mismatching the `app name` and `app with version name`

**To Reproduce**
![image](https://user-images.githubusercontent.com/5144108/109796219-d6edc000-7c52-11eb-98b3-58ba5113cfd4.png)

**Expected behavior**
Delete the application correctly.

**Comment by hongchaodeng** [comment]
We are rewriting the dashboard and all control plane stuff in [velacp](https://github.com/oam-dev/velacp) project.
That has supported deletion of applications as well.
We are still in the middle of migrating stuff in between. Would let you know once it is done

**Comment by kinsolee** [comment]
Nice to hear that, I will keep looking at the latest features. Will velacp be a temporary project mainly targeting at migrating, or a long-going project paralleled with kubevela?
