### ISSUE TITLE
Get rid of the integration test dir

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/kubevela#1147]
**Describe the bug**
We currently maintain two types of e2e tests and the test/integration directory contains only one test that relies on some obsolete/proprietary test framework. 

We actually put in a CI hack so that the integration test can run. We need to migrate the integration test to test/e2e-test dir and suite.

The extra one-test-only coverage absolutely doesn't worth the maintenance effort for a different style and the CI hack.

**To Reproduce**
See the code in test/integration

**Expected behavior**
All e2e tests are organized cleanly under the test/e2e-test dir with before and after suite logics that are self-contained.

**Comment by captainroy-hy** [comment]
I would like to help with this issue.
