### ISSUE TITLE
[Feature] revision for doc site

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1155]
**Is your feature request related to a problem? Please describe.**

Now when a PR was merged, the doc site(kubevela.io) was updated, that was hard for maintian. We need to keep a revision for our doc site until next release.

**Describe the solution you'd like**

Just like crossplane does:

The URL shows which revision the doc site points to: https://crossplane.io/docs/v1.1/

![image](https://user-images.githubusercontent.com/2173670/110305219-789c5500-8037-11eb-9384-65e8e999168f.png)

![image](https://user-images.githubusercontent.com/2173670/110305277-8f42ac00-8037-11eb-8821-7a1dc2d80d22.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
@sunny0826  Cool

**Comment by sunny0826** [comment]
@wonderflow @resouer As of now, the process has been initially tested and the new process is based on the GItHub Action automation setup documentation. Users only need to edit the `.md` and `sidebar.js` files in `/docs` under the [kubevela](https://github.com/oam-dev/kubevela) repo, and the push will trigger GItHub Action to automatically update the website content.

Example Project：https://pod-lens.guoxudong.io
Github Repo: https://github.com/sunny0826/kubectl-pod-lens 
https://github.com/sunny0826/pod-lens.github.io

If this process is OK, I'll start refactoring the kubevela official site.

**Comment by wonderflow** [comment]
Cool, please go ahead!

**Comment by sunny0826** [comment]
preview url: https://kubevela.guoxudong.io
