### ISSUE TITLE
release v0.3.4 doesn't generate darwin package

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1163]
https://github.com/oam-dev/kubevela/releases/tag/v0.3.4

![image](https://user-images.githubusercontent.com/2805315/110448862-8ff14600-80fc-11eb-9a67-8977bfa3931c.png)

**Comment by wonderflow** [comment]
yes,cherry-pick https://github.com/oam-dev/kubevela/pull/1134 into release-0.3 can fix it

related issue: #1125

**Comment by legendtkl** [comment]
Hi, @wonderflow , I would like to take this one, can you assign it to me?

**Comment by wonderflow** [comment]
> Hi, @wonderflow , I would like to take this one, can you assign it to me?

Sure,thanks!

**Comment by wonderflow** [comment]
@legendtkl Hi, are you going to send a PR recently? We're going to release 0.3.5 in two days.

**Comment by legendtkl** [comment]
Hi, @wonderflow , sorry for the late reply.
This is my first PR and I try to fix my local env, it stuck in the step: "staticcheck ./..." when running 'make'.

Anyway, for not blocking the release, I have cherry-pick the commit mentioned in the comments and submit the PR https://github.com/oam-dev/kubevela/pull/1169. 

Thanks.

**Comment by wonderflow** [comment]
@legendtkl Welcome, thanks for your contribution.

**Comment by legendtkl** [comment]
:D
