### ISSUE TITLE
Kubevela client CI/CD integration and distributed developers workflow

### ISSUE THREAD

**Issue by jriguera** [oam-dev/kubevela#1164]
**Describe the bug**

We are a bit confused about what the intended workflow is for developers/applications teams working with Kubevela.

We expect `vela ls` to show all the applications of an environment (kubernetes namespace) that a developer is part of. This way developers can get the same view of their applications and their states.  Currently `vela ls` only shows apps which have been deployed by local user.

**To Reproduce**

1. UserA deploys *app1* with `vela up` at time T1.
2. UserB wants to check the status and logs of the app *app1*, performs `vela ls` and *app1* is not there.
3. UserB pushes  *app1* again and sees `App exists, updating existing deployment...` at  time T2.
4. UserB sees *app1* created at time T1 with `vela ls`
5. UserB  runs `vela status app1` and sees T2 timestamps

**Expected behavior**

According to the previous steps to reproduce the issue, *User B* would see the same timestamps and be able to run actions like `vela logs` or `vela exec` without deploying the app again.

**Additional context**

Pushing apps via an automated CI/CD system, where pipelines run tests on git push/commits, why developers need to push the same app again manually, with the same code and parameters (environment variables and/or secrets) as the CI/CD pipeline in order to be able just to check the status of the app?

Can you point us to a suitable workflow for this scenario?

**Comment by Cweiping** [comment]
When v1.0.0 is released, your problems will be solved. use `Application` and `Environment` CRD  to manage user-defined applications. 
More Details: https://github.com/oam-dev/kubevela/issues/932

**Comment by resouer** [comment]
Though for the CLI part, I believe `$ vela ls --environment` should return all the apps in this environment, regardless of the user who creates it. /cc @wonderflow to confirm, it seems to be a bug.

We are migrating CLI/dashboard/Appfile to work with vela control plane objects so right now CLI issue is not P0 task. But for v1.0.0, I think we should still ensure the essential features are available.

**Comment by wonderflow** [comment]
Currently I have supported `vela ls --namespace=xxx` to list applications from cluster in #1174

**Comment by jriguera** [comment]
Nice!, thank you, but I have a small question, given the environment is already in the context, why do not make it by default?  without the need of `xxxx` in the  `--namespace` flag. I haven't check the code, but we are happy to submit a PR if you want.

**Comment by wonderflow** [comment]
Yes , the default behavior is to read the namespace in local env meta, it's already contained in #1174

**Comment by jriguera** [comment]
Thanks, I am going to compile it and give a try. Thanks again!

**Comment by jriguera** [comment]
I have compiled the PR and it works, but there is still an issue with the commands `vela status`, `vela exec`, `vela logs` ... which they report `Error: application "test-app" not found`. 

Given the fact you are working on the new Vela control Plane, which would define a new API, I am wondering if it makes sense continue fixing the current client. To my understanding, the new velacp would require to rewrite the client, and the rewrite would be simple and easy (almost perform API requests and print the result?). The functionalities regarding CUE templates will be done in velacp, right?

**Comment by wonderflow** [comment]
@jriguera Yes, we will finally using velacp, but currently we may not possible to include velacp in kubevela-v1.0

**Comment by wonderflow** [comment]
> vela status, vela exec, vela logs ... which they report Error: application "test-app" not found.

BTW, I'm still working on that PR, thanks for reporting.

**Comment by jriguera** [comment]
Thank you!

**Comment by wonderflow** [comment]
@jriguera I think this issue has been fixed, please have a  try with the master branch. Thanks!

**Comment by wonderflow** [comment]
@jriguera  I think this issue was fixed, please have a try with the master branch, thanks!

**Comment by jriguera** [comment]
It works! Thank you!
