### ISSUE TITLE
[Feature] request to change base image of  vela-core for debug convenience

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1177]
**Is your feature request related to a problem? Please describe.**

The vela-core images to use `ENTRYPOINT `, we can not access to the container. When the vela-core have some problem, I cannot troubleshoot problems quickly.

For exmaple, when I install kubevela and meet the problem and I cannot not find problem easy:
```bash
$ kubectl --namespace vela-system port-forward $POD_NAME 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
Handling connection for 8080
E0311 18:08:22.897968   20928 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod d07025c7648f5e2b6ece1fe8f3caf1210b462ce5b4df19826b0253a1176dfa89, uid : exit status 1: 2021/03/11 18:08:24 socat[31899] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
E0311 18:08:22.898883   20928 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod d07025c7648f5e2b6ece1fe8f3caf1210b462ce5b4df19826b0253a1176dfa89, uid : exit status 1: 2021/03/11 18:08:24 socat[31900] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused
```

**Describe the solution you'd like**

Change  `CMD` of Dockerfile instead of `ENTRYPOINT`. And the yaml file of vela-core deployment use `command` instead of `args`.

**Comment by shikanon** [comment]
@wonderflow can we provide other base images like alpine instead of "Distroless". when occur problem we cannot entry the container to network and service.

**Comment by wonderflow** [comment]
I think this need to be discussed. WDYT?  ping @hongchaodeng @ryanzhang-oss

**Comment by wonderflow** [comment]
It seems we can use `ubuntu:latest` as our base image, its size is very small now. 

https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated

**Comment by shikanon** [comment]
> It seems we can use `ubuntu:latest` as our base image, its size is very small now.
> 
> https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated

yes, the command of ubuntu is more popular than alpine which is only 2MB. But if consider the balance of  image size and propularity, is alpine better choice?

vela-core image build size is ~25MB
ubuntu image size is ~25MB
alpine image size is ~2.5MB

vela-core image:
https://hub.docker.com/r/oamdev/vela-core/tags?page=1&ordering=last_updated
ubuntu image:
https://hub.docker.com/_/ubuntu?tab=tags&page=1&ordering=last_updated
alpine image:
https://hub.docker.com/_/alpine?tab=tags&page=1&ordering=last_updated
