### ISSUE TITLE
[Feature] workloadDefinition Health check supports external CRD processing status results

### ISSUE THREAD

**Issue by xiqiu618** [oam-dev/kubevela#1178]
**Is your feature request related to a problem? Please describe.**
Health check supports the implementation of obtaining fields from the fields in output for verification. However, complex logic judgment is often not only performed in one CRD, but also can be implemented by multiple operators. Therefore, we hope to expand this capability

**Describe the solution you'd like**
Take an example of a helm to illustrate. We use the helm operator to implement the deployment of a helm Charts is defined as a kind of workload definition, and the scheme adopted is the helm operator of flux. Through experiments, it is found that the status check of components is relatively rough, and we can only rely on release to trigger deployment operation to judge whether it is successful or not. We can't subdivide the resources generated by release, which can't meet our expectations
![image](https://user-images.githubusercontent.com/73998049/110787333-2b72ea00-82a8-11eb-9899-eb62a2e247df.png)
![image](https://user-images.githubusercontent.com/73998049/110787370-3463bb80-82a8-11eb-99d1-850e8506f84d.png)

We have developed a component (helmRelease status operator) to make up for this function. The name of CRD is helmRelease status, which refs to helmRelease resources. HelmRelease status is not defined in workload definition. We hope that health check can combine helmRelease status with helmRelease logic to make unified judgment and ensure service availability

![image](https://user-images.githubusercontent.com/73998049/110786754-793b2280-82a7-11eb-977e-c8de63203a0d.png)
```
deployPhase: Succeeded
  releaseName: chart-system-redis
  resources:
  - GroupVersionKind:
      Group: ""
      Kind: Secret
      Version: v1
    Message: ""
    Name: chart-system-redis
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: ""
      Kind: ConfigMap
      Version: v1
    Message: ""
    Name: chart-system-redis-scripts
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: ""
      Kind: ConfigMap
      Version: v1
    Message: ""
    Name: chart-system-redis
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: ""
      Kind: ConfigMap
      Version: v1
    Message: ""
    Name: chart-system-redis-health
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: ""
      Kind: Service
      Version: v1
    Message: ""
    Name: chart-system-redis-headless
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: ""
      Kind: Service
      Version: v1
    Message: ""
    Name: chart-system-redis-master
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: ""
      Kind: Service
      Version: v1
    Message: ""
    Name: chart-system-redis-slave
    Namespace: chart-system
    Ready: true
  - GroupVersionKind:
      Group: apps
      Kind: StatefulSet
      Version: v1
    Message: |
      ready replicas 0 < total replicas 1
    Name: chart-system-redis-master
    Namespace: chart-system
    Ready: false
  - GroupVersionKind:
      Group: apps
      Kind: StatefulSet
      Version: v1
    Message: |
      ready replicas 0 < total replicas 1
    Name: chart-system-redis-slave
    Namespace: chart-system
    Ready: false
```
**Describe alternatives you've considered**
As an alternative, helm release status is also declared as a workload definition. The mapping logic of helmrelease status and helmrelease is integrated into helmrelease status operator logic

**Additional context**

**Comment by wonderflow** [comment]
@xiqiu618 Hi, does this issue resolved?
