### ISSUE TITLE
master: Failed to upgrade using helm

### ISSUE THREAD

**Issue by S-mango** [oam-dev/kubevela#1184]
ErrorInfo: UPGRADE FAILED: failed to create resource: TraitDefinition.core.oam.dev "ingress" is invalid: spec.definitionRef: Required value

**Modification method**: 
Need to add this “spec.definitionRef” in the file 
(oam-dev/kubevela/charts/vela-core/templates/defwithtemplate/ingress.yaml)

**Comment by wonderflow** [comment]
Yes, the CRD has been updated, the `spec.definitionRef` was not required in the new version

**Comment by wonderflow** [comment]
@S-mango Hi, you can delete the TraitDefinition CRD and re-install helm chart. Closing, feel free to re-open it if there's still any question on it.
