### ISSUE TITLE
requeue mechanism when error occurs in reconciliation

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1188]
AppConfig controller uses its own mechanism to re-queue obj during reconciliation. Once an error occurs, an error condition will be added into `appconfig.status`. And status changing will trigger requeue then reconcile again.
But in the situation where reconcile proceed very fast, the same error occurs, and the new error condition is created.
Since the duration time is very small, the timestamp(lastTransactionTime) in the error condition is the same as last time. That means, no change happens to the appconfig status, so it will not trigger requeue.
![image](https://user-images.githubusercontent.com/5107364/111017492-4c962080-83f7-11eb-989f-5974d0d21c4a.png)

Then the appconfig controller has to wait a bit long time until an informer re-sync happens. Currently, the default informer resync interval is 5min. 
`	flag.DurationVar(&syncPeriod, "informer-re-sync-interval", 5*time.Minute,
		"controller shared informer lister full re-sync period")
`

#### solution
If error occurs, track it into resource's status (condition) to trigger requeue.
To avoid the issue aforementioned, check the previous error msg before setting status.

**Comment by wonderflow** [comment]
We should remove the lastTransitionTime in status, and let the error return
