### ISSUE TITLE
Application Revision path: Create new component name similar to what happens to AppConfig

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1200]
Currently, if `app.oam.dev/rollout-template` is set, it will create new AppConfig and bump the revision in name. But the component name isn't updated and uses componentRevisionName instead.

This is very inconvenient for AppDeployment to clone components to other clusters. We should change it to create new component similar to what happens to AppConfig.

**Comment by hongchaodeng** [comment]
Note:

just need to change revisionName here to componentName:

```go
// GenerateAppFile converts an application to an Appfile
func (p *Parser) GenerateAppFile(ctx context.Context, name string, app *v1alpha2.Application) (*Appfile, error) {
	appfile := new(Appfile)
	appfile.Name = name
	var wds []*Workload
	for _, comp := range app.Spec.Components {
		wd, err := p.parseWorkload(ctx, comp)
		if err != nil {
			return nil, err
		}
		wds = append(wds, wd)
	}
	appfile.Workloads = wds
	appfile.RevisionName, _ = utils.GetAppNextRevision(app)
	return appfile, nil
}
```

**Comment by ryanzhang-oss** [comment]
This is because we have a component revision mechanism.  I am not sure if we need to replace that logic in the application controller.

**Comment by wonderflow** [comment]
I suggest we use revisionName to prevent unexpected change on component.

**Comment by hongchaodeng** [comment]
After syncing with @wonderflow , here's our discussion:

- The reason why revision name is not working anymore is because when cloning to other clusters, we need to wait the components to apply first and get the revisions to fill the AC again. This would make the revisionName varying in each clusters. Moreover, the AppDeployment controller will also change the replicas of the Workload, and incrementing the revision.
- The problem of above scenarios will not only make the logic very complex and error prone, but also make the revisionName inconsistent across ACs.
- We have decided to to use ComponentName instead when cloning Components across clusters.
- We would add add a similar revision annotation to Component to prevent Component handler from creating revisions.

**Comment by hongchaodeng** [comment]
Closing this in favor to #1210
