### ISSUE TITLE
[Feature]`vela` command provide debug tools which render from Application to Application Configuration

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1207]
**Is your feature request related to a problem? Please describe.**

Application is render from app file. But the `applicationconfigurations` and `components`  which render from `Application` is inconvenient to debug.
For example, when I define a workload and trait, and I apply `application` not working, I cannot get information when I lost the trait. I also think What happen? I can't know anything unless I check the pod of vela-core log.

**Describe the solution you'd like**

can use `vela` to render the application to the application configuration and components, and also can use it to render to the finish object like this:

To render the application:
```bash
vela template appfile --dry-run <appfile.yaml> -o <output-type>
``` 

To render the applicationconfigurations and components:
```bash
vela template appconfig --dry-run <application.yaml> -o <output-type>
``` 

To render the finish CRD object:
```bash
vela template oam --dry-run <oam runtime directory> -o <output-type>
``` 

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
We already have `vela system dry-drun` do you mean extend it?

**Comment by shikanon** [comment]
> We already have `vela system dry-drun` do you mean extend it?

Yes, It is useful to me. But I not see it in the document, I think it can be added.

**Comment by wonderflow** [comment]
@shikanon  Yes ， we're planning to add it in #1191 I think we could discuss more about it in this issue, currently it's really not easy to write a CUE template.

**Comment by wonderflow** [comment]
New docs were added,please read and have a try, thanks. https://kubevela.io/#/en/cue/component?id=a-full-workflow-of-how-to-debug-and-test-cue-definitions
