### ISSUE TITLE
The link in the blog Readme is 404

### ISSUE THREAD

**Issue by shikanon** [oam-dev/kubevela#1221]
**Describe the bug**

The readme in the link is invalid. this two link:
![image](https://user-images.githubusercontent.com/7250620/111579797-9ca72580-87f1-11eb-913e-41af84b44e40.png)

**To Reproduce**

1. open link https://github.com/oam-dev/kubevela/tree/master/docs/blog/zh
2. click link under the paper
3. see 404 error

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

**Comment by sunny0826** [comment]
This directory holds the official blog module source files, read them at https://kubevela.io/#/blog/zh/, this is not a bug.
