### ISSUE TITLE
Application Controller should not "Update" an AppRevision

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1254]
Currently the app controller could **UPDATE** an AppRevision: https://github.com/oam-dev/kubevela/blob/379e1432221b00baa433ddf595cdcbc369f1d393/pkg/controller/core.oam.dev/v1alpha2/application/apply.go#L110-L118

This doesn't make any sense. An AppRevision is an immutable thing. It should not be updated. A potential problem with this code is that in second time reconcile some of the labels could be changed. Then it will update them. This might violates immutability.

A problem it might cause is that the GenerateAppfile() function will render context.AppRevision which could be v2 while the app revision is currently v1. Even though the App spec is not changed, the workload's labels are changed.

**Comment by ryanzhang-oss** [comment]
it is to update the label/annotation. Yes, the labels/annotation can change within a revision. The rationale behind it is that we won't have two revisions that only differ in labels/annotation so they are meaningfully different. 
I am guessing that you want to create one revision for each cluster (with just label difference)? I am not sure if that's what revision is for.

**Comment by hongchaodeng** [comment]
> I am guessing that you want to create one revision for each cluster (with just label difference)? I am not sure if that's what revision is for.

I'm not sure what you mean here. That's not what the problem I'm describing above.

The problem is that in second time the context.AppRevision (e.g. v2) will be bumped up while the actual AppRevision name is still the old one (e.g. v1)

**Comment by hongchaodeng** [comment]
Discussed with @ryanzhang-oss offline. We will not rely on context.AppRevision.
Instead, AppDeploy controller will pass in revision label to AC to wrap labels around pods.
