### ISSUE TITLE
WARN: handle workload template `containerizedworkloads.core.oam.dev` failed: template not exist in definition, you will unable to use this workload capability

### ISSUE THREAD

**Issue by rapkey** [oam-dev/kubevela#1262]
Always show the following msg while run `vela workloads`.
`WARN: handle workload template `containerizedworkloads.core.oam.dev` failed: template not exist in definition, you will unable to use this workload capability`

How can I konw which workload cause this warning?

**Comment by wonderflow** [comment]
It's because this workload `containerizedworkloads.core.oam.dev` doesn't contain a `schematic` template, others will work normally. You can delete it if youre not using it.

```
kubectl delete workloaddefinition containerizedworkloads.core.oam.dev
```

**Comment by rapkey** [comment]
@wonderflow But I never create this workload. Where it from?

**Comment by wonderflow** [comment]
It's a default workload installed by the Vela chart.

**Comment by resouer** [comment]
@wonderflow with v0.3.0 spec (kubevela v1.0), we need to decouple component and workload types, `vela workloads` should not complain. It seems we need a `vela components` command.

**Comment by wonderflow** [comment]
@resouer  Yes, agree, it's in my plan, will finish it in these two days.

**Comment by rapkey** [comment]
> It's a default workload installed by the Vela chart.
The default workload raise warning？

**Comment by rapkey** [comment]
@wonderflow 
Thanks for your help.But why the default workload raise warning？

**Comment by resouer** [comment]
@rapkey Please check this comment: https://github.com/oam-dev/kubevela/issues/1262#issuecomment-805515069, this is a bug in vela cli.

**Comment by rapkey** [comment]
@resouer Get. Thanks a lot.

**Comment by wonderflow** [comment]
Closing as it should be fixed in the master branch.
