### ISSUE TITLE
[Feature] Provide a way to disable revisioning for a component

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1266]
**Is your feature request related to a problem? Please describe.**

If a component is a Crossplane managed resource, creating a new revision might not work as it might fail when the Observe reconciling find a managed resource is already there and not controlled by the current controller.

For example, more than one Crossplane RDSInstance revision will be created and the newer one will fail.

```
✗ k get component
NAME             WORKLOAD-KIND   AGE
sample-db        RDSInstance     13h

✗ k get rdsinstance
NAME           READY   SYNCED   STATE     ENGINE   VERSION   AGE
sample-db-v1   True    True     Running   mysql    8.0       13h
sample-db-v2           False              mysql    8.0       12h
```

**Describe the solution you'd like**

- Disable RevisionEnabled mechanism for specified component

**Describe alternatives you've considered**

- Or maybe we can deleting the old revision and recreate a new revision.

**Additional context**

**Comment by wonderflow** [comment]
This is fixed by #1315
