### ISSUE TITLE
traitDefinition controller can't generate the schema

### ISSUE THREAD

**Issue by ryanzhang-oss** [oam-dev/kubevela#1288]
**Describe the bug**
"E0325 00:28:45.137211       1 traitdefinition_controller.go:76] "cannot store capability in ConfigMap" err="cannot generate OpenAPI v3 JSON schema for capability manualscalertraits-extended.core.oam.dev: capability manualscalertraits-extended.core.oam.dev doesn't contain section `parmeter`"

**To Reproduce**
Helm install vela

**Comment by yangsoon** [comment]
sorry, this PR was fixed in https://github.com/oam-dev/kubevela/pull/1689
