### ISSUE TITLE
Why application CRD description field have line break when it's too long

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela#1311]
As title said,  but other CRDs don't. This broke my CI pipeline

https://github.com/oam-dev/kubevela/blob/20a31d4554466206fe939dae141eee379fe45a7f/charts/vela-core/crds/core.oam.dev_applications.yaml#L60

**Comment by captainroy-hy** [comment]
Maybe you can try upgrading your kustomize bin to v3.8.2. Legacy version kustomize has the problem you said.
