### ISSUE TITLE
Can't create deployment in Kind-cluster(k8s-version:1.20.2)

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#1314]
**Describe the bug**

kubevela(1.0.0) in Kind-cluster(k8s v1.20) can't create deployments.

**To Reproduce**
env:
1. MacOs: version: 10.15.5 (19F101)
2. Kind: version: v0.10.0 go1.15.7 darwin/amd64
3. k8s: version: v1.20.2

When run demo in [https://kubevela.io/#/en/quick-start-appfile](https://kubevela.io/#/en/quick-start-appfile),the log did not print any errors.  Corresponding resources Application, ApplicationContext, ApplicationRevision, Component are also created, but execute `kubectl get deployments`, shows `No resources found`.

While In Kind-cluster(k8s-version:1.18.15)，everything normal, k8s  can create deployment.

**Comment by wonderflow** [comment]
https://github.com/kubernetes/kubernetes/pull/92743
