### ISSUE TITLE
Add AppDeployment/AppRollout doc to the website

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#1337]
The docs are here:

AppDeploy: https://github.com/oam-dev/kubevela/blob/master/docs/examples/appdeployment/README.md
AppRollout: https://github.com/oam-dev/kubevela/blob/master/docs/en/rollout/rollout.md

Need to refine it based on mdx and update the TOC.

**Comment by wonderflow** [comment]
![image](https://user-images.githubusercontent.com/2173670/112779308-02f53900-9079-11eb-8358-43cc642e5b71.png)

I suggest the hierarchy could be like this.

The docs should be in： https://github.com/oam-dev/kubevela/tree/master/docs/en 
The TOC file: https://github.com/oam-dev/kubevela/blob/master/docs/sidebars.js

**Comment by wonderflow** [comment]
We have copy the tuturial https://kubevela.io/docs/rollout/appdeploy please refine it.

**Comment by hongchaodeng** [comment]
AppDeployment doc PR: https://github.com/oam-dev/kubevela/pull/1355
