### ISSUE TITLE
Support traffic management in Application rollout with workflow

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1357]
We should have Traffic Management feature for [app rollout](https://kubevela.io/docs/rollout/rollout) like flagger. #299

**Comment by charles-woshicai** [comment]
What does traffic management means?

**Comment by LeoLiuYan** [comment]
@wonderflow 

Does AppRollout still need `Traffic Management`? AppDeployment already has it.

**Comment by wonderflow** [comment]
Specifically, I mean the traffic driven rollout. The current rollout is driven by replica, while we can use HPA and let the traffic percent to  drive the rolling.

**Comment by charles-woshicai** [comment]
/assign

I can have a try.

**Comment by wonderflow** [comment]
@charles-woshicai Hi, are you still working on that?

**Comment by charles-woshicai** [comment]
> @charles-woshicai Hi, are you still working on that?

No, actually I don't start to work for this issue even for I not being assigned.

I will be willing to help after being assigned, recently I am free.

**Comment by wonderflow** [comment]
https://kubevela.io/docs/case-studies/canary-blue-green
