### ISSUE TITLE
[Feature] Use pure github action commans for website sync

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1367]
Currently the docs website automatically sync by a outer action: https://github.com/oam-dev/kubevela/blob/master/.github/workflows/release-docs.yaml#L15

In fact, this job could be done by the script just as the docs check action https://github.com/oam-dev/kubevela/blob/master/.github/workflows/check-docs.yml#L19

**Comment by yangsoon** [comment]
Note, we should also keep some infrequently changed config files like ` index.js`, `docusaurus.config.js` keep in repo kubevela.io. only overwrite frequently changed files.
