### ISSUE TITLE
Code Refactor: remove all the duplicate fields in parser above as template contains now

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1388]
[pkg/appfile/parser.go:L78](https://github.com/oam-dev/kubevela/blob/0629049e1f9fd1529a2e285f569258896296a566/pkg/appfile/parser.go#L78)

**Comment by Ghostbaby** [comment]
@wonderflow pls assign to me

**Comment by wonderflow** [comment]
@Ghostbaby Sure,thanks
