### ISSUE TITLE
write a helm chart test for vela-core chart

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1406]
Now we don't have any test for the installation of the helm chart. https://github.com/oam-dev/kubevela/tree/master/charts/vela-core/templates/tests removed in https://github.com/oam-dev/kubevela/pull/1405

We should follow the docs:  https://helm.sh/docs/topics/chart_tests/

And write a test that include creating an application and get the status to be running.

**Comment by charles-woshicai** [comment]
Please help to review.
