### ISSUE TITLE
[Docker] Docker base image discussion

### ISSUE THREAD

**Issue by chengshiwen** [oam-dev/kubevela#1448]
@wonderflow @shikanon 
After comparison and discussion as follows, `alpine` base image will be a better choice. And the `BASE_IMAGE` argument can be used for users to override the base image. So the current known needs have been met.

|                                            | Ubuntu   | Debian  | Alpine  | Distroless |
| ------------------------------------------ | -------- | ------- | ------- | ---------- |
| Popularity                                 | Low      | High    | High    | Medium     |
| Image Size (latest, uncompressed)          | 72.9MB   | 114MB   | 5.61MB  | 1.82MB     |
| Image Size (latest, compressed)            | 27.25 MB | 48.1 MB | 2.68 MB | 625KB      |
| Security                                   | Medium   | Medium  | High    | High       |
| Install Package (like ca-certificates)     | Yes      | Yes     | Yes     | No         |
| Debug (like attaching container by `bash`) | Easy     | Easy    | Easy    | Hard       |
| Extensibility (like 2nd development)               | Easy     | Easy    | Easy    | Hard       |

**Comment by ryanzhang-oss** [comment]
Who uses this base image and where?

**Comment by wonderflow** [comment]
@ryanzhang-oss  KubeVela Controller

**Comment by shikanon** [comment]
Great!
