### ISSUE TITLE
update application will see appContext update failed error-log

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela#1451]
**Describe the bug**
update a application, vela-core will print a applicationContext update status error

**To Reproduce**
1. create application
2. update application
3. check vela-core log See error

**Screenshots**
![image](https://user-images.githubusercontent.com/77846369/114163436-c4a32800-995c-11eb-808b-49c791665f77.png)

**Cluster information**
Describe your kubernetes cluster information.
- Kubernetes Version [e.g. 1.18.9]

**Comment by ryanzhang-oss** [comment]
this error should be transiant
