### ISSUE TITLE
[Feature] Why the service name must be unique under one env other than application？

### ISSUE THREAD

**Issue by rapkey** [oam-dev/kubevela#1491]
I have severral applications with many services for each aplication. Got error when there are the same service name even if they are not under the same applicaion.

**Comment by wonderflow** [comment]
Yes, this is a known issue as we use the service name to create underlying resources. These resources should have unique name.

App myapp -- (service: mysvc) -- K8s Deployment(mysvc)

**Comment by charles-woshicai** [comment]
It's the limitation of `kubernetes`, the name of k8s resources like `Deployment` is an attribute of its `metadata`.

Docs ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

```
Each object in your cluster has a Name that is unique for that type of resource
```

**Comment by rapkey** [comment]
@charles-woshicai 
why not add a app-name prefix before the service and deployment or other resources under app while they are created by kubevela?
For ex:
app name: demo-app1
service name: service1

then the service name in k8s is `demo-app1-service1`

**Comment by rapkey** [comment]
@wonderflow 
So, it's not an `enhancement` in the nearest release but a `question` need to be discussed？

**Comment by wonderflow** [comment]
Yes, we need to discuss more. `a app-name prefix` doesn't fix the issue, it makes the underlying resource has complex name and can't be understood clearly.

**Comment by rapkey** [comment]
@wonderflow 
There are many apps develop by different engineer running in one k8s cluster. Name conflict  is bothered.
Is there any recommend solution for this?

**Comment by rapkey** [comment]
@wonderflow 
Also I cant specify the namespace of the application except for change env.But if specify different env for each applicaton, also need create all the workloads and traits under every env.

**Comment by wonderflow** [comment]
Will it be confuse for users to see their underlying component resources has a prefix of app-name? And was it possible for the user add the prefix by themselves?

**Comment by charles-woshicai** [comment]
How about add a random hash to the end of name? Just like what pod was doing.

We could add `owner-reference` to bind the service and application.

E.g:
```
app name: demo-app1
service name: service1

runtime service name: service1-a8e809a
```

**Comment by charles-woshicai** [comment]
> How about add a random hash to the end of name? Just like what pod was doing.
> 
> We could add `owner-reference` to bind the service and application.
> 
> E.g:
> 
> ```
> app name: demo-app1
> service name: service1
> 
> runtime service name: service1-a8e809a
> ```

And I think it could be an opitional feature, only the application with specific annotaion like `vela.io/randomName: 'enable'` would enable it

**Comment by rapkey** [comment]
> How about add a random hash to the end of name? Just like what pod was doing.
> 
> We could add `owner-reference` to bind the service and application.
> 
> E.g:
> 
> ```
> app name: demo-app1
> service name: service1
> 
> runtime service name: service1-a8e809a
> ```

It's more confuse for users, cos I can't  konw which ones belong to my app except get more info by `kubectl describe` for ex.

**Comment by wonderflow** [comment]
> > How about add a random hash to the end of name? Just like what pod was doing.
> > We could add `owner-reference` to bind the service and application.
> > E.g:
> > ```
> > app name: demo-app1
> > service name: service1
> > 
> > runtime service name: service1-a8e809a
> > ```
> 
> It's more confuse for users, cos I can't konw which ones belong to my app except get more info by `kubectl describe` for ex.

yes, I won't vote for the random suffix design
