### ISSUE TITLE
[BUG] refine output for `vela app:status`

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#150]
By default, only important status should be displayed and detailed information could only be shown with flag like `--extended (-e)` per the suggestion from a community user.

![image](https://user-images.githubusercontent.com/2805315/90086153-53b75c00-dd4c-11ea-9fc4-73dd74c0bda5.png)

**Comment by wonderflow** [comment]
To refine status output, we need use health scope ,and  implement `healthchecktrait` for command resource status check. https://github.com/crossplane/oam-kubernetes-runtime/pull/160

**Comment by captainroy-hy** [comment]
@wonderflow @zzxwill maybe I can help on this issue. Could you please assign it to me?

**Comment by wonderflow** [comment]
1. adding health scope for core workload automatically
2. using status output from Heath scope as part of `vela app status` output
3. implement `healthchecktrait` for common resource

**Comment by captainroy-hy** [comment]
almost done but still in need of merging dependency [pr](https://github.com/crossplane/oam-kubernetes-runtime/pull/194) of oam controller.

**Comment by wonderflow** [comment]
thanks @captainroy-hy
