### ISSUE TITLE
Vela CLI installation PowerShell script error: Cannot convert 'System.Object[]' to the type 'System.Uri'...

### ISSUE THREAD

**Issue by suraciii** [oam-dev/kubevela#1536]
**Describe the bug**

There's an error when executing the PowerShell script to install vela cli:
> Downloading https://api.github.com/repos/oam-dev/kubevela/releases/assets/35181884 https://api.github.com/repos/oam-dev/kubevela/releases/assets/35181870 ...
iex : Cannot convert 'System.Object[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not
supported.
At line:1 char:52

**To Reproduce**
``` powershell
iwr -useb https://kubevela.io/script/install.ps1 | iex
```

**Expected behavior**
The installation script should run to end without errors.

**Additional context**
It seems like the newest (v1.0.3) release breaks the script, the following query results to two assets:
https://github.com/oam-dev/kubevela.io/blob/b3342150744a60ac0fb428ba88a946941a4e215b/static/script/install.ps1#L67
``` powershell
$windowsAsset = $releases | Where-Object { $_.tag_name -notlike "*rc*" } | Select-Object -First 1 | Select-Object -ExpandProperty assets | Where-Object { $_.name -Like "*${os_arch}.zip" }
```

**Comment by zzxwill** [comment]
@suraciii Thanks for reporting this problem.

>**Additional context**
It seems like the newest (v1.0.3) release breaks the script, the following query results to two assets:
https://github.com/oam-dev/kubevela.io/blob/b3342150744a60ac0fb428ba88a946941a4e215b/static/script/install.ps1#L67
``` powershell
$windowsAsset = $releases | Where-Object { $_.tag_name -notlike "*rc*" } | Select-Object -First 1 | Select-Object -ExpandProperty assets | Where-Object { $_.name -Like "*${os_arch}.zip" }
```

@yangsoon Do you any idea why this happened?

**Comment by zzxwill** [comment]
I've reproduced this issue in a Windows server. I need more time to investigate.

**Comment by suraciii** [comment]
@zzxwill I think it's because the v1.0.3 release has both "kubectl-vela" and "vela" assets, and it impacts the filter `"*${os_arch}.zip"`.
So change the filter to `"vela-*${os_arch}.zip"` may solve this issue.

**Comment by wonderflow** [comment]
@suraciii Hi, can you help send a PR and check?
