### ISSUE TITLE
[Feature] doc site will fail to build for release branch update

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1544]
**Is your feature request related to a problem? Please describe.**

Now we have configured the v1.0 as the current website version in https://github.com/oam-dev/kubevela.io/blob/main/docusaurus.config.js#L150

When the release-1.0 updated, the doc of website will be deleted(https://github.com/oam-dev/kubevela/blob/master/hack/website/release.sh#L88-L91 and https://github.com/oam-dev/kubevela/blob/master/hack/website/release.sh#L60-L63) and re-generate( https://github.com/oam-dev/kubevela/blob/master/hack/website/release.sh#L75 and https://github.com/oam-dev/kubevela/blob/master/hack/website/release.sh#L103).

Unfortunately, the docusaurus need the configured version exist to generate the version. Which means, we can't update the revision of docs in use. 

**Describe the solution you'd like**

After delete the revision we need to modify the config file(https://github.com/oam-dev/kubevela.io/blob/main/docusaurus.config.js#L150).

Use `lastVersion: 'current'` instead of `lastVersion: 'v<x.y>',`

And generate the version. After that, we should change it back, use `lastVersion: 'v<x.y>',` to replace `lastVersion: 'current'`

**Describe alternatives you've considered**

**Additional context**

**Comment by charles-woshicai** [comment]
Is related to #1518 ?

**Comment by wonderflow** [comment]
yes, they're related @charles-woshicai
