### ISSUE TITLE
[Feature] Manage the DAG of the component

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#1551]
Consider generating an Argo workflow to apply if `dependsOn` is present in `Application`. Also, it's simpler than reusing data input/output IMO.

**Comment by charles-woshicai** [comment]
Not sure what's the exact situation, in my understanding `argo workflow` requires `argo runtime` that argo crds to be installed and related controllers to run .

**Comment by charles-woshicai** [comment]
> Not sure what's the exact situation, in my understanding `argo workflow` requires `argo runtime` that argo crds to be installed and related controllers to run .

Is this expected?

**Comment by resouer** [comment]
@charles-woshicai yes, or we can also import argo lib, this is not a blocker.

**Comment by hongchaodeng** [comment]
Closing this since we already model components as DAG in CUE flows.
