### ISSUE TITLE
Terraform application hit issue "status.currentBatch: Required value, status.rollingState: Required value"

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1594]
**Describe the bug**

Applying the application `terraform-webapp` https://github.com/oam-dev/samples/pull/59, it hit the following issue.

`
{"level":"error","ts":1619780692.9016252,"logger":"Application","msg":"[Update] application status","application":"default/terraform-webapp","error":"Application.core.oam.dev \"terraform-webapp\" is invalid: [status.currentBatch: Required value, status.rollingState: Required value, status.upgradedReadyReplicas: Required value, status.upgradedReplicas: Required value]","stacktrace":"github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application.(*Reconciler).Reconcile\n\t/Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go:173\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/zhouzhengxi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/zhouzhengxi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/zhouzhengxi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/Users/zhouzhengxi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/Users/zhouzhengxi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/zhouzhengxi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/zhouzhengxi/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90"}

`

**To Reproduce**

Follow readme steps https://github.com/oam-dev/samples/pull/59/files#diff-581ea7feb97b57c66b5ad10b1c47976ff168261020de218a35fcb8d28f7eff68.

**Comment by wonderflow** [comment]
please try:
```
kubectl apply -f https://raw.githubusercontent.com/oam-dev/kubevela/master/charts/vela-core/crds/core.oam.dev_applications.yaml
```

**Comment by zzxwill** [comment]
Thanks, by applying this latest application CRD, the issue went away.
