### ISSUE TITLE
[Feature] Alibaba Cloud load balancer as a Kubernetes Ingress controller

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1606]
**Is your feature request related to a problem? Please describe.**

Supporting Alibaba Cloud [load balancer as a Kubernetes load balancer, which can work as an alternative [route trait](https://github.com/oam-dev/catalog/tree/master/traits/routetrait) in KubeVela.

**Describe the solution you'd like**

#### 1.supported protocols

TCP/UDP/http/https?

- CLB or ALB?

Alibaba Cloud load balancer has two products, (CLB + ALB)](https://help.aliyun.com/document_detail/196874.html?spm=5176.13094714.0.dexternal.77b21eb9zmZ57q). CLB, known as SLB before, is good at layer-4, and has some basic ability on layer-7, while ALB is powerful in layer-7.

#### 2. multi-tenant(?)

- LB instance number: Just one or each one for one application

## Integrate ingress as a networking trait

Use `CUE` module to wrap the LB ingress controller as a networking route trait.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
https://kubernetes.io/blog/2021/04/22/evolving-kubernetes-networking-with-the-gateway-api/
