### ISSUE TITLE
The properties table for "vela show annotations" is empty

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1618]
**Describe the bug**

Applying [annotation trait](https://github.com/oam-dev/kubevela/blob/3be63bba91117272b2704953d2255d73ddbd304f/charts/vela-core/templates/defwithtemplate/annotations.yaml), "vela show annotations" display none of properties.

```
vela show annotations
# Properties
+------+-------------+------+----------+---------+
| NAME | DESCRIPTION | TYPE | REQUIRED | DEFAULT |
+------+-------------+------+----------+---------+
+------+-------------+------+----------+---------+
```

**Comment by BinaryHB0916** [comment]
Using in KubeVela 1.0.7, this problem still exists.

**Comment by wonderflow** [comment]
Please try `v1.1.0-rc.1` client

**Comment by BinaryHB0916** [comment]
tried in v1.1.0-rc.1, it works!
