### ISSUE TITLE
[Bug] Rollout failed when execute cloneset-rollout examples in docs 

### ISSUE THREAD

**Issue by wangyuan249** [oam-dev/kubevela#1644]
**Describe the bug**
Rollout failed when execute cloneset-rollout examples in docs 

**Steps to reproduce the behavior**
1.  Follow the instructions in docs/examples/cloneset-rollout/README.md
![image](https://user-images.githubusercontent.com/35907099/117934839-a8b4ec80-b335-11eb-8f64-3cdb31fba0cb.png)
2. When executed instructions in step 2, the approllouts will failed.
![image](https://user-images.githubusercontent.com/35907099/117931936-62aa5980-b332-11eb-8e58-e3c71f8913fb.png)
The detailed information of the approllout  is provided below
```shell
kubectl get approllouts rolling-example -o yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1beta1","kind":"AppRollout","metadata":{"annotations":{},"name":"rolling-example","namespace":"default"},"spec":{"componentList":["metrics-provider"],"rolloutPlan":{"rolloutBatches":[{"replicas":1},{"replicas":3}],"targetSize":5},"targetAppRevisionName":"test-rolling-v1"}}
  creationTimestamp: "2021-05-11T08:45:55Z"
  finalizers:
  - finalizers.approllout.oam.dev
  generation: 1
  managedFields:
  - apiVersion: core.oam.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:componentList: {}
        f:rolloutPlan:
          .: {}
          f:rolloutBatches: {}
          f:targetSize: {}
        f:targetAppRevisionName: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-05-11T08:45:55Z"
  - apiVersion: core.oam.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
      f:status:
        .: {}
        f:batchRollingState: {}
        f:conditions: {}
        f:currentBatch: {}
        f:lastTargetAppRevision: {}
        f:rollingState: {}
        f:rolloutOriginalSize: {}
        f:rolloutTargetSize: {}
        f:upgradedReadyReplicas: {}
        f:upgradedReplicas: {}
    manager: kubevela
    operation: Update
    time: "2021-05-11T08:45:58Z"
  name: rolling-example
  namespace: default
  resourceVersion: "2010424"
  selfLink: /apis/core.oam.dev/v1beta1/namespaces/default/approllouts/rolling-example
  uid: 24a6b0fa-c5f1-47bf-bb19-dc101ef5aa51
spec:
  componentList:
  - metrics-provider
  rolloutPlan:
    rolloutBatches:
    - replicas: 1
    - replicas: 3
    targetSize: 5
  targetAppRevisionName: test-rolling-v1
status:
  batchRollingState: batchInitializing
  conditions:
  - lastTransitionTime: "2021-05-11T08:45:58Z"
    message: the rollout plan changed on no-op scale, total batch size = 4, targetSize
      size = 5
    reason: ""
    status: "False"
    type: RolloutSpecVerifying
  currentBatch: 0
  lastTargetAppRevision: test-rolling-v1
  rollingState: rolloutFailed
  rolloutOriginalSize: 5
  rolloutTargetSize: 5
  upgradedReadyReplicas: 0
  upgradedReplicas: 0
```
**Possible reason for rollout failure**
The rollout strategy described in appRollout-scale.yaml maybe wrong.
```shell
  componentList:
    - metrics-provider
  rolloutPlan:
    targetSize: 5
    rolloutBatches:
      - replicas: 1
      - replicas: 3
```
I communicated with yike and and attempt to change with 
```shell
targetSize: 5
    rolloutBatches:
      - replicas: 2
      - replicas: 3
```
But it didn't work.

The example rollout plan provided in kubevela.io can rollout success.
```shell
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  targetAppRevisionName: test-rolling-v1
  componentList:
    - metrics-provider
  rolloutPlan:
    rolloutStrategy: "IncreaseFirst"
    rolloutBatches:
      - replicas: 10%
      - replicas: 40%
      - replicas: 50%
    targetSize: 5
```

**Comment by wangyuan249** [comment]
@wangyikewxgm

**Comment by wangyikewxgm** [comment]
Does the issue be same with #1629 ?

**Comment by Alpacius** [comment]
> Does the issue be same with #1629 ?

I think so. Both cloneset and deployment application bootstrap use their scaler controller with [the very same logic for batch verification](https://github.com/oam-dev/kubevela/blob/58b3fffa36991a0d8504ae5ad70e70baa0749483/pkg/controller/common/rollout/workloads/common.go#L59), which has an initial size of 1.

When all batches are represented in percentage, target size could be alway filled exactly.

**Comment by ryanzhang-oss** [comment]
@wangyuan249  the example is not updated, please try

```
kubectl apply -f docs/examples/cloneset-rollout/app-scale.yaml
kubectl apply -f docs/examples/cloneset-rollout/appRollout-scale.yaml
```

**Comment by wangyuan249** [comment]
@ryanzhang-oss thanks for your advice!  It can rollout success with changing : apply app-scale.yaml.  But the only difference between  the  app-scale.yaml  and app-source.yaml  is an replicas value statement.  May be I should  read carefully about the strategy of rolling-out in kubevela code.  It seems that the rollout plan is not absolutely correct or not, we should consider it with the combination of app statement.

**Comment by ryanzhang-oss** [comment]
> @ryanzhang-oss thanks for your advice! It can rollout success with changing : apply app-scale.yaml. But the only difference between the app-scale.yaml and app-source.yaml is an replicas value statement. May be I should read carefully about the strategy of rolling-out in kubevela code. It seems that the rollout plan is not absolutely correct or not, we should consider it with the combination of app statement.

The scale operation needs to manipulate the replicas fields. Therefore, the component itself cannot set the replica value. That's the fundamental point.
