### ISSUE TITLE
[website] all relative urls link error when current page url ends with slash

### ISSUE THREAD

**Issue by llhuii** [oam-dev/kubevela#1659]
**Describe the bug**

All relative urls link error when current page url ends with slash.

**To Reproduce**

For example:
1. Go to the [install page](https://kubevela.io/docs/install).
2. Click the [upgrade guide] link.
3. It shows "Page Not Found" error.

**Expected behavior**

Step 3 should show the truly [upgrade-guide page](https://kubevela.io/docs/advanced-install#upgrade)

**Screenshots**

![image](https://user-images.githubusercontent.com/419660/118241644-f9ac1880-b4ce-11eb-8cc9-5d2e40544608.png)

![image](https://user-images.githubusercontent.com/419660/118241831-2f510180-b4cf-11eb-9703-a6db36a3574f.png)

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
@llhuii Hi, thanks for reporting, would you like to fix it? I think we need to trime the slash.

**Comment by llhuii** [comment]
@wonderflow Hi, any hint to where to trim the slash? It seems not trivial to me.

**Comment by wonderflow** [comment]
ping @yangsoon @sunny0826  please help
