### ISSUE TITLE
[Makefile] the issues of `make docs-build`

### ISSUE THREAD

**Issue by llhuii** [oam-dev/kubevela#1665]
Tracking some issues I found when `make docs-build`
## issue 1:
Error msg: 
```
hack/website/test-build.sh: 20: hack/website/test-build.sh: source: not found
```
Reason: In my linux machine(ubuntu 18.04), /bin/sh is the symbolic of `/bin/dash` having no `source` builtin command

How to fix: replace sh of `sh hack/website/test-build.sh`  to bash.

## issue 2: 
When kustomize/node/yarn command are missed, add some hints or install-links-or-commands wouble be more friendly ​for new-learners.

## issue 3:
Error msg: 
```
Error: Docs markdown link couldn't be resolved: (vela_system.md) in /root/kubevela/git-page/docs/cli/vela_system_cue-packages.md for version current
    at Array.forEach (<anonymous>)
Error: Docs markdown link couldn't be resolved: (vela_system.md) in /root/kubevela/git-page/docs/cli/vela_system_live-diff.md for version current
    at Array.forEach (<anonymous>)
Client bundle compiled with errors therefore further build is impossible.
```

Reason: 
[vela_system_live-diff.md](https://github.com/oam-dev/kubevela/blob/master/docs/en/cli/vela_system_live-diff.md#see-also) as said in this one [doc](https://github.com/oam-dev/kubevela/tree/master/docs#add-or-update-docs)

How to fix: 
1. add `python3 ./hack/website/clean-md.py ./docs/en` in docs-build target before `bash hack/website/test-build.sh` as done in https://github.com/oam-dev/kubevela/blob/master/.github/workflows/check-docs.yml#L21
2. Or fix the master files to remove `.md` suffix?

## issue 4:
make docs server host(default 127.0.0.1)/port(3000) configurable especially `host`, since in general linux os has no browser.

How:  read some envs(e.g. HOST/PORT) and modify the start of package.json  `  "start": "docusaurus start --host 0.0.0.0 --port 8000"`

**Comment by wonderflow** [comment]
Thanks for reporting. All good catches!

**Comment by llhuii** [comment]
In the bash function checkDocusaurus, ` [ --d $1 ]` should be ` [ -d $1 ]`
https://github.com/oam-dev/kubevela/blob/a11ae2f95d3f1023e65a6355905da2f6852f7da1/hack/website/helpers.sh#L21
