### ISSUE TITLE
[Feature] replace ResourceTracker with GC/Finalizer mechanism of Application

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1719]
**Is your feature request related to a problem? Please describe.**

Currently, we use `ResourceTracker` to track cluster-scoped and cx-namespace resources because these resources cannot be cascadingly deleted with the deletion of their owner application.
Along with the refactor work #1705 , application should have GC/Finalizer mechanism instead of purely cascading deletion.
GC/Finalizer will treat cluster-scoped/cx-namespace/normal resources equally. Thus, it's no need to maintain `ResourceTracker`.

**Describe the solution you'd like**

Application status should record its all resources' typed references. 
Do GC in each round of reconciliation.
Do finalizer for cluster-scope/cx-namespace resources (or always do finalizer for any resources, easier to implement)

**Describe alternatives you've considered**

**Additional context**

\cc @wonderflow @wangyikewxgm

**Comment by wangyikewxgm** [comment]
You mean delete all related cluster/cx-namespace resources in finalizer phase?

**Comment by wangyikewxgm** [comment]
I think this make sense.

**Comment by wonderflow** [comment]
I hope we still keep the `ResourceTracker ` object and write a controller to handle all the GC job, it will be more clean and the main Application controller will be more robust

**Comment by wonderflow** [comment]
Can we close this issue? I think it's finished

**Comment by captainroy-hy** [comment]
@wonderflow Sure. Close for it's fixed in #1763 .
