### ISSUE TITLE
Ingress trait definition uses old Ingress CRD version

### ISSUE THREAD

**Issue by kminder** [oam-dev/kubevela#1726]
Was working through the KubeVela 1.0 install and quick start docs. Tried both KinD and minikube versions. The health check is reporting an error.

```
$ kubectl get application first-vela-app -o yaml
...
  - lastTransitionTime: "2021-05-25T22:14:40Z"
    message: 'app=first-vela-app, comp=express-server, trait=ingress, check health
      error: get template context: failed to get obj express-server with gvk networking.k8s.io/v1beta1,
      Kind=Ingress : ingresses.networking.k8s.io "express-server" not found'
    reason: ReconcileError
    status: "False"
    type: HealthCheck

```
The ingress appears to be present.
```
$ kubectl get ingresses -n vela-system express-server
NAME             CLASS    HOSTS                 ADDRESS        PORTS   AGE
express-server   <none>   testsvc.example.com   192.168.49.2   80      34m
```
The app is working.
```
$ curl -H "Host:testsvc.example.com" http://192.168.49.2
<xmp>
Hello World
[removed whale ASCII art]
</xmp>
```
Looks like a version mismatch (i.e. v1 vs v1beta1)? Does the ingress trait definition need to be updated or a different ingress-nginx version installed?
```
$ kubectl get ingresses -n vela-system express-server -o yaml | more
apiVersion: networking.k8s.io/v1
kind: Ingress
...
```

**Comment by Chwetion** [comment]
could you provider your k8s version, kubevela version and provider detail use command `kubectl describe traitdefinitions.core.oam.dev -n vela-system ingress`

**Comment by wonderflow** [comment]
We should use `networking.k8s.io/v1` to replace `networking.k8s.io/v1beta1` in the ingress trait.

**Comment by Chwetion** [comment]
This api resource version is used since k8s 1.19, Does this mean that the ingress trait is no longer supported for versions below 1.19, or the ingress trait is modified to provide a trait compatible with the old version? @wonderflow

**Comment by wonderflow** [comment]
I add a ingress-1-20 for work around
