### ISSUE TITLE
embedded metadata schema in CRD is not generated 

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#1730]
`appRevision.Spec.Application` [use Application as field type.](https://github.com/oam-dev/kubevela/blob/181bcda66a859cc74ce8561b8e9176d814d16021/apis/core.oam.dev/v1beta1/applicationrevision_types.go#L31), because of the upstream issue [kubernetes-sigs/controller-tools#448](https://github.com/kubernetes-sigs/controller-tools/issues/448), embedded metadata schema [cannot be generated](https://github.com/oam-dev/kubevela/blob/181bcda66a859cc74ce8561b8e9176d814d16021/charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml#L51-L52). Same issue happens to CompDef,TraitDef used in AppRevision.
That results in the resources(App,CompDefiniton,TraitDefinition) stored in appRevision has no metadata. 

Is it by design to omit metadata of these resources?
If not and require to fix. Noticing the upstream issue has been fixed and merged [kubernetes-sigs/controller-tools#557](https://github.com/kubernetes-sigs/controller-tools/pull/557) recently, maybe we can consider upgrading controller-gen from v0.2.4 to v0.6.0-beta.0

/cc @wonderflow @yangsoon

**Comment by captainroy-hy** [comment]
After discussion with @wonderflow. Upgrading dependency is too heavy now. As a workaround, currently we can get app's lables/annots from `appRevision.Spec.ApplicationConfiguration`.

**Comment by wonderflow** [comment]
We should still keep the issue open, until we finally upgrade the dependency.
