### ISSUE TITLE
Unify the recommended way to install KubeVela CLI

### ISSUE THREAD

**Issue by p-null** [oam-dev/kubevela#1737]
**Is your feature request related to a problem? Please describe.**

In the vela installation section, it would be more intuitive if the doc shows installing vela as a kubectl plugin as a recommended way.
Since in most part of the doc, the command used is `kubectl vela` instead of `vela`. 

If you install the cli, you may be confused to find the corresponding command from `kubectl vela`.
e.g. those two commands are not interchangeable: 
`kubectl vela comp --discover` != `vela comp --discover` or `vela components --discover`

**Describe the solution you'd like**
I don't have a preferance bewteen `vela` or `kubectl vela`, we just need to 
1. unify the command (either `vela` or `kubectl vela`) in docs
2. show the unified CLI as the recommended way

**Describe alternatives you've considered**
Probably just keep one CLI, what's the benefit of maintaining two CLI: `vela` and `kubectl vela`?

**Comment by wonderflow** [comment]
Sorry for the confusion, I think we should align the commands and experience.

`vela` is for App-Centric developer which uses `Appfile`, while `kubectl vela` is a plugin for k8s centric users.

**Comment by resouer** [comment]
> vela is for App-Centric developer which uses Appfile, while kubectl vela is a plugin for k8s centric users.

@wonderflow this dosen't make sense to me, please clearly define *what is the user interface of KubeVela* and fix this issue ASAP.

The users (application team) are expected to use `vela CLI` (including Appfile) and GUI console to interact with KubeVela, and Kubernetes API resources are designed for systems to consume only.

We need to consider making `Appfile` a CUE object, this will be natural.

**Comment by wonderflow** [comment]
Now they're completely aligned in v1.2.0 https://github.com/oam-dev/kubevela/releases/tag/v1.2.1
