### ISSUE TITLE
[Feature] Use vela-cli to simplify the process of deploy OCM

### ISSUE THREAD

**Issue by yangsoon** [oam-dev/kubevela#1757]
**Is your feature request related to a problem? Please describe.**

Use kubectl vela to simplify the process of deploy OCM. 

1. Use  kubectl vela to specify the master cluster

``` shell
kubectl vela cluster init --config=./kube/hub-kubeconfig
```

2.  Register slave cluster

``` shell
kubectl vela cluster register cluster1
```

**Describe the solution you'd like**

ocm already has an installation tool https://github.com/open-cluster-management-io/clusteradm, We can import and use the functions in this repo. but we will merge the `clusteradm join` and `clustardm accept` to one step `kubectl vela cluster register`.

**Comment by wonderflow** [comment]
we will just write a doc to do that

**Comment by yangsoon** [comment]
refer to https://github.com/oam-dev/kubevela/pull/2599
