### ISSUE TITLE
[Feature] Workaround to enable re-run single jobs 

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1781]
Many Github users are expecting Github to enable the ability to re-run single jobs in workflow https://github.com/actions/runner/issues/432, so do we as it's cost another twenty minutes to rerun a failed e2e or unit-test job. But the feature hasn't come out.

Here is a workaround from @salem7 to fix the problem by splitting workflow https://hsalem.com/posts/ability-to-rerun-single-jobs-in-github-actions.html.

For example, we can split workflow `go` to several workflows, in each of which, contains e2e-tests, unit-tests respectively. We just need to rerun e2e-tests, without re-running unit-tests, which will save a lot of time.

![image](https://user-images.githubusercontent.com/2805315/121330734-dc8d2d00-c948-11eb-9ad8-b2c77664bdeb.png)

Do you think it's a good idea? If yes, I would be pleased to overtake the split work. Thanks.

**Comment by wonderflow** [comment]
I doubt it's really save time. Now the time cost of unit test is ~15min while the e2e cost ~20min. In fact what fails most is the e2e test. Rerun e2e test will cause rerun all the other test jobs but they run concurrently.

**Comment by zzxwill** [comment]
@wonderflow Splitting the workload into the current one, unit-test, and e2e-test, won't do bad for the CI, right?
You mention `what fails most is the e2e test`, I agree with you. But sometimes, re-running all jobs will fail the job which passed before, and sometimes, unit-test failed, in which situations, it saves time and improve the user experience.

But I have to admin re-running success jobs shouldn't fail, we have to improve the robustness of the testes.
