### ISSUE TITLE
[Feature] create github action bot for issue triage

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1806]
Follow the Grafana way: https://github.com/grafana/grafana/blob/main/.github/bot.md
Using the grafana-github-actions:  https://github.com/grafana/grafana-github-actions

TBD：

* https://github.com/oam-dev/kubevela/blob/main/.github/commands.json
* https://github.com/oam-dev/kubevela/blob/main/.github/commands.json

**Comment by wangyuan249** [comment]
/priority/important-soon

**Comment by wangyuan249** [comment]
/area/component

**Comment by wangyuan249** [comment]
/bot/question

**Comment by wangyuan249** [comment]
/type/enhancement

**Comment by FogDong** [comment]
/type/docs
