### ISSUE TITLE
[Feature] A perfect demo to of external capability for the app engine

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#181]
xref: https://github.com/rudoi/cruster-api

```
$ vela cap add cruster-api --alias pizaorder

$ vela svc run -t pizaorder  --address MY_HOME --pizzas [size=large,toppings=[sausage]] --name daily-piza-order
$ vela cron daily-piza-order -e "0 8 * * *"
```

/cc @szihai

**Comment by wonderflow** [comment]
We need to build a helm chart and workloadDefinition for it.

**Comment by wonderflow** [comment]
This is not good example, we don't have cron, and it's hard to get feedback from running.

I prepared one for demo https://github.com/oam-dev/catalog/blob/master/registry/kubewatch.yaml

We could configure webhook url to receive event notification if workload is updated or deleted.

closing
