### ISSUE TITLE
 allow revision created by outside system

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1818]
The background is in #1786 .

We should allow revision created by outside system. So we should add a mechanism to check if the revision already exist.

The quick solution could be:

1. calculate the revision hash
2. list all revision related(label selector app name)
3. check if there's existing revision with same hash and compare the spec. If they are deep equal, don't generate.

_Originally posted by @wonderflow in https://github.com/oam-dev/kubevela/issues/1786#issuecomment-864346846_

**Comment by wonderflow** [comment]
Not only apprevision but also ComponentRevision and TraitRevision as metioned in https://github.com/oam-dev/kubevela/issues/1786#issuecomment-864496947

**Comment by kinsolee** [comment]
Any progress to this issue ?

**Comment by LeoLiuYan** [comment]
I will create a PR about this feature in this afternoon.    @kinsolee   cc  @wonderflow
