### ISSUE TITLE
fail to install vela-core-legacy with kubernetes v1.15.3

### ISSUE THREAD

**Issue by ljn55966005** [oam-dev/kubevela#1835]
**Describe the bug**

```
# kubectl apply -f core.oam.dev_componentdefinitions.yaml
The CustomResourceDefinition "componentdefinitions.core.oam.dev" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[schematic].properties[terraform].properties[type].default: Forbidden: must not be set
```
the same error occured when i apply dev_workloaddefinitions , dev_traitdefinitions, dev_componentdefinitions, dev_traitdefinitions and dev_applicationrevisions

**Comment by wonderflow** [comment]
I'm sorry the community is not going to support K8s version < v1.18, I hope you can upgade your cluster. Thanks.

**Comment by wonderflow** [comment]
KubeVela will also clean the legacy support.
