### ISSUE TITLE
Cannot place application across multiple clusters via AppDeployment

### ISSUE THREAD

**Issue by fanzhihai0215** [oam-dev/kubevela#1909]
**Describe the bug**
Try to place application across multi-clustsers, but some problems occurred while deploying AppDeployment. I created Cluster CRD and its kubeconfig SecretRef, but nothing seems to happen. 

I followed [this tutorial](https://kubevela.io/docs/v1.1/end-user/scopes/appdeploy) to operate.

I see "Multi-Cluster Application Deployment was supported by the object called AppDeployment" in release v1.0.0, but i also see "Support multiple cluster and ENV" in release v1.1.0 as the main planning feature. Is there a possibility that the current version has not yet fully implemented the AppDeployment feature? Thanks.

**To Reproduce**
1. cluster.yaml
```
apiVersion: core.oam.dev/v1beta1
kind: Cluster
metadata:
  name: cluster-1
  labels:
    tier: production-1
spec:
  kubeconfigSecretRef:
    name: kubeconfig-cluster-1
---
apiVersion: core.oam.dev/v1beta1
kind: Cluster
metadata:
  name: cluster-2
  labels:
    tier: production-2
spec:
  kubeconfigSecretRef:
    name: kubeconfig-cluster-2
```
2. cluster-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-cluster-1
data:
  config: ...  # kubeconfig data
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-cluster-2
data:
  config: ... # kubeconfig data
```
3. appdeploy.yaml
```
apiVersion: core.oam.dev/v1beta1
kind: AppDeployment
metadata:
  name: sample-appdeploy
spec:
#  traffic:
#    hosts:
#      - example.com
#
#    http:
#      - match:
#          # match any requests to 'example.com/example-app'
#          - uri:
#              prefix: "/example-app"
#
#        # split traffic 50/50 on v1/v2 versions of the app
#        weightedTargets:
#          - revisionName: example-app-v1
#            componentName: testsvc
#            port: 80
#            weight: 50
#          - revisionName: example-app-v2
#            componentName: testsvc
#            port: 80
#            weight: 50

  appRevisions:
    - # Name of the AppRevision.
      # Each modification to Application would generate a new AppRevision.
      revisionName: example-app-v1

      # Cluster specific workload placement config
      placement:
        - clusterSelector:
            # You can select Clusters by name or labels.
            # If multiple clusters is selected, one will be picked via a unique hashing algorithm.
            labels:
              tier: production-1
            name: cluster-1

          distribution:
            replicas: 2

    - revisionName: example-app-v2
      placement:
        - clusterSelector:
            labels:
              tier: production-2
            name: cluster-2
          distribution:
            replicas: 2
```
4. errors when apply the AppDeployment
```
I0713 08:31:36.846311       1 appdeployment_controller.go:97] "Start to reconcile" appDeployment="default/sample-appdeploy"
I0713 08:31:36.969830       1 appdeployment_controller.go:235] "apply revision" revision="example-app-v1" cluster="cluster-1"
E0713 08:31:36.970465       1 appdeployment_controller.go:87] Failed to reconcile appDeployment default/sample-appdeploy: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0713 08:31:37.971420       1 appdeployment_controller.go:97] "Start to reconcile" appDeployment="default/sample-appdeploy"
I0713 08:31:37.971485       1 appdeployment_controller.go:235] "apply revision" revision="example-app-v1" cluster="cluster-1"
E0713 08:31:37.972258       1 appdeployment_controller.go:87] Failed to reconcile appDeployment default/sample-appdeploy: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
5. BTW, When I comment out the placement.clusterSelector.name, it works, but it can only be deployed in the current cluster.
```
    - revisionName: example-app-v2
      placement:
        - clusterSelector:
            labels:
              tier: production-2
#            name: cluster-2
          distribution:
            replicas: 2
```
**Expected behavior**
In my understanding, the result should be displayed by kubectl.
```
kubectl get po --context cluster-1
kubectl get po --context cluster-2
```
Can you add the result of placing application across multi-clustsers in the tutorial?

**KubeVela Version**
```
# vela version
Version: refs/tags/v1.1.0-alpha.4
GitRevision: git-93234e8
GolangVersion: go1.16.5
```

**Cluster information**
```
# kind version
kind v0.9.0 go1.15.2 linux/amd64
# kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
1. I'm not sure if my secret format is correct. The data.config should be just the certificate-authority-data in kubeconfig or the entire  kubeconfig file?
2. Is there a way to get the cluster status of multiple clusters like kubefed?
```
# kubectl -n kube-federation-system get kubefedclusters
NAME   AGE   READY
c1     14m   True
c2     18s   True
c3     6s    True
```

Thank you for your reply~

**Comment by hongchaodeng** [comment]
Hi. Let me help answer your questions:

> I'm not sure if my secret format is correct. The data.config should be just the certificate-authority-data in kubeconfig or the entire kubeconfig file?

Entire kubeconfig

> Is there a way to get the cluster status of multiple clusters like kubefed?

We are planning to use Open-Cluster-Management and Karmada as a Workflow Task plugin to deal with multi-cluster deployments. So you should be able to get cluster status via their APIs.

> I see "Multi-Cluster Application Deployment was supported by the object called AppDeployment" in release v1.0.0, but i also see "Support multiple cluster and ENV" in release v1.1.0 as the main planning feature. Is there a possibility that the current version has not yet fully implemented the AppDeployment feature? Thanks.

Let me provide more context: The AppDeployment will be broken into three Workflow Task definitions in the upcoming release which corresponds to its 3 features right now: Multi-cluster, Scaling, Traffic split. This will be implemented in the upcoming release.

**Comment by fanzhihai0215** [comment]
Great! The entire kubeconfig file works. 

In my test, there may be a little defect. After spinning up kind clusters, the API server address is like _127.0.0.1:xxxxx_ in kubeconfig. In order to deploy application across multi-clusters, should set container IP address as kube API endpoint in order for kind clusters to reach kube API servers in other kind clusters. Also the configuration of all kind clusters are in the same kubeconfig. Need to manually fill in each cluster secret instead of simply copying the kubeconfig.

It is recommended to add some instructions in the tutorial or provide a script to generate the cluster secret. 

Finally, can one AppRevision of Application be deployed on multi-clusters? It means split traffic on one version of the Application across multi-clusters.

@hongchaodeng

**Comment by wonderflow** [comment]
Now we have supported multi-cluster since v1.1 and appdeployment is deprecated, please use the new way, thanks! https://kubevela.io/docs/case-studies/multi-cluster
