### ISSUE TITLE
getCPUInfo for OS darwin

### ISSUE THREAD

**Issue by mrmartan** [oam-dev/kubevela#1924]
**Describe the bug**

```
ERRO[0000] failure getting variant                       error="getCPUInfo for OS darwin: not implemented"
```

**To Reproduce**

```zsh
vela components
```

**Expected behavior**

no error

**Screenshots**
<img width="920" alt="image" src="https://user-images.githubusercontent.com/2376580/125810830-b4ba38c8-be96-4fbf-9734-3db997a72a78.png">

**KubeVela Version**

1.0.7

**Cluster information**
client: 1.21.2
server: 1.19.11

**Additional context**

MacOS bigSur  
Apple M1 (ARMv8)

**Comment by wonderflow** [comment]
Thanks for reporting. It should be something related with `Apple M1 (ARMv8)`, and it doesn't affect the function.
