### ISSUE TITLE
make core-run report error ""Could not capability in ConfigMap"

### ISSUE THREAD

**Issue by woodgear** [oam-dev/kubevela#1959]
**Describe the bug**

**To Reproduce**

1. following [develop guide](https://github.com/oam-dev/kubevela/blob/master/contribute/developer-guide.md) to prepare dev env
2. make core-install && make check-install-def
**Expected behavior**

without any error.
**Screenshots**

![image](https://user-images.githubusercontent.com/16863223/126637797-42ca973b-f84e-4a5a-b97f-daef1b579536.png)

**KubeVela Version**
master (c508cd45c62a32b54d220a01fb56ca842938014a)

**Cluster information**

kindest/node:v1.16.15
**Additional context**

**Comment by chivalryq** [comment]
It's about generating OpenAPI JSON schema. That logs won't affect vela-core's function. If you are trying KubeVela you can simply ignore that by now.
Expectedly it will be fix after workflow feature finished. :)

**Comment by wonderflow** [comment]
dup with #1939
