### ISSUE TITLE
[Feature] Options to access to component properties and other component information in a trait

### ISSUE THREAD

**Issue by neinkeinkaffee** [oam-dev/kubevela#1984]
**Is your feature request related to a problem? Please describe.**
In my `TraitDefinitions` and `ComponentDefinitions` I would like to be able to access values from the objects that enclose the given trait or component. For example, I would like to access the properties of the enclosing component in a trait so that I can attach the trait resources to the component resources.
All my `TraitDefinitions` and `ComponentDefinitions` deploy resources to AWS with Terraform. An example would therefore be that a component provisions a bucket with a name specified in the component properties, and a trait attached to it needs to know the bucket name to deploy for example an IAM policy that refers to it.

**Describe the solution you'd like**
It would be great if the properties of an enclosing component could be made available to a given trait, e.g. as part of the `context` object. 
Additionally, pointers to all existing documentation and places in the source code that shed light on what context information about the enclosing application and component can be currently accessed from inside a component or trait would be super.
 
I've already received the following pointers (thanks a lot!)
- [templateContext struct definition in handle.go](https://github.com/oam-dev/kubevela/blob/3199fd75772b46acae12daf63855f1befdff61e5/pkg/cue/process/handle.go#L81-L101)
- [vela template context docs](https://kubevela.io/docs/next/cli/vela_template_context)

**Comment by wonderflow** [comment]
@neinkeinkaffee Why closed, have you fixed your issue?

**Comment by neinkeinkaffee** [comment]
Oh, sorry, no, I closed it as I then subsequently created issue #2007 that I felt was more concrete and didn't want to create the impression of submitting near-duplicate issues.

In the long term of course, it would be nice to come closer to feature parity between CUE and HCL in this regard, and also enabling sharing of the `context.output` between component and trait, and maybe even allowing `patch`ing of components by their traits...
