### ISSUE TITLE
[Feature]Discussion on Env CLI and env API

### ISSUE THREAD

**Issue by wenxinnnnn** [oam-dev/kubevela#200]
**Is your feature request related to a problem? Please describe.**

In my opinion, env init and evn specify that the namespace should be detached. In Env init, friendly prompts should be repeated.
Moreover, the idempotency of the interface PSOT / API / envs is inconsistent.

**Describe the solution you'd like**

cli:
`vale env init envname namespace nsname`
Envname presence will block and prompt.

`vale env config envname namespcae nsname`
Envname does not exist, will be blocked and prompted

api:
POST /api/envs/                     {"envName":"xxx"}
PUT  /api/envs/:envName      {"namespcae":"xxx"}

The other 1: expand the env describe field, because the env gradually increases, it is not easy to manage by env name alone.
`vale env config envname namespcae nsname describe  xxx `
PUT  /api/envs/:envName      {"namespcae":"xxx","describe":""}

The other 2:  currently get /API/envs does not support paging query.

**Comment by wonderflow** [comment]
I can't very understand this issue, you could describe in Chinese if you don't mind.

**Comment by wonderflow** [comment]
fixed by #215
