### ISSUE TITLE
applicationcontext status.conditions patch nothing

### ISSUE THREAD

**Issue by zjq123456** [oam-dev/kubevela#2008]
**Describe the bug**
ApplicationContext status patch data fail, because data is empty.

**To Reproduce**
file: pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller.go
line 99: appConfig.Status = appContext.Status
Solution Suggestion:  appContext.Status.DeepCopyInto(&appConfig.Status)

**Expected behavior**
Expect ApplicationContext status patch success.

**Screenshots**
![image](https://user-images.githubusercontent.com/14069938/127947970-7b847cb8-e573-4e95-aa3d-b368beee1a4a.png)
![image](https://user-images.githubusercontent.com/14069938/127948114-d93f71d8-aca7-4f46-98cc-0bdb788f0a51.png)
![image](https://user-images.githubusercontent.com/14069938/127948233-b0277b4e-5f54-43f7-b85b-12467e13aa40.png)
![image](https://user-images.githubusercontent.com/14069938/127947798-38202e45-8b34-4060-9c45-4def9272ec6a.png)

**KubeVela Version**
v1.0.7

**Cluster information**
Kubernetes Version [e.g. 1.18.8]

**Additional context**

**Comment by wonderflow** [comment]
@zjq123456 Thanks for your report, would you like to send a PR for it?

**Comment by zjq123456** [comment]
ok
