### ISSUE TITLE
Refactor appfile concept in Application resource rendering

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/kubevela#2015]
**Problem**
Now we have appfile concept in vela CLI. That part of code are in `reference/cli`. But we still have another type `appfile` in `pkg/appfile`, which is used in Application rendering. That may cause confusion for developer. 

**Solution I want**
Refactor the appfile concept in `pkg`, make it a helper type or something

**Comment by wonderflow** [comment]
It's implemented now
