### ISSUE TITLE
Provide a way to start up dashboard front-end service

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#204]
When running command `vela dashboard`, the front-end service needs to be started up. 
There won't be source code of dashboard under folder `dashboard` of the project, so it needs to provide a way on the start-up.

**Comment by zzxwill** [comment]
@hanxie-crypto Please help take a look at it.

**Comment by wonderflow** [comment]
I have fixed this issue, you can use it by `vela dashboard` now
