### ISSUE TITLE
[Feature] vela CLI support generate addon

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/kubevela#2112]
**Is your feature request related to a problem? Please describe.**

Now, We are using vela-templates/addons/gen_addon.go to generate addon. It's hard for user to generate addon themselves.

**Describe the solution you'd like**

Add addon scaffold and generation function in vela CLI.

It will be used like:

```shell
vela addon init --name my-addon

vela addon build -d ./my-addon
```

**Comment by barnettZQG** [comment]
As demand changes, let's close this first.
