### ISSUE TITLE
annotation and lable trait should also affect the workload object along with pod

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#2196]
Now our [annotation](https://github.com/oam-dev/kubevela/blob/master/vela-templates/definitions/internal/annotations.cue) and [label](https://github.com/oam-dev/kubevela/blob/master/vela-templates/definitions/internal/labels.cue) trait will patch to pod spec.

We should also patch to the workload itself like below:

```
labels: {
	type: "trait"
	annotations: {}
	labels: {}
	description: "Add labels for your Workload."
	attributes: {
		podDisruptive: true
		appliesToWorkloads: ["deployments.apps"]
	}
}
template: {
	patch: {
           metadata:{
              labels:{
		for k, v in parameter {
			"\(k)": v
		}
             }
          }
           spec: template: metadata: labels: {
		for k, v in parameter {
			"\(k)": v
		}
	}
       }
	parameter: [string]: string
}
```

**Comment by reetasingh** [comment]
@wonderflow I am interested in this issue. Assigning it to myself
/assign
