### ISSUE TITLE
componentdefinition_controller repeat run

### ISSUE THREAD

**Issue by zjq123456** [oam-dev/kubevela#2201]
componentdefinition_controller repeat run

**To Reproduce**

**Expected behavior**
componentdefinition_controller repeat run every hour, why? ComponentDefinition kubeease-job never changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14069938/131431445-6ef18b27-82d4-4e0b-b5d1-e54ffb731760.png)

**KubeVela Version**

v1.0.7

**Cluster information**
Kubernetes Version  v18.8

**Additional context**

**Comment by zzxwill** [comment]
@zjq123456 It's the default sync period for a Kubernetes controller https://github.com/oam-dev/kubevela/blob/master/cmd/core/main.go#L102.

**Comment by zjq123456** [comment]
What configuration is recommended for the production environment.

**Comment by zjq123456** [comment]
Applicationcontext_controller repeat run Every 20 to 30 minutes, why not one hour.

![image](https://user-images.githubusercontent.com/14069938/131434210-60777dfa-f88f-4e24-8f38-f38f76fbd375.png)

**Comment by Somefive** [comment]
> What configuration is recommended for the production environment.

The re-sync period is used for preventing configuration shifts. A short period will help fixing config shifts quickly but will lead to more CPU/Memory usage.

20min is okay for production. However, if you have lots of applications with limited controller resources, like 5,000 applications and 0.5 core 1 Gi resource, you might need to increase 20min to 1h to host more applications.

**Comment by zjq123456** [comment]
Thank you.
