### ISSUE TITLE
Component type field is not standardized?

### ISSUE THREAD

**Issue by majian159** [oam-dev/kubevela#2210]
### Discussed in https://github.com/oam-dev/kubevela/discussions/2203

<div type='discussions-op-text'>

<sup>Originally posted by **majian159** August 31, 2021</sup>
1. Whether the readinessProbe exists successThreshold?(does not exist in k8s)
![image](https://user-images.githubusercontent.com/10176784/131435036-ca431302-9904-4a09-af9c-bd7dde4a14cf.png)

2. Task component missing imagePullPolicy,imagePullSecrets
![image](https://user-images.githubusercontent.com/10176784/131435249-f01ff658-c567-49e0-bc2d-d7a7c11122ed.png)

Version: v1.1.0</div>

**Comment by wonderflow** [comment]
Sorry, we should align them.

1. add  imagePullPolicy,imagePullSecrets.
2. remove non exists field.
