### ISSUE TITLE
Traitdefinition_controller repeat run every 3 to 4 seconds

### ISSUE THREAD

**Issue by zjq123456** [oam-dev/kubevela#2238]
**Describe the bug**
Traitdefinition_controller repeat run every 3 to 4 seconds, why?

**To Reproduce**

**Expected behavior**
Default syncPeriod time is 1 hour.

**Screenshots**
![image](https://user-images.githubusercontent.com/14069938/132204859-8dcdc085-1425-45c7-861b-916de73ecbce.png)

**KubeVela Version**
v1.1.0

**Cluster information**
Kubernetes Version v1.18.8

**Additional context**

**Comment by yangsoon** [comment]
sorry, this bug has fixed in https://github.com/oam-dev/kubevela/pull/2157
