### ISSUE TITLE
[Chore] deprecate containerized workload and remove the related code

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#2261]
same as #2258

**Comment by reetasingh** [comment]
@wonderflow 
I have sone question on this issue

1. In e2e tests, like test/e2e-test/suite_test.go containerized workload is used in multiple places for WorkloadDefinition. I am replacing containerized workload with deployment in such places. Is this the right approach? 
2. I Am assuming we also have to remove references of containerized workload from health_scope controller. But I see that we sill have referecences for CheckPodSpecWorkloadHealth. while PodSpecWorkload is deprecated/

**Comment by wonderflow** [comment]
> In e2e tests, like test/e2e-test/suite_test.go containerized workload is used in multiple places for WorkloadDefinition. I am replacing containerized workload with deployment in such places. Is this the right approach?

Yes, that's good.

> I Am assuming we also have to remove references of containerized workload from health_scope controller. But I see that we sill have referecences for CheckPodSpecWorkloadHealth. while PodSpecWorkload is deprecated.

Yes, they're all deprecated, you can clean them together.
