### ISSUE TITLE
[Feature] support ARM64

### ISSUE THREAD

**Issue by syswu** [oam-dev/kubevela#2285]
**Is your feature request related to a problem? Please describe.**

I want run it on ARM64 based host platform. 

**Describe the solution you'd like**

build ARM64 based images

**Comment by Somefive** [comment]
Currently, we have not tested the ARM64 image in ARM64 environment, but we have tried to build ARM64 image and use it in some places. We might support it in later version such as 1.2 or 1.3. If you would like to have a try, you can clone the code and build it with `docker buildx` to build cross-platform images.

**Comment by wonderflow** [comment]
I think our vela-core image already support ARM64, what you mean here is vela cli, right?

Then it's duplicated with #961. I hope someone could help add the ARM64 cli build in our github action pipeline.

**Comment by wonderflow** [comment]
https://github.com/oam-dev/kubevela/releases/tag/v1.2.0-rc.2 supported
