### ISSUE TITLE
[Feature] overwrite the workload name with component name only if not defined

### ISSUE THREAD

**Issue by plpan** [oam-dev/kubevela#2312]
**Is your feature request related to a problem? Please describe.**
In some situation, I wish to use the same name for multiple components of different type in one application, e.g. the application name.

However, it's required to set different names for these components, and the name of the workload is set, by kubevela automatically, with the name of the component.
```
//// @assembly.go#assembleWorkload
// use component name as workload name
// override the name set in render phase if exist
wl.SetName(compName)
```

**Describe the solution you'd like**
Use component name as workload name only if the name of workload is not defined.
```
//// @assembly.go#assembleWorkload
// use component name as workload name only if not defined
if len(wl.GetName()) == 0 {
    wl.SetName(compName)
}
```

**Describe alternatives you've considered**
It's not forward compatible for those applications that overwrite the workload name with a different component name.

**Additional context**

**Comment by kinsolee** [comment]
My team have a similar scenario, we'd like to use our custom `workflowstep` to implement multi-version deployment.

We use the same component to apply multiple times in terms of different versions. 

We are going to pass the version field into component's properties in order to distinguish each `Deployment`. 

The `workflowstepdefinition` is like below:

```
...
applyVersion: op.#Steps & {
    load: op.#Load @step(1)
    
    apply: op.#Steps & {
	for compName, comp in load.value {
            applyComp: op.#ApplyComponent & {
	        value: comp & {
		    properties: {
			version:     parameter.version
			image:       "\(parameter.image)-\(parameter.version)"
		    }
	        }
            }
	}
    } @step(2)
}
...
```

And the `componentdefinition` is like below:

```
...
output: {
    apiVersion: "apps.openshift.io/v1"
    kind:       "DeploymentConfig"
    
    metadata: name:      "\(context.name)-\(parameter.version)"
    metadata: namespace: context.namespace
...
```

Since the ComponentManifest's name is rewritten by workload's name. It doesn't work now.

https://github.com/oam-dev/kubevela/blob/8407c0bf4d01db70f580910c03c7792c2dd6798c/pkg/appfile/appfile.go#L507

**Comment by wonderflow** [comment]
There have several discussion before, the general conclusion is:

Rollout controller need to control the name of the underlying resource, so kubevela override the name.

But I think it's also fine if the users don't want to use rollout.

So the conclusion here should be:

1. Support this feature => "Use component name as workload name only if the name of workload is not defined." 
2. If users specify it's name in componentDefinition, then the rollout (especially for deployment) should not work. We must add a webhook in this case, and report the error in condition of rollout CR.

**Comment by barnettZQG** [comment]
If a name is defined in a template, the template loses its reproducibility. Are we considering supporting user-defined workload names in components?
