### ISSUE TITLE
[BUG] Inconsistent workload between  garbageCollection and applyComponent

### ISSUE THREAD

**Issue by kinsolee** [oam-dev/kubevela#2316]
**Describe the bug**

Thanks to https://github.com/oam-dev/kubevela/pull/2304, now we could rewrite component's properties in the workflow. 

But application_controller.garbageCollection may fail if we rewrite component's properties in `workflowstepdefinition`.  

Failure will happen if we try to refer fields from `context.parameter` in `traitdefinition` but no such fields in component's properties.

**To Reproduce**

Let's say we have a trait to output a cronjob. Here we'd like to add a `version` label passed from `context.parameter.version`.
```
outputs: cronjob: {
    apiVersion: "batch/v1beta1"
    kind:       "cronjob"
    metadata: {
        namespace: context.namespace
        labels: {
	        app: "\(context.name)-cronjob"
                // Read from component's parameter
                version: "\(context.parameter.version)"
        }
    }
...
```
And we definitely declare the `version` field in component's parameter.
```
parameter: {
    cmd?: [...string]

    // +ignore
    version: *"" | string
}
```
When we go through the workflowstep below, it works fine because we declare the version field.
```
deploy: op.#Steps & {
    load: op.#Load @step(1)
    apply: op.#Steps & {
	    for compName, comp in load.value {
		    applyComp: op.#ApplyComponent & {
			    value: comp & {
				    properties: {
                                         version: "v1.1.1"
				    }
			    }
		    }
	    }
    } @step(2)
}
```

But vela-core will output error log likes below:
```
E0917 15:13:49.770521   29433 instance.go:81] "failed to have the workload/trait unstructured" err="metadata.labels.version: reference \"context\" not found"
```

Both `revision.cleanUpComponentRevision` and `application.AppHandler.applyComponentFunc` call `appfile.Appfile.GenerateComponentManifest` to generate ComponentManifest. 

But the `Appfile.Workloads` among them are different as they read from different source. 

One is from Applicaiton.Spec.Components https://github.com/oam-dev/kubevela/blob/8407c0bf4d01db70f580910c03c7792c2dd6798c/pkg/appfile/parser.go#L204,
another is from workflowstep's component with rewritten properties.
https://github.com/oam-dev/kubevela/blob/8407c0bf4d01db70f580910c03c7792c2dd6798c/pkg/workflow/providers/oam/apply.go#L57

**Expected behavior**
As we might apply multiple times from workflowstep. We should persist the written component properties into apprevision for consistency. 

**Screenshots**

**KubeVela Version**

Version: master
GitRevision: git-941c599a
GolangVersion: go1.17

**Cluster information**

**Additional context**

**Comment by leejanee** [comment]
The cause of the error is that  application/component revision GC executes the old `rendering` logic, we should refactor the revision GC.
