### ISSUE TITLE
[Feature] Use vela CLI to manage KubeVela version

### ISSUE THREAD

**Issue by Somefive** [oam-dev/kubevela#2338]
**Is your feature request related to a problem? Please describe.**

Currently, we install/upgrade/remove KubeVela by using Helm. However, helm itself do not upgrade CRD resources. Besides, when removing KubeVela, there are some complicated remaining resources which is out of the scope of `helm uninstall` which makes it hard to clean up. We should support it in Vela CLI.

**Describe the solution you'd like**

A list of command should be supported such as `vela install`, `vela uninstall`, `vela upgrade`.

**Describe alternatives you've considered**

Alternatively, we could provide some bash scripts to do such things so that user do not need to install vela CLI.

**Additional context**

**Comment by wonderflow** [comment]
it's already supported by using `vela install` in v1.2
