### ISSUE TITLE
[Feature] Form the ComponentDefinition、TraitDefinition and WorkflowStepDefinition  extended case list.

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#2352]
Kubevela needs to develop an ecosystem of extended capabilities, and before that, we need to build deliverables, tutorials, and user guides.

**Comment by FogDong** [comment]
ComponentsDefinition:
| Name | Description |
| :-----: |  :------------- |
| raw | raw allow users to specify raw K8s object in properties. |
| task | Describes jobs that run code or a script to completion. |
| webservice | Describes long-running, scalable, containerized services that have a stable network endpoint to receive external network traffic from customers. |
| worker | Describes long-running, scalable, containerized services that running at backend. They do NOT have network endpoint to receive external network traffic. |

TraitsDefinition:
| Name | Description |
| :-----: |  :------------- |
| annotations | Add annotations on K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| configmap | Create/Attach configmaps on K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| cpuscaler | Automatically scale the component based on CPU usage. |
| env | add env on K8s pod for your workload which follows the pod spec in path 'spec.template.' |
| expose | Expose port to enable web traffic for your component. |
| hostalias | Add host aliases on K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| ingress | Enable public web traffic for the component. |
| ingress-1-20 | Enable public web traffic for the component, the ingress API matches K8s v1.20+. |
| init-container | add an init container and use shared volume with pod. |
| labels | Add labels on K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| lifecycle | Add lifecycle hooks for the first container of K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| node-affinity | affinity specify node affinity and toleration on K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| pvc | Create a Persistent Volume Claim and mount the PVC as volume to the  first container in the pod |
| resource | Add resource requests and limits on K8s pod for your workload which follows the pod spec in path 'spec.template.' |
| rollout | rollout the component |
| scaler | Manually scale K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| service-binding | Binding secrets of cloud resources to component env |
| sidecar | Inject a sidecar container to K8s pod for your workload which follows the pod spec in path 'spec.template'. |
| volumes | Add volumes on K8s pod for your workload which follows the pod spec in path 'spec.template'. |

WorkflowStepDefinition:
| Name | Description |
| :-----: |  :------------- |
| apply-application | Apply application for your workflow steps. |
| apply-object | Apply raw kubernetes objects for your workflow steps. |
| apply-remaining | Apply remaining components and traits. |
| depends-on-app | Check or install depends-on Application. |
| deploy2env | Deploy env binding component to target env. |
| export2config | Export data to config map for your workflow steps. |
| export2secret | Export data to secret for your workflow steps. |
| read-object | Read objects for your workflow steps. |
| webhook-notification | Send message to webhook. |

Two more built-in WorkflowStepDefinitions but won't show in `/internal`:
| Name | Description |
| :-----: |  :------------- |
| apply-component | Apply component for your workflow steps. |
| suspend | Suspend workflow step. |

**Comment by hongchaodeng** [comment]
Here's my thoughts:

------

comps:
- raw -> k8s/k8s-object
- webservice -> about its template:
  - addRevisionLabel should be deprecated
  - Some of the fields should be converted to traits，e.g. health check、storage
  - The exposed paramters should be focused on Application use cases (i.e. app-centric). For example we should name it "storage" not "volumes".
- worker -> merged into webservice

traits:
- configmap/pvc/volumes -> merged into storage
- cpuscaler -> changed to autoscaler
- hostalias/ingress/expose  -> merged into netwrok
- init-container -> changed to preprocess or preparation-job

------

Let's have a meeting tomorrow to go over all definitions again to ensure all definitions are good for everyone. The definitions list has kinda blown up. We need to trim and renovate them for the good UX experience.

**Comment by barnettZQG** [comment]
The extended capability set is maintained in the [catalog](https://github.com/oam-dev/catalog) repo.
