### ISSUE TITLE
Support [Nocalhost](https://github.com/nocalhost/nocalhost) as developing tool with kubevela

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#2367]
[Nocalhost](https://github.com/nocalhost/nocalhost) is also an option to integrate, it's a developing tool similar with tilt. 

 refer to : https://nocalhost.dev/blog/api-six 

Add a nocalhost trait to debug app in developing time.

_Originally posted by @wonderflow in https://github.com/oam-dev/kubevela/issues/795#issuecomment-895890910_

**Comment by FogDong** [comment]
ref #2577 #2545
