### ISSUE TITLE
[Feature] define the workflow execution record CRD

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#2380]
* **Why do we need it?**

Workflow cannot track its historical state after multiple executions. We need to get more Workflow execution details and history for more control in the business dimension.

* **Want it to record the data？**

Recommendations include the following data:

- Execution time, critical logs, and the final status of each step.
- Overall status.
- Error information that needs to be told to the developer.

* **When it should be generated.**
Generate and update workflow multiple times each time it executes.

* **Key points:**

Given the large amount of data, there should be a healthy GC to recycle and only keep the last N records in the cluster.

**Comment by leejanee** [comment]
refer #2479
