### ISSUE TITLE
completion setup blocks the homebrew build process

### ISSUE THREAD

**Issue by chenrui333** [oam-dev/kubevela#2436]
Looks like since [1.1.0 release](https://github.com/Homebrew/homebrew-core/pull/83714), `vela completion bash` does not run properly during the build process, might need some help taking a look at it. Thanks! 

---

relates to https://github.com/Homebrew/homebrew-core/pull/87046/ (the latest effort)

**Comment by wonderflow** [comment]
fixed in #2434

**Comment by chenrui333** [comment]
@wonderflow I think #2434 is irrelevant to the issue I raised in here.

**Comment by saltbo** [comment]
https://github.com/Homebrew/homebrew-core/pull/87046

I found this PR, completion setup blocks be removed?  how to implement completion?  @chenrui333
