### ISSUE TITLE
[Feature] Support Vela Querying Language

### ISSUE THREAD

**Issue by leejanee** [oam-dev/kubevela#2448]
**Is your feature request related to a problem? Please describe.**

Kubevela has always  followed the principle of render and deploy, which means that an application corresponds to a set of resources. So it becomes difficult to describe the running state of an application.
 
**Describe the solution you'd like**

1. Kubevela should use `cue-lang` as querying language.
2. Pull Mode.
3. View Definition describes the user's viewing perspective.
4. Data can be obtained by triggering the view through API.
**Describe alternatives you've considered**

For example:

A view named "pods-view" like bellow:
```
import ( "vela/ql" )

parameter: {app: string}

pods: ql.#List & {
   ns: "default"
   labels: ["app=\(parameter.app)"]
   kind: "Pods"
}

statusForDev: [for pod in pods.value {
      name: pod.metadata.name
      ip: pod.status.podIp
      cluster: pod.metadata.labels["cluster"]
      secret: "****"
}]

statusForPlatform: [for pod in pods {
      name: pod.metadata.name
      ip: pod.status.podIp
      node: pod.spec.nodeName
}]

statusWithSecret: [for pod in pods {
      let envs=pod.spec.containers[0].env
      name: pod.metadata.name
      ip: pod.status.podIp
      for env in envs {
        if env.name=="dbSecret"{
          secret: env.value
        }       
      }    
}]
```
 When request api as follows:
```
path: /view/pods-view/statusForDev
method: POST
body: `{"app": "test-app"}`
```
You can get the response as follows:
```
[{name: "pod1",ip: "1.1.1.1",cluster: "env1",secret: "****"}]
```
**Additional context**

**Comment by wonderflow** [comment]
Now we have supported the velaql in apiserver
