### ISSUE TITLE
[Feature] Enable addon in runtime cluster

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela#2562]
**Is your feature request related to a problem? Please describe.**

Vela cli only support install addon in hub cluster currently. I propose that vela should support  install addon in runtime cluster.

**Describe the solution you'd like**

We user enable an addon in runtime cluster, it should output a application with a envbinding policy.

**Describe alternatives you've considered**

**Additional context**

**Comment by hongchaodeng** [comment]
We will implement this this week.
