### ISSUE TITLE
API to show parameters of Addon Observability

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#2609]
@hongchaodeng @chivalryq In order to redirect to or inline Grafana Dashboard of Observability in KubeVela Dashboard, I need an Addon API to show all the parameters of Observability.

Users have to set [several parameters](https://kubevela.io/docs/platform-engineers/system-operation/observability#installing-the-addon) when they enable Addon Observability in a self-built Kubernetes cluster or ACK.

By exposing these parameters, I can:
- indicate where Grafana is installed
If in a self-built k8s cluster, more information will be provided to users on how to enable access to the Grafana dashboard.
- get the domain name of the Grafna dashboard

**Comment by hongchaodeng** [comment]
Addon is another level of abstraction on top. Addon provide parameterization. Just specify the parameters you need in `parameter.cue` and write the templates. See this example.

**Comment by zzxwill** [comment]
@hongchaodeng Thanks. And it's implemented per your design.
