### ISSUE TITLE
[Feature][Dashboard] docker logs for application description

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#263]
Provide logs tailing for docker containers in application description page.
![image](https://user-images.githubusercontent.com/2805315/92907338-ce60bd80-f457-11ea-8eda-e80a3058c336.png)

**Comment by woshilanren11** [comment]
done

**Comment by zzxwill** [comment]
This is a sub-feature of https://github.com/oam-dev/kubevela/issues/740
