### ISSUE TITLE
[Feature] API for `vela comp run`

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#271]
Init and Run workloads

**Comment by mosesyou** [comment]
I will finish it this weekend.

**Comment by mosesyou** [comment]
I see `CreateWorkload` API in the code, this API seems to be done? Or what is the difference from `comp run` and `workload run`

**Comment by zzxwill** [comment]
> I see `CreateWorkload` API in the code, this API seems to be done? Or what is the difference from `comp run` and `workload run`

They are the same. At the very beginning, we call it `workload run`. Thanks.
Implemented by #325 .
