### ISSUE TITLE
Has the name field changed in Env？

### ISSUE THREAD

**Issue by woshilanren11** [oam-dev/kubevela#277]
before:
![image](https://user-images.githubusercontent.com/42092479/93159948-ebd8a480-f741-11ea-9d42-9384d6a76918.png)

now:
![image](https://user-images.githubusercontent.com/42092479/93159815-a1572800-f741-11ea-9180-2f9448a37fd1.png)

**Comment by wenxinnnnn** [comment]
#215 I changed the name of env to envName.
In the latest document, I did not find the problem you mentioned.

**Comment by woshilanren11** [comment]
now，use envName or name?

**Comment by woshilanren11** [comment]
> #215 I changed the name of env to envName.
> In the latest document, I did not find the problem you mentioned.

now，use envName or name?

**Comment by wenxinnnnn** [comment]
> > [＃215](https://github.com/oam-dev/kubevela/pull/215)我将env的名称更改为envName。
> > 在最新文档中，我没有找到您提到的问题。
> 
> 现在，使用envName还是name？

envName

**Comment by woshilanren11** [comment]
> envName

ok

**Comment by wonderflow** [comment]
Sorry I didn't review carefully for that, We should keep compatibility.

**Comment by wonderflow** [comment]
closing as it's fixed , thanks @woshilanren11
