### ISSUE TITLE
[BUG] After setting new env, the application is still created under old env

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#278]
这里还发现的了一个bug。是confirm之前，我去切换的环境，还是创建旧环境的app。

![image](https://user-images.githubusercontent.com/2805315/93172731-00c33100-f75e-11ea-9a89-e69ab34d3737.png)

Reported by @wenxinnnnn

**Comment by wonderflow** [comment]
只要保证这个被破坏的env可以删掉就行，暂时不考虑去把ns创建回来

**Comment by wonderflow** [comment]
vela apiser 可以做一个create后切换
