### ISSUE TITLE
Refine Vela Core Chart

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#2801]
This issue is to collect feedback on current vela-core chart which is too complicated. Let's share the problems you saw on the chart.

**Comment by hongchaodeng** [comment]
1. api+ui 处于同一个deployment.
2. api+ui 默认部署，但可以配置disable。
3. api 默认使用kubeapi数据库
4. 支持部署mongodb 但默认不部署。
5. 支持指定api使用已经存在的mongodb数据库。

**Comment by hongchaodeng** [comment]
在definition方面：
1. 干掉废弃的definition。

**Comment by FogDong** [comment]
1. 已废弃的 definition 增加 label：`custom.definition.oam.dev/deprecated: "true"`
2. 不在 UI 中展示的 definition 增加 label：`custom.definition.oam.dev/ui-hidden: "true"`

Ref: #2664

**Comment by hongchaodeng** [comment]
Update:

We have decided to remove velaux components from Helm chart. Instead, we will put velaux as an addon.
