### ISSUE TITLE
[build] kubevela 1.1.{9,10} build issue

### ISSUE THREAD

**Issue by chenrui333** [oam-dev/kubevela#2812]
👋  while trying to keep the homebrew releases to the latest, I found some build issues with the latest two releases.

**how to reproduce**
1. untar the two source code archives
2. run `make vela-cli VERSION=1.0.9`
3. run into the build issue as below

```
==> make vela-cli VELA_VERSION=1.1.9
  make: docker: Command not found
  Makefile:282: *** recipe commences before first target.  Stop.
```

**related PRs**

relates to https://github.com/Homebrew/homebrew-core/pull/89682

**Comment by wonderflow** [comment]
Seems something went wrong, but I didn't find why the make command invoke the `docker` cli.

https://github.com/oam-dev/kubevela/blob/master/Makefile#L65-L66

It's not rely on it at all.

**Comment by wonderflow** [comment]
I got it, it because we have some pre-check in makefile

**Comment by wonderflow** [comment]
@chenrui333 Thanks for reporting, it's really important and helpful! Much appreciated！

**Comment by chenrui333** [comment]
Thanks for the quick fix!
