### ISSUE TITLE
[BUG] `vela comp status` should get from AppConfig status if no health scope found

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#282]
![image](https://user-images.githubusercontent.com/2173670/93313471-16f2ef00-f83b-11ea-9946-3021dae18497.png)

![image](https://user-images.githubusercontent.com/2173670/93313485-1bb7a300-f83b-11ea-8000-081a0b8fb71d.png)

We can use message from AppConfig.status.conditions

**Comment by captainroy-hy** [comment]
Maybe I can reuse functions in #329 to track component status in each phase including:
- Phase 1: Render and Apply by AppConfig controller
- Phase 2: Reconciled by the corresponding Workload controller
- Phase 3: Health checking after reconciled successfully.

Currently, `vela comp status` only can show status when it gets into phase 2 & phase 3, but cannot handle cases before that (phase 1) just like what you show in the second pic.

**Comment by wonderflow** [comment]
Closing  It was fixed by @captainroy-hy, thanks!
