### ISSUE TITLE
Helm chart test use wrong image tag

### ISSUE THREAD

**Issue by number21** [oam-dev/kubevela#2869]
**Describe the bug**
KubeVela Helm chart test doesn't use correct tag for docker image.

**To Reproduce**
I faced this issue by following this guide - https://kubevela.io/docs/install
Step 2.3 in guide above cause following error:
```
  Normal   Scheduled  23m                  default-scheduler  Successfully assigned vela-system/helm-test-express-server-bff6b68c4-w6b4d to docker-desktop
  Normal   Pulling    21m (x4 over 23m)    kubelet            Pulling image "oamdev/hello-world:v1.1.11"
  Warning  Failed     21m (x4 over 23m)    kubelet            Failed to pull image "oamdev/hello-world:v1.1.11": rpc error: code = Unknown desc = Error response from daemon: manifest for oamdev/hello-world:v1.1.11 not found: manifest unknown: manifest unknown
  Warning  Failed     21m (x4 over 23m)    kubelet            Error: ErrImagePull
  Warning  Failed     20m (x6 over 23m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m6s (x82 over 23m)  kubelet            Back-off pulling image "oamdev/hello-world:v1.1.11"
```

**Expected behavior**

Pod have to be pull **latest** tag, not **v1.1.11**

**Screenshots**

Tag value from tgz I got by this command - `helm pull kubevela/vela-core`
<img width="1422" alt="Screenshot 2021-12-02 at 16 35 54" src="https://user-images.githubusercontent.com/6652590/144447939-1d47d37e-032b-4c9c-abbb-4ba323e0a1dc.png">

**KubeVela Version**

N/A

**Cluster information**

N/A

**Additional context**

Repacked tgz to zip got by run `helm pull kubevela/vela-core`
[vela-core-1.11.11.zip](https://github.com/oam-dev/kubevela/files/7642953/vela-core-1.11.11.zip)

**Comment by wonderflow** [comment]
Thanks for reporting, it's a critical bug that blocks installation.
