### ISSUE TITLE
[Feature] enable to install addon to the managed clusters 

### ISSUE THREAD

**Issue by archever** [oam-dev/kubevela#2912]
**Is your feature request related to a problem? Please describe.**
when I use multicluser env-binding feature with helm component, it failed with "HelmRepository api resource not found". 
it seems to be the fluxcd addon not installing to the managed clusters. 

**Describe the solution you'd like**
there should be a way to installing addon to the managed clusters, like `vela addon enable fluxcd --managed-cluster xxx`

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyikewxgm** [comment]
Have been fixed by #3497 . If you specify any cluster will install on all managedClusters
