### ISSUE TITLE
[Feature] 支持预定义的命名空间，作为apiserver的 Project/Target 命名空间

### ISSUE THREAD

**Issue by ranger-huang** [oam-dev/kubevela#2914]
**Describe the solution you'd like**

因项目需要， 管理应用所在的命名空间是预先定义好的，命名规范、命名空间的个数，不能随便变动的。
为了使用velaux 管理应用，希望 vela-core apisever 支持预定义的命名空间。

kubevela目前的实现 pkg/apiserver/rest/usercase/project.go `projectUsecaseImpl.CreateProject` 
在添加项目时，是固定命名空间的格式（带前缀`project-`）: 

```golang
	new := &model.Project{
		Name:        req.Name,
                 ....
		Namespace:   fmt.Sprintf("project-%s", req.Name),
	}
```

并且在创建 Namespace k8s资源之后，才能录入持久化存储 ( `p.ds.Add(ctx, new)` ) ，所以已有的命名空间也不能被纳入管理

```golang 
	if err := p.kubeClient.Create(ctx, &corev1.Namespace{
		...
	}); err != nil {
		if !apierrors.IsAlreadyExists(err) {
			return nil, err
		}
	}

	if err := p.ds.Add(ctx, new); err != nil {
		return nil, err
	}
```

假设我已有的项目在 `local`，命名空间 `mygroup-qa` 里 已经部署了应用，
在此情况下，vela-core apiserver 不能纳管这里命名空间作为项目，也不能在后添加的addon velaux UI上进行管理。

**Comment by wonderflow** [comment]
这个需求合理，并且KubeVela应该初始化的时候就有一个默认的 project 叫 default （对应default namespace），默认的 target 也是 default namespace 对应 local 集群。

**Comment by wonderflow** [comment]
We shouldn't implement project like below that use a fixed prefix to create the namespace.

```
	new := &model.Project{
		Name:        req.Name,
                 ....
		Namespace:   fmt.Sprintf("project-%s", req.Name),
	}
```

We should allow users to write their own namespace, even existing namespace. And add a lable on it.
