### ISSUE TITLE
[Feature] vela install should wait until the helm install success and all pods started

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#292]
Now, after execute `vela install` , we will install helm chart of vela core, and the command finished very fast.

```
$ vela install
- Installing Vela Core Chart:
- Installing builtin capabilities:
Successful applied 2 kinds of Workloads and Traits: manualscalertraits.core.oam.dev,simplerollouttraits.extend.oam.dev.
syncing workload definitions from cluster...
get 4 workload definition(s) from cluster, syncing...sync 4 workload definition(s) successfully
syncing trait definitions from cluster...
[WARN]handle template metricstraits.standard.oam.dev: extension field is nil
get 3 trait definition(s) from cluster, syncing...sync 3 trait definition(s) successfully
remove 3 legacy capability definition(s) successfully
- Finished.
$ k get pods -n oam-system
NAME                         READY   STATUS              RESTARTS   AGE
vela-core-568cf7b985-rv64g   0/1     ContainerCreating   0          9s
```

Actally, the pods of vela-core could still be creating which means vela-core was not available now, we should wait in `vela install` command until it's Running. Or at least add an argument.

**Comment by captainroy-hy** [comment]
I make an implementation to track OAM-runtime pod's phase in vela, but it takes a long time (more than 2 minutes) to get into "running" phase. The reason is that the `cert-manager-webhook` pod, the prerequisite of oam-runtime pod, takes a long time to set up (average time is more than 2 minutes among 3 experiments).

**Comment by wonderflow** [comment]
@captainroy-hy  If it takes too long, make install command asynchronous is necessary. We could do following things:

1. Add a pre-check before command that need to interact with vela-core. (e.g. `vela comp run`, `vela route`)
2. Add a `--wait` parameter in `vela install`, if this parameter is added, wait until ready.

**Comment by captainroy-hy** [comment]
@wonderflow got it, I will fix it.
