### ISSUE TITLE
when install vela CLI with sh script , failed.

### ISSUE THREAD

**Issue by seedsunrise1** [oam-dev/kubevela#2921]
**Describe the bug**

when install vela CLI with sh script , failed.  because  the latest_release  ，  Regular expression cannot be matched。
**To Reproduce**

**Expected behavior**

**Screenshots**

latest_release is v1.2.0-beta.2  , Regular expression cannot be matched.

<img width="933" alt="1639466360930_50D579F6-A695-4582-9FEB-11F8396F98DD" src="https://user-images.githubusercontent.com/73209573/145952214-f68a2531-9d74-4f73-b908-87128688708e.png">
![image](https://user-images.githubusercontent.com/73209573/145952270-ec16afa3-25e9-4d4b-953a-8b84bec619df.png)

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wangyikewxgm** [comment]
This issue has been fixed by https://github.com/oam-dev/kubevela.io/pull/377 ,but why do you get the old version script
