### ISSUE TITLE
[Feature]velaux does not support create applications with multiple Components

### ISSUE THREAD

**Issue by andy-ruc** [oam-dev/kubevela#2934]
**Is your feature request related to a problem? Please describe.**
Now in vela v1.2.0-beta.2, when I use the velaux dashboard to manage applications, I found that I can only create application with one components. But almost every application we need to delivery has more than 2 components, like rds, redis, or other requirements in the company. We now use the vela-cli to delivery them through one app desc file with all components and traits together
![image](https://user-images.githubusercontent.com/96033892/146137514-a789ffc6-8d73-4f7f-b29d-15668b15eb55.png)

**Describe the solution you'd like**
I hope that one application can be created with several components

**Describe alternatives you've considered**

**Additional context**

**Comment by jefree-cat** [comment]
typical  scenario for the application composed of  micro-services arch.  suggest considering the issue solved align with multi-svc best practices.

**Comment by wonderflow** [comment]
hi @andy-ruc it's supported in https://github.com/oam-dev/kubevela/releases/tag/v1.3.0-beta.2 please have a try
