### ISSUE TITLE
[Feature] Introducing the Application object

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#298]
`Application` is a UI object to generate `Components` and `AppConfig`, it's designed as user facing, simple and could be implemented in either cli side or server side (I prefer the later for now, but open for discussion).

It's schema is of course enforced by CUElang. Actually, if we go to server side impl, I suggest we use CUElang to enforce the schema of Component and AppConfig (Traits) directly so `Application` will be as simple as a generator only!

Note that `Application` is NOT a "standard" Kubernetes object, think about the OAM object in v1alpha1: it should be a minimized version of K8s API schema and 100% developer/operator/devops facing.

Original design: https://github.com/oam-dev/spec/issues/306#issuecomment-583117101, another example is: https://github.com/oam-dev/spec/issues/342

**Comment by hongchaodeng** [comment]
Agree.
I think this could be part of the Appfile definition that I'm working on.
The goal is to have an application definition from developer's perspective.
Another point is that it doesn't have to be Kubernetes object -- it is an API design for developer interaction, mostly taken place in client side.

**Comment by resouer** [comment]
> Agree.
> 
> I think this could be part of the Appfile definition that I'm working on.
> 
> The goal is to have an application definition from developer's perspective.
> 
> Another point is that it doesn't have to be Kubernetes object -- it is an API design for developer interaction, mostly taken place in client side.

My current idea is we have appfile as client side tool but also have equivalent Application object on sever side. This will enable us achieve https://github.com/oam-dev/kubevela/issues/299, and make core feature impl aggregated on server side (easier to be aligned with our internal adoption).

**Comment by hongchaodeng** [comment]
> My current idea is we have appfile as client side tool but also have equivalent Application object on sever side. 

That's what I am thinking as well.
There is always gap from dev framework -> tooling -> backend -> infra. I believe that over time the the API will propagate in the direction from dev  to infra.

**Comment by wonderflow** [comment]
The Application CRD has been implemented
