### ISSUE TITLE
[Feature] Introducing Application level rollout and traffic management

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#299]
For now we have implemented Component level rollout and traffic management.

But after we implemented https://github.com/oam-dev/kubevela/issues/298 in server side, we will have the concept of `Application` and be able to do application level rollout and traffic mgmt - this case is also common in many app platform.

- Original design: https://github.com/oam-dev/spec/issues/342#issue-588587747
- A detailed design and workflow: https://github.com/oam-dev/spec/issues/342#issuecomment-695150546

**Comment by wonderflow** [comment]
This is the application deployment we are working on: https://github.com/oam-dev/kubevela/blob/master/design/vela-core/rollout-design.md

**Comment by wonderflow** [comment]
We have implemented the Rollout https://kubevela.io/docs/rollout/rollout  Traffic Management will be supported in the next release. I'll close this one and write a new issue #1357 .
