### ISSUE TITLE
vela addon enable velaux panic

### ISSUE THREAD

**Issue by zzhzero** [oam-dev/kubevela#3015]
我在自己搭建的gitlab上fork了catalog这个项目
使用这个地址enable velaux panic
![image](https://user-images.githubusercontent.com/26578967/147542542-506ff7c6-cd43-4566-9b87-b3e02f63608a.png)

**Comment by barnettZQG** [comment]
@zzhzero 目前不支持gitlab仓库类型，离线环境我们考虑支持 addon 基于本地目录安装。

/cc @wangyikewxgm  建议先做限制。

**Comment by zzhzero** [comment]
这个限制我后续了解到了，很期待addon支持离线环境。
这个panic应该是代码里在仓库类型为unknown的时候返回err为nil导致的。

**Comment by barnettZQG** [comment]
@zzhzero 欢迎PR来初步解决panic
