### ISSUE TITLE
[Feature] support for more trigger webhook PayloadType

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#3029]
## How a trigger works?

The trigger currently only supports webhook type, which is triggered by an HTTP post request. The custom PayloadType is supported by default:

```
Upgrade  map[string]*model.JSONStruct `json:"upgrade,omitempty"`
CodeInfo *model.CodeInfo              `json:"codeInfo,omitempty"`
```
The `upgrade` defines component properties changes. The `codeInfo` defines code commit info, it can be saved to app revision.

## Support more PayloadType

We usually need to trigger application deployment by changes in the product library. such as:

- [x]  DockerHub Webhook  #3081
- [x]  ACR Trigger #3044 
- [x]  Harbor Webhook #3065 
- [x]  JFrog Webhook

**Comment by K1ngram4** [comment]
We have similar needs recently, maybe I can try to implement part of Harbor Webhook

**Comment by chwetion** [comment]
I can implement dockerhub webhook first

**Comment by wonderflow** [comment]
Harbor merged ： https://github.com/oam-dev/kubevela/pull/3065
