### ISSUE TITLE
applist api 返回的数据有的缺失workload和trait字段

### ISSUE THREAD

**Issue by woshilanren11** [oam-dev/kubevela#304]
![image](https://user-images.githubusercontent.com/42092479/93841507-636c7d80-fcc6-11ea-8646-588c9260c0a7.png)

**Comment by wonderflow** [comment]
traits 确实不一定有，Workload类型一定要有，是个bug. \cc @zzxwill

**Comment by zzxwill** [comment]
Okay, I will look into it.

**Comment by zzxwill** [comment]
The app list changes to a table format which only needs `name`, `status`, `created time`. So workload and trait are not required. Closing this issue. Thanks.
