### ISSUE TITLE
invalid addon repo url makes apiserver crash

### ISSUE THREAD

**Issue by StevenLeiZhang** [oam-dev/kubevela#3042]
**Describe the bug**
invalid addon repo url makes apiserver crash

**To Reproduce**
1. launch VelaUX
2. go to Addons
3. click button "addon registries"
4. click button "new"
5. set "Type" to be GIthub
6. input one invalid URL(means that is not a git repo follows "Addon Format") to "URL" textbox
7. click button "submit"

**Expected behavior**
VelaUx should works as before, but apiserver pod is crashed by null point exception.

```
➜  ~ kubectl -n vela-system logs -f apiserver-7dc97f7558-kqs92
{"level":"info","ts":1641302139.5081124,"caller":"apiserver/main.go:108","msg":"KubeVela information: version: undefined, gitRevision: undefined"}
I0104 13:15:40.315824       1 utils.go:143] find cluster gateway service vela-system/kubevela-cluster-gateway-service:9443
{"level":"info","ts":1641302140.3392406,"caller":"rest/rest_server.go:251","msg":"HTTP APIs are being served on: 0.0.0.0:8000, ctx: context.Background.WithCancel"}
I0104 13:15:40.339524       1 leaderelection.go:248] attempting to acquire leader lease vela-system/apiserver-lock...
I0104 13:15:40.342548       1 rest_server.go:150] new leader elected: f28b817d-f8e7-45a3-b713-dbff80c9f15e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x22b1528]

goroutine 231 [running]:
github.com/oam-dev/kubevela/pkg/addon.(*Registry).ListAddonMeta(0xc00071df20, 0xc000e13330, 0x8, 0xc000e90dc0)
	/workspace/pkg/addon/source.go:212 +0x68
github.com/oam-dev/kubevela/pkg/addon.(*Cache).discoverAndRefreshRegistry(0xc0003c4330)
	/workspace/pkg/addon/cache.go:213 +0x127
github.com/oam-dev/kubevela/pkg/addon.(*Cache).DiscoverAndRefreshLoop(0xc0003c4330, 0x8bb2c97000)
	/workspace/pkg/addon/cache.go:69 +0x6a
created by github.com/oam-dev/kubevela/pkg/apiserver/rest/usecase.NewAddonUsecase
	/workspace/pkg/apiserver/rest/usecase/addon.go:104 +0x1b7
```

**Screenshots**

**KubeVela Version**

v1.2.0-RC2

**Cluster information**

**Additional context**

**Comment by wangyikewxgm** [comment]
@StevenLeiZhang Thanks for your report.This bug has been fixed by #3026 by test. Please check again with the code with master branch or next  1.20 release . Let me close this issue firstly, feel free we can reopen this issue if the bug still exist.

**Comment by StevenLeiZhang** [comment]
> 
I have question about this
`fmt.Errorf("git type repository only support github for now")`
why is Vela only suport github? I want to  use one local private gitlab, this private gitlab also suport github openapi.

**Comment by wonderflow** [comment]
@StevenLeiZhang yes, we're planing to support gitlab, but we only tested github currently. You're very welcome to contribute if the gitlab is tested well. Thanks!
