### ISSUE TITLE
[BUG]configurations.terraform.core.oam.dev crd version is still v1beta1

### ISSUE THREAD

**Issue by songminglong** [oam-dev/kubevela#3056]
**Describe the bug**
I run go test in kubevela/pkg/controller/core.oam.dev/v1alpha2/application, and report error like:
![image](https://user-images.githubusercontent.com/8907867/148504509-607ab2a7-0aa9-4f0a-8530-d7a1229af87b.png)

**To Reproduce**

**Expected behavior**
crd version is v1, not v1beta1

**Screenshots**

**KubeVela Version**
1.2.0-rc

**Cluster information**
k8s 1.22.2

**Additional context**

**Comment by zzxwill** [comment]
@songminglong Thanks for reporting this issue.

I run the tests in Kubernetes 1.22.1 deployed by Kind, but there are no failuers on `v1beta1` issue. In fact, Configuration is in v1 version at the very beginning https://github.com/oam-dev/terraform-controller/blob/master/chart/crds/terraform.core.oam.dev_configurations.yaml#L3.

To help debug this issue, could you please help provide the information below?
- Test command
- Go version
- KubeVela branch
- Kubernetes distribution (ACK? Kind?)

**Comment by zzxwill** [comment]
Please also append the version of `kubebuilder`:)

**Comment by wonderflow** [comment]
Seems you're running tests of kubevela, thanks for reporting.
