### ISSUE TITLE
[Feature] track and show component status changing in `vela init`

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#310]
Enhance feature inspired by #308  @wonderflow 

**Describe the solution you'd like**

When `vela init xxx` occurs, we need to track and show status changing of the component. 

Proposal: 

The overall strategy as below:
![image](https://user-images.githubusercontent.com/5107364/93953588-befe4000-fd86-11ea-8e97-7078a931a3a5.png)

- The initial status is `Pending`
  - if ( k8sClient can get the workload object ) , `Pending` ==> `Creating`
  - if (appConfig reconcile condition is `true` && k8sClient cannot get the workload object ), stay `Pending`
  - if (appConfig reconcile condition is `false` && k8sClient cannot get the workload object ), `Pending` ==>`InitFailed`
    - then output error msg from appConfig condition
- The 2nd normal status is `Creating`
  - if (workload reconcile condition is `false`), `Creating` ==> `CreateFailed`
    - then output error msg from workload condition
  - if (workload status is empty), stady `Creating`
  - if (workload reconcile condition is `true`), `Creating` ==> `HealthChecking`

When status comes into `HealthChecking`, vela should notify users with output:
> Deployed successfully!
> Start checking the health status ...
> Health checking may complete in minutes, you are optional to exit now and check the health status latter.

IMO, `vela init` is responsible for deploying the component while health checking is the next step after the component deployed. So the user can choose to wait for health checking finish **or** just exit the command and check component status latter.

If user doesn't exit the command, vela continues showing status changing as below:
- The 3rd normal status is `HealthChecking`
  - if (HealthScope indicates the workload is `Healthy`), `HealthChecking` ==> `Healthy`
  - if (HealthScope indicates the workload is `Unhealthy` && the age of the workload >= 120s), `HealthChecking` ==> `Unhealthy`
  - if (HealthScope indicates the workload is `Unhealthy` && the age of the workload < 120s), stay `HealthChecking` 
  - if (no HealthScope referenced ||  HealthScope indicates the workload is `Unknown`), `HealthChecking` ==> `Not Diagnosed`
    - output workload condition msg

> 120s means 2 health check cycles, as current default health check interval is 60s. We can use the buffered time to distinguish whether the workload is truly unhealthy or just still under progressing.

**Describe alternatives you've considered**

**Additional

**Comment by captainroy-hy** [comment]
Demo as below:
[gif show click here](https://gifyu.com/image/4DiN)

![image](https://user-images.githubusercontent.com/5107364/94223367-b6df0580-ff2a-11ea-9b76-49406cc7068f.png)

**Comment by wonderflow** [comment]
@captainroy-hy  you should update the oam-k8s-runtime package dependency, then the health scope won't complain `NOT DIAGNOSED` , right?

**Comment by captainroy-hy** [comment]
> @captainroy-hy you should update the oam-k8s-runtime package dependency, then the health scope won't complain `NOT DIAGNOSED` , right?

Yes, that's right. I would update the dependency with latest tag of oam-k8s-runtime.

**Comment by wonderflow** [comment]
fixed by #329
