### ISSUE TITLE
vela CLI installation script not work for arm arch os

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#3130]
**Describe the bug**

The script https://kubevela.io/script/install.sh not work in mac m1 chip.

**To Reproduce**

1. on mac m1 
2. run `curl -fsSl https://kubevela.io/script/install.sh | bash -s 1.2.1`

**Expected behavior**

Install succeed.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

Hope the script can be fixed

**Comment by Somefive** [comment]
Fixed in https://github.com/oam-dev/kubevela.io/pull/457.
