### ISSUE TITLE
When a local addon's path is not right, the error message does not correctly indicate the issue

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#3183]
**Describe the bug**

When a local addon's path is not right, the error message does not correctly indicate the issue

```
➜  catalog git:(generate-terraform-addon) ✗ vela addon enable ./sfsfjsdlfjsdlfjsdlfjsd
Error: addon: ./sfsfjsdlfjsdlfjsdlfjsd not found in registries
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
yes, it should point out the directory not found, e.g.:

```
Error: addon directory ./sfsfjsdlfjsdlfjsdlfjsd not found 
```

**Comment by JooKS-me** [comment]
Hi, I think we should be clear about this question:
`./sfsfjsdlfjsdlfjsdlfjsd` is a path, but `sfsfjsdlfjsdlfjsdlfjsd` is a local path or not?

If the latter cannot be a local path, we only need to additionally check whether the `/` symbol is included.

However, if `sfsfjsdlfjsdlfjsdlfjsd` may be a local path or `./sfsfjsdlfjsdlfjsdlfjsd` is an addon in the repository, I think we should add a parameter to let the user mark whether it is a local path or not.

for example:
````
vela addon enable xxxxxx #only finding in repository
vela addon enable xxxxxx -lc (--local) #only finding in local path
````

**Comment by wonderflow** [comment]
We follow the helm ux, so we should not add more flags here. We can simply regard `sfsfjsdlfjsdlfjsdlfjsd` as an addon in registry, only `./sfsfjsdlfjsdlfjsdlfjsd` or `sfsfjsdlfjsdlfjsdlfjsd/` is a local chart.

**Comment by JooKS-me** [comment]
> We follow the helm ux, so we should not add more flags here. We can simply regard `sfsfjsdlfjsdlfjsdlfjsd` as an addon in registry, only `./sfsfjsdlfjsdlfjsdlfjsd` or `sfsfjsdlfjsdlfjsdlfjsd/` is a local chart.

Got it! Can I try to fix this issue?
