### ISSUE TITLE
Observability addon install failed

### ISSUE THREAD

**Issue by JooKS-me** [oam-dev/kubevela#3188]
**Describe the bug**

Observability addon install failed.

It say: Fetch repository successfully, Delivery helm release in progress, message: install retries exhausted, Helm install failed: timed out waiting for the condition Last Helm logs: creating 15 resource(s) beginning wait for 15 resources with timeout of 10m0s Service does not have load balancer ingress IP address: vela-system/grafana

- helm list -n vela-system
```
NAME                          	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                     	APP VERSION
grafana                       	vela-system	1       	2022-02-05 08:35:54.010193888 +0000 UTC	failed  	grafana-6.14.1            	8.0.5
grafana-registration          	vela-system	1       	2022-02-05 04:59:00.383012921 +0000 UTC	deployed	grafana-registration-0.0.7	0.0.6
loki                          	vela-system	1       	2022-02-05 08:29:04.143591336 +0000 UTC	deployed	loki-stack-2.4.1          	v2.1.0
vela-system-kube-state-metrics	vela-system	1       	2022-02-05 08:32:29.775759376 +0000 UTC	deployed	kube-state-metrics-3.4.1  	2.1.0
```

- kubectl get pod -n vela-system
```
NAME                                              READY   STATUS    RESTARTS   AGE
grafana-844464d494-76hfw                          1/1     Running   0          21m
grafana-configuration-68845b6bdb-xrmkb            1/1     Running   0          5h2m
loki-0                                            1/1     Running   0          28m
loki-promtail-75lt7                               1/1     Running   0          28m
vela-system-kube-state-metrics-688454d44f-ndgjp   1/1     Running   0          25m
```

- kubectl get svc -n vela-system

```
NAME                             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
grafana                          LoadBalancer   10.96.136.166   <pending>     80:31269/TCP   23m
loki                             ClusterIP      10.96.12.158    <none>        3100/TCP       29m
loki-headless                    ClusterIP      None            <none>        3100/TCP       29m
vela-system-kube-state-metrics   ClusterIP      10.96.97.58     <none>        8080/TCP       26m
```

**To Reproduce**

refer to https://kubevela.io/docs/install .

1. Install k8s cluster with kind.
2. Install ingress controller to enable service route
3. Install KubeVela Core
4. Install KubeVela CLI
5. Install VelaUX
6. enable addon `fluxcd`
7. enable addon `observability-assets`
8. enable addon `observability`  (can't)

**Expected behavior**

enable addon `observability`

**Screenshots**

![image](https://user-images.githubusercontent.com/62384022/152632934-a2333979-6b58-46fb-b698-f3e3276edc68.png)
![image](https://user-images.githubusercontent.com/62384022/152632773-90f9e077-7340-4816-8b96-7bcf91a78d02.png)

**KubeVela Version**

both `1.2.2` and `latest in master`

**Cluster information**

Kubernetes Version 1.21.2

**Additional context**

**Comment by JooKS-me** [comment]
I found the reseaon :)
Because I running on kind cluster, and it's not support `LoadBalancer` type service, and in the addon repo, it's the fixed LoadBalancer (https://github.com/oam-dev/catalog/blob/8dc0f1c9392cc4720b04362f8798286ffeec6388/experimental/addons/observability/resources/grafana.cue#L13) .
And then I modify `LoadBalancer` to `ClusterIP`, it became successful~

Thus, should we make the type of service configurable for user?

**Comment by wonderflow** [comment]
Yes, in fact the default type should be `ClusterIP`
