### ISSUE TITLE
New Traits UI problem 

### ISSUE THREAD

**Issue by workman-Lu** [oam-dev/kubevela#3203]
**Describe the bug**

there was a UI Problem when i New the Traits. 

**To Reproduce**

http://$url/applications/$project/config

**Screenshots**

![image](https://user-images.githubusercontent.com/23043492/152952092-415e3760-67f1-4dc1-93b7-0f594a6b6c81.png)

**KubeVela Version**
kubevela v1.2.2

**Cluster information**

K8S v1.21.0

**Additional context**

applications->baseconfig->properties->new Traits

**Comment by barnettZQG** [comment]
The issues about the velaux move to https://github.com/oam-dev/velaux/issues/346
