### ISSUE TITLE
[Question] Failed to execute "vela init"

### ISSUE THREAD

**Issue by Glacier759** [oam-dev/kubevela#323]
**$ vela init**
Welcome to use KubeVela CLI! We're going to help you run applications through a couple of questions.

Environment: default, namespace: default

? Do you want to setup a domain for web service:  aliyun.com
? Provide an email for production certification:  test@aliyun.com
Error: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: dial tcp 10.105.226.2:443: connect: connection refused

**$ kubectl -n oam-system get pods**
NAME                        READY   STATUS              RESTARTS   AGE
vela-core-b599c5f99-bdpks   0/1     ContainerCreating   0          63m

**$ kubectl -n oam-system get events**
LAST SEEN   TYPE      REASON        OBJECT                          MESSAGE
54s         Warning   FailedMount   pod/vela-core-b599c5f99-bdpks   MountVolume.SetUp failed for volume "tls-cert-vol" : secret "webhook-server-cert" not found
29m         Warning   FailedMount   pod/vela-core-b599c5f99-bdpks   Unable to attach or mount volumes: unmounted volumes=[tls-cert-vol], unattached volumes=[tls-cert-vol vela-core-token-dmpj2]: timed out waiting for the condition
20m         Warning   FailedMount   pod/vela-core-b599c5f99-bdpks   Unable to attach or mount volumes: unmounted volumes=[tls-cert-vol], unattached volumes=[vela-core-token-dmpj2 tls-cert-vol]: timed out waiting for the condition

**Comment by wonderflow** [comment]
It seems vela-core haven't installed successfully yet, I think it's duplicated with #292

**Comment by wonderflow** [comment]
We have added the feature 'to wait until the vela-core is successfully running'.

So just use `vela install --wait` to install the vela core. Then you'll be able to fix this problem.

I'll close this PR, feel free to reopen if you still have problems.
