### ISSUE TITLE
Helm charts missing README.md

### ISSUE THREAD

**Issue by nashtsai** [oam-dev/kubevela#3253]
**Describe the bug**
Helm charts (charts/vela-core & charts/oam-runtime) missing README.md file, however, the released package seems to include github repo's README.md, there is an underlying problem that repo's README.md is using local referenced contents (check below) which caused display problem when showing chart's README

```
![](docs/resources/what-is-kubevela.png)
 [CONTRIBUTING](./CONTRIBUTING.md)
```

**Comment by wonderflow** [comment]
fixed by https://github.com/oam-dev/kubevela/pull/3331
