### ISSUE TITLE
[BUG] Helm install doesn't support namespace other than vela-system

### ISSUE THREAD

**Issue by nashtsai** [oam-dev/kubevela#3263]
**Describe the bug**
Helm install doesn't support namespace other than vela-system. It's observed following hardcoded `vela-system` value:

- under `/templates/`, `namespace: vala-system`
- `crds/core.oam.dev_applications.yaml`  file's elements: `.spec.conversion.webhook.clientConfig.service.namespace` and `.metadata.annotations.cert-manager.io/inject-ca-from` 

**Expected behavior**
Chart able to install to specified namespace.

**KubeVela Version**

v1.2.3

**Cluster information**
1.20.4

**Additional context**
I've hacked through with replaced hardcoded value with `{{ .Release.Namespace }}`  and removed `crds/core.oam.dev_applications.yaml` file's `.spec.conversion.webhook.clientConfig.service.namespace`  and `.metadata.annotations.cert-manager.io/inject-ca-from`  element, got following job failed:

```
# kubectl -n artifacthub-io-vela-core-1-2-4-beta-1-2-control-plane get job.batch/vela-core-vela-core-admission-patch
NAME                                  COMPLETIONS   DURATION   AGE
vela-core-vela-core-admission-patch   0/1           25m        25m

#kubectl -n artifacthub-io-vela-core-1-2-4-beta-1-2-control-plane logs pod/vela-core-vela-core-admission-patch-hw6fx
W0215 14:08:35.688677       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0215 14:08:36.742460       1 request.go:668] Waited for 1.038838608s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/storage.yoda.io/v1beta1?timeout=32s
{"level":"info","msg":"config= %#v {info json vela-core-vela-core-admission artifacthub-io-vela-core-1-2-4-beta-1-2-control-plane cert key  vela-core-vela-core-admission true true Fail  [applications.core.oam.dev]}","source":"cmd/patch.go:48","time":"2022-02-15T14:08:39Z"}
{"level":"info","msg":"patching webhook configurations 'vela-core-vela-core-admission' mutating=true, validating=true, failurePolicy=Fail","source":"k8s/k8s.go:61","time":"2022-02-15T14:08:39Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x177723a]

goroutine 1 [running]:
github.com/jet/kube-webhook-certgen/pkg/k8s.(*k8s).PatchWebhookConfigurations(0xc000426400, 0x7fff2447c9fd, 0x1d, 0xc000016000, 0x236, 0x237, 0x28fb590, 0x101, 0x7fff2447ca27, 0x35, ...)
        /workspace/pkg/k8s/k8s.go:124 +0x95a
github.com/jet/kube-webhook-certgen/cmd.patchCommand(0x28f3000, 0xc00043d0e0, 0x0, 0x5)
        /workspace/cmd/patch.go:49 +0x1f6
github.com/spf13/cobra.(*Command).execute(0x28f3000, 0xc00043d090, 0x5, 0x5, 0x28f3000, 0xc00043d090)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x28f3280, 0x41ac01, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/jet/kube-webhook-certgen/cmd.Execute()
        /workspace/cmd/root.go:43 +0x2d
main.main()
        /workspace/main.go:8 +0x25
```

**Comment by wonderflow** [comment]
I have tested and succeed, please try following lines:

```
kubectl create ns your-vela-ns
helm install -n your-vela-ns kubevela kubevela/vela-core --version 1.2.3 --set multicluster.enabled=true --set systemDefinitionNamespace=your-vela-ns --wait
```

**Comment by nashtsai** [comment]
> I have tested and succeed, please try following lines:
> 
> ```
> kubectl create ns your-vela-ns
> helm install -n your-vela-ns kubevela kubevela/vela-core --version 1.2.3 --set multicluster.enabled=true --set systemDefinitionNamespace=your-vela-ns --wait
> ```

I've done another test, as keeping `crds/core.oam.dev_applications.yaml` file's `.spec.conversion` and `.metadata.annotations.cert-manager.io/inject-ca-from` elements and Helm installation were completed, and these 2 elements got overwritten correctly with correct NS name. Since these context will be patched, I would suggest removal of `.spec.conversion` and `.metadata.annotations.cert-manager.io/inject-ca-from` elements as current contents may misleading.

**Comment by nashtsai** [comment]
> I have tested and succeed, please try following lines:
> 
> ```
> kubectl create ns your-vela-ns
> helm install -n your-vela-ns kubevela kubevela/vela-core --version 1.2.3 --set multicluster.enabled=true --set systemDefinitionNamespace=your-vela-ns --wait
> ```

I've done another test, as keeping `crds/core.oam.dev_applications.yaml` file's `.spec.conversion` and `.metadata.annotations.cert-manager.io/inject-ca-from` elements and Helm installation were completed, and these 2 elements got overwritten correctly with correct NS name. Since these context will be correct context will be patched, I would suggest removal of `.spec.conversion` and `.metadata.annotations.cert-manager.io/inject-ca-from` elements as context may misleading

**Comment by wonderflow** [comment]
> I would suggest removal of .spec.conversion and .metadata.annotations.cert-manager.io/inject-ca-from elements as context may misleading

Yes, it's a good idea. 

The project related is here: https://github.com/oam-dev/kube-webhook-certgen/blob/master/pkg/k8s/k8s.go#L124-L126

We should automatically inject values if these lines are empty.

**Comment by wangyikewxgm** [comment]
@nashtsai  I have tested with KubeVela 1.2.4 helm chart and cannot regenerate this error. Let's closed this issue and fell free reopen if this bug still exist.
