### ISSUE TITLE
You need to enable JavaScript to run the velaux.

### ISSUE THREAD

**Issue by laotoutou** [oam-dev/kubevela#3264]
`vela addon enable velaux serviceType=NodePort repo=acr.kubevela.net`

and server return 
> You need to enable JavaScript to run the velaux.

so what happen?

**Comment by barnettZQG** [comment]
@laotoutou Are you disabled JavaScript in your brower?

**Comment by laotoutou** [comment]
> @laotoutou Are you disabled JavaScript in your browser?

No, Javascript is enabled.

**Comment by barnettZQG** [comment]
@laotoutou What is your browser type and version?

**Comment by laotoutou** [comment]
> @laotoutou What is your browser type and version?

I stop firewalld （systemctl stop firewalld）on centos7，and then is ok.

**Comment by laotoutou** [comment]
> @laotoutou What is your browser type and version?

thank you~
