### ISSUE TITLE
[Bug] The order of status displayed by vela ls is not correct

### ISSUE THREAD

**Issue by FogDong** [oam-dev/kubevela#3279]
**Describe the bug**

 The order of status displayed by vela ls is not correct.

**To Reproduce**

Have one application with more than three components.

Use vela ls:
```bash
$ vela ls
APP           	COMPONENT    	TYPE            	TRAITS	PHASE  	HEALTHY	STATUS       	CREATED-TIME
simple-example	demo-training	training        	      	running	healthy	Available    	2022-02-17 11:48:11 +0800 CST
├─          	jupyter      	jupyter-notebook	      	running	healthy	Job Succeeded	2022-02-17 11:48:11 +0800 CST
└─          	demo-serving 	serving         	      	running	healthy	             	2022-02-17 11:48:11 +0800 CST
```

It shows that the status of demo-training is `Available`, and jupyter is `Job Succeeded`.

Use vela status to show detatils:

```
$ vela status simple-example

About:

  Name:      	simple-example
  Namespace: 	default
  Created at:	2022-02-17 11:48:11 +0800 CST
  Status:    	running

Workflow:

  mode: DAG
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id:j6gf43ybu2
    name:demo-training
    type:apply-component
    phase:succeeded
    message:
  - id:8hic6pv1zw
    name:jupyter
    type:apply-component
    phase:succeeded
    message:
  - id:8g7gymrcfe
    name:demo-serving
    type:apply-component
    phase:succeeded
    message:

Services:

  - Name: demo-serving  Env: Control plane cluster
    Type: serving
    healthy Available
    Traits:

  - Name: demo-training  Env: Control plane cluster
    Type: training
    healthy Job Succeeded
    Traits:

  - Name: jupyter  Env: Control plane cluster
    Type: jupyter-notebook
    healthy
    Traits:
```

It shows that the status of serving is`Available`, and the training is `Job Succeeded`.

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by mayankkumar2** [comment]
@FogDong what is the expected order? Is it Job Succeded > Available?

**Comment by FogDong** [comment]
> @FogDong what is the expected order? Is it Job Succeded > Available?

The expected order is:

```
$ vela ls
APP           	COMPONENT    	TYPE            	TRAITS	PHASE  	HEALTHY	STATUS       	CREATED-TIME
simple-example	demo-training	training        	      	running	healthy	Job Succeeded    	2022-02-17 11:48:11 +0800 CST
├─          	jupyter      	jupyter-notebook	      	running	healthy		2022-02-17 11:48:11 +0800 CST
└─          	demo-serving 	serving         	      	running	healthy	   Available          	2022-02-17 11:48:11 +0800 CST
```

In my definition, the jupyter does not have custom status, and the training's status is `Job Succeeded`, the serving's status is `Available`.

**Comment by StevenLeiZhang** [comment]
> > @FogDong what is the expected order? Is it Job Succeded > Available?
> 
> The expected order is:
> 
> ```
> $ vela ls
> APP           	COMPONENT    	TYPE            	TRAITS	PHASE  	HEALTHY	STATUS       	CREATED-TIME
> simple-example	demo-training	training        	      	running	healthy	Job Succeeded    	2022-02-17 11:48:11 +0800 CST
> ├─          	jupyter      	jupyter-notebook	      	running	healthy		2022-02-17 11:48:11 +0800 CST
> └─          	demo-serving 	serving         	      	running	healthy	   Available          	2022-02-17 11:48:11 +0800 CST
> ```
> 
> In my definition, the jupyter does not have custom status, and the training's status is `Job Succeeded`, the serving's status is `Available`.

Hi @FogDong  , I tried to investigate and fix this. Please review my PR.
