### ISSUE TITLE
Get fail when kube-vela of latest as dependency of project in gomod

### ISSUE THREAD

**Issue by lengpucheng** [oam-dev/kubevela#3334]
### Discussed in https://github.com/oam-dev/kubevela/discussions/3333

<div type='discussions-op-text'>

<sup>Originally posted by **lengpucheng** February 28, 2022</sup>
when latest (such as v1.2.4) as dependency in project ,  use go download get  all dependency of project can fail ，the info is :
````
go get: github.com/oam-dev/kubevela@v1.1.8 updating to
        github.com/oam-dev/kubevela@v1.2.4 requires
        sigs.k8s.io/apiserver-network-proxy@v0.0.24 requires
        sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.0.0: reading
http://my-goproxy-website/sigs.k8s.io/apiserver-network-proxy/konnectivi
ty-client/@v/v0.0.0.mod: 404 Not Found
````
we try different machine and network still fail,but get old version is succes
![2](https://user-images.githubusercontent.com/56445668/155890939-5ed7e161-e4b2-4ab0-96ad-605363890bb0.png)

i need help! thanks !

</div>

**Comment by StevenLeiZhang** [comment]
Would you please try another "goproxy"? Please refer to the document https://goproxy.cn/,  this webpage shows the usage. It works well for me .

**Comment by lengpucheng** [comment]
> 你能试试另一个"goproxy"吗？请参阅文档 https://goproxy.cn/，此网页显示了用法。它对我很好。

We have tried, currently we are using goproxy to proxy the local private repository and another remote proxy at the same time, the original proxy cannot get the dependency using gorpoxy.cn and goproxy.io or aliyun

**Comment by wonderflow** [comment]
What's your scenario? Maybe, you can try using this repo as dependency https://github.com/oam-dev/kubevela-core-api

**Comment by lengpucheng** [comment]
> What's your scenario? Maybe, you can try using this repo as dependency https://github.com/oam-dev/kubevela-core-api

thanks! we add mod replace of kubevela or use kubevela-core-api to solve

**Comment by yangsoon** [comment]
If you want to use kubevela as a third-party package, you need to view the go.mod file in the kubevela project and copy the `replace` part to the `replace` of your project.

plz, refer to https://go.dev/ref/mod#go-mod-file-replace :

> replace directives only apply in the main module’s go.mod file and are ignored in other modules.

```
replace (
	github.com/docker/cli => github.com/docker/cli v20.10.9+incompatible
	github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
	github.com/wercker/stern => github.com/oam-dev/stern v1.13.2
	sigs.k8s.io/apiserver-network-proxy/konnectivity-client => sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.0.24
)
```

Then re-executing `go mod download` will solve your problem. 

However, we recommend directly referencing https://github.com/oam-dev/kubevela-core-api to use kubevela's api
