### ISSUE TITLE
[Feature] Extend UCloud as a Terraform addon

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#3336]
UCloud has been supported as a Provider in [Terraform Controller](https://github.com/oam-dev/terraform-controller), please convert it to a Terraform addon `terraform-ucloud` in KubeVela per [the guide](https://kubevela.io/docs/platform-engineers/addon/terraform).

**Comment by wonderflow** [comment]
supported in https://github.com/oam-dev/catalog/pull/285
