### ISSUE TITLE
trait list 中appliesTo字段是必须的吗，接口返回的可能有可能无

### ISSUE THREAD

**Issue by woshilanren11** [oam-dev/kubevela#334]
![image](https://user-images.githubusercontent.com/42092479/94382009-b5514f80-016d-11eb-8a34-ee366a931eb0.png)

**Comment by wonderflow** [comment]
嗯，这个字段是可能有，可能无，一般情况下都是有的。

**Comment by woshilanren11** [comment]
> 嗯，这个字段是可能有，可能无，一般情况下都是有的。

嗯嗯，无的话是说，该trait没有可追加的workload type,还是该trait可追加给任意的workload type呢

**Comment by wonderflow** [comment]
@woshilanren11  无的话咱们暂时认为是没有可追加的Workload（实际上应该是写Definition的人漏写了），还有一种是 `*` ，这种是可追加到任意Workload

**Comment by woshilanren11** [comment]
> @woshilanren11 无的话咱们暂时认为是没有可追加的Workload（实际上应该是写Definition的人漏写了），还有一种是 `*` ，这种是可追加到任意Workload

好的
