### ISSUE TITLE
Component creation failed without custom resources

### ISSUE THREAD

**Issue by wxuedong** [oam-dev/kubevela#3342]
version:
Version: 1.1.6
GitRevision: git-844f479f
GolangVersion: go1.17.2

yaml:
```
stateless: {
    annotations: {}
    attributes: workload: definition: {
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
    }
    description: ""
    labels: {}
    type: "component"
}

template: {
    output: {
        spec: {
            selector: matchLabels: "app.oam.dev/component": "name"
            template: {
                metadata: labels: "app.oam.dev/component": "name"
                spec: containers: [{
                    name:  "name"
                    image: "image"
                }]
            }
        }
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
    }
    outputs: {}
    parameters: {}
}
``` 

error message:

Error: failed to update existing definition in kubernetes: admission webhook "mutating.core.oam-dev.v1beta1.componentdefinitions" denied the request: no matches for kind "Rollout" in version "argoproj.io/v1alpha1"

This resource is not customized in the management cluster ，but the target cluster is defined  

I think the component can be created normally in this case

**Comment by chivalryq** [comment]
Just a reminder, it's three "`" in markdown to wrap a long code.

You can edit the issue for a better looking.

**Comment by chivalryq** [comment]
If one CRD doesn't exist in managed cluster, the CR creation (by vela-core) will fail.

Consider turn ArgoRollout as an addon whose CRD can be dispatched in managed cluster then.

ping @wangyikewxgm

**Comment by wxuedong** [comment]
This CR may be submitted to the target cluster. 

As long as the target cluster has it, there is no problem. 

In this case, it is normal for the control cluster to have no CR, and it should not fail.

**Comment by wxuedong** [comment]
> If one CRD doesn't exist in managed cluster, the corresponding CR creation (by vela-core) will fail.
> 
> Consider turn ArgoRollout as an addon whose CRD can be dispatched in managed cluster then. That's what we done with fluxcd.
> 
> Or you can simply install Argo rollout in managedCluster.
> 
> ping @wangyikewxgm

This CR may be submitted to the target cluster.

As long as the target cluster has it, there is no problem.

In this case, it is normal for the control cluster to have no CR, and it should not fail.

**Comment by chivalryq** [comment]
Got you. You won't use Argo in Control plane and didn't install it.

That's a case we didn't consider before. Thanks for reporting. You can track this issue for more progress.

**Comment by chivalryq** [comment]
There's a workaround for this case. You can use this defintion instead.

```cue
stateless: {
    annotations: {}
        attributes: workload: type: "autodetects.core.oam.dev"
    description: ""
    labels: {}
    type: "component"
}

template: {
    output: {
        spec: {
            selector: matchLabels: "app.oam.dev/component": "name"
            template: {
                metadata: labels: "app.oam.dev/component": "name"
                spec: containers: [{
                    name:  "name"
                    image: "image"
                }]
            }
        }
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
    }
    outputs: {}
    parameters: {}
}
```

The difference is use "autodetects.core.oam.dev" in the workload field. Now this field is only for validate and this will work for most case.

**Comment by wxuedong** [comment]
> Let me know if this works for you.

This can be solved  .   

If you define a lot of components, there will be a lot of "autodetects.core.oam.dev" , which cannot intuitively reflect the workload.
