### ISSUE TITLE
can't install VelaUX

### ISSUE THREAD

**Issue by wcollin** [oam-dev/kubevela#3347]
**Describe the bug**
when install VelaUX， waiting for addon-velaux application ready

**To Reproduce**
1. vela install
2. vela addon enable velaux serviceType=NodePort repo=acr.kubevela.net
3. kubectl describe applications addon-velaux -n vela-system
4. see status error：failed to create resourceKeeper: failed to load resourcetrackers: resourcetracker addon-velaux-comp-rev-vela-system exists but controlled by another application (uid: f02a02c6-10a7-425d-8ac5-fce9da0fbcb9), this could probably be cased by some mistakes while garbage collecting outdated resource. Please check this resourcetrakcer and delete it manually

**Screenshots**
<img width="1257" alt="33cfdd98ac70318e13115d9f60108fa" src="https://user-images.githubusercontent.com/17266901/156289801-18530113-9666-4880-995c-3834ebc7ec1a.png">

**KubeVela Version**
vela version：1.2.4

**Cluster information**
kubernetes 1.22.5

**Comment by chivalryq** [comment]
This may not have to do with 1.22 compatibility. I have try launch vela-core and velaUX addon in my 1.22 Kubernetes and it works fine.

```shell
$ vela addon enable velaux
I0302 12:01:37.749016   81400 apply.go:107] "creating object" name="addon-velaux" resource="core.oam.dev/v1beta1, Kind=Application"
Addon: velaux enabled Successfully.
Please use command: "vela port-forward -n vela-system addon-velaux 9082:80" and Select "Cluster: local | Namespace: vela-system | Component: velaux | Kind: Service" to check the dashboard.
```

**Comment by chivalryq** [comment]
After talking offline, we figure out the reason caused break. Cleaning up the left ResourceTracker it works fine.
Closing
