### ISSUE TITLE
trait api 接口返回500错误问题

### ISSUE THREAD

**Issue by woshilanren11** [oam-dev/kubevela#336]
delete删除的时候：
url: http://30.11.171.39:8000/api/envs/default/apps/test33/components/testcom33/traits/scale
post追加时：
url: http://30.11.171.39:8000/api/envs/default/apps/test33/components/testcom33/traits/
body：
{
"name": "metrics",
"flags": [
{
"name": "path",
"value": "/metrics"
},
{
"name": "format",
"value": "prometheus"
},
{
"name": "scheme",
"value": "http"
},
{
"name": "enabled",
"value": "true"
},
{
"name": "port",
"value": "8080"
}
]
}

错误信息：
![image](https://user-images.githubusercontent.com/42092479/94398680-961be780-0198-11eb-8a40-b0c559d93fde.png)

创建workload同时含有trait时报错，post请求
url: http://30.11.171.39:8000/api/workloads/
body:
{"envName":"default","workloadType":"backend","workloadName":"testcom61","flags":[{"name":"image","value":"26"},{"name":"name","value":"testcom61"}],"appName":"test66","traits":[{"name":"route","envName":"default","workloadName":"testcom61","appName":"test66","flags":[{"name":"path","value":"/33"},{"name":"domain","value":"11"},{"name":"issuer","value":"22"},{"name":"port","value":"443"}]}]}
错误信息：
![image](https://user-images.githubusercontent.com/42092479/94399804-9e752200-019a-11eb-902b-cd40a7ee30ce.png)

**Comment by wonderflow** [comment]
ping @zzxwill  please help check and fix, thanks

**Comment by zzxwill** [comment]
Fixed in #343
