### ISSUE TITLE
upgrade velaux1.2.4 has a little issue

### ISSUE THREAD

**Issue by zhulaoliu** [oam-dev/kubevela#3371]
![image](https://user-images.githubusercontent.com/54096513/156723324-095d5b97-b5b4-4044-99cd-b3e89cbdf0d9.png)
![image](https://user-images.githubusercontent.com/54096513/156723370-125fdc23-de56-44c8-af90-c468bedb5780.png)
![image](https://user-images.githubusercontent.com/54096513/156723369-29db4549-395d-426e-84d0-89c94eed6817.png)
我想将原本的运维特征“scaler“ 修改成“rollout”  但貌似报错了 提示trait is not exit
随后我选择新建一个运维特征“rollout”    并将原本的scaler删除   就不报错了
下面是我的trait definition
rollout -n vela-system
Name:         rollout
Namespace:    vela-system
Labels:       app.kubernetes.io/managed-by=Helm
              oam.dev/render-hash=fb75ee1a09143229
Annotations:  definition.oam.dev/description: Rollout the component.
              meta.helm.sh/release-name: kubevela
              meta.helm.sh/release-namespace: vela-system
API Version:  core.oam.dev/v1beta1
Kind:         TraitDefinition
Metadata:
  Creation Timestamp:  2022-01-24T09:27:42Z
  Generation:          3
  Managed Fields:
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:definition.oam.dev/description:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:manageWorkload:
        f:schematic:
          .:
          f:cue:
        f:status:
          .:
          f:customStatus:
          f:healthPolicy:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2022-03-02T10:12:47Z
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:oam.dev/render-hash:
        f:ownerReferences:
          .:
          k:{"uid":"09b18c3c-ac3d-4114-8694-20522485d256"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        f:schematic:
          f:cue:
            f:template:
    Manager:      apiserver
    Operation:    Update
    Time:         2022-03-03T10:16:47Z
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:definitionRef:
          .:
          f:name:
      f:status:
        .:
        f:configMapRef:
        f:latestRevision:
          .:
          f:name:
          f:revision:
          f:revisionHash:
    Manager:    kubevela
    Operation:  Update
    Time:       2022-03-03T10:16:47Z
  Owner References:
    API Version:           core.oam.dev/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Application
    Name:                  addon-rollout
    UID:                   09b18c3c-ac3d-4114-8694-20522485d256
  Resource Version:        17811111
  Self Link:               /apis/core.oam.dev/v1beta1/namespaces/vela-system/traitdefinitions/rollout
  UID:                     42587c3a-9649-46b2-a5be-25e78fb96ca3
Spec:
  Manage Workload:  true
  Schematic:
    Cue:
      Template:  outputs: rollout: {
                 apiVersion: "standard.oam.dev/v1alpha1"
                 kind:       "Rollout"
                 metadata: {
                   name:      context.name
                   namespace: context.namespace
                 }
                 spec: {
                   if parameter.targetRevision != _|_ {
                     targetRevisionName: parameter.targetRevision
                   }
                   if parameter.targetRevision == _|_ {
                     targetRevisionName: context.revision
                   }
                   componentName: context.name
                   rolloutPlan: {
                     rolloutStrategy: "IncreaseFirst"
                     if parameter.rolloutBatches != _|_ {
                       rolloutBatches: parameter.rolloutBatches
                     }
                     targetSize: parameter.targetSize
                     if parameter["batchPartition"] != _|_ {
                       batchPartition: parameter.batchPartition
                     }
                   }
                 }
}
parameter: {
  // +usage=Specify the target revision, it should be set if you want to rollback. such as: componentname-v1
  targetRevision?: string
  // +usage=Specify the count of replicas.
  targetSize: int
  // +usage=Specify the rollout batches, The total number of replicas of all batches needs to be equal to number of targetSize.
  rolloutBatches?: [...rolloutBatch]
  // +usage=Specify the batch partition in current deploying. It is used to control batch processes.
  batchPartition?: int
}
rolloutBatch: replicas: int

  Status:
    Custom Status:  message: context.outputs.rollout.status.rollingState
    Health Policy:  isHealth: context.outputs.rollout.status.batchRollingState == "batchReady"
Status:
  Config Map Ref:  trait-schema-rollout
  Latest Revision:
    Name:           rollout-v3
    Revision:       3
    Revision Hash:  d6658670d89d0cb3
Events:             <none>

**Comment by zhulaoliu** [comment]
![image](https://user-images.githubusercontent.com/54096513/156724685-2a878c43-989b-418a-91a1-f3e13bae7749.png)
 随后我尝试了灰度升级（点击了deploy） 但版本没有看到变化  是我的操作方式不对？
![image](https://user-images.githubusercontent.com/54096513/156724886-6a0cc81e-815f-4cf7-bd10-61bc9649fa78.png)

**Comment by barnettZQG** [comment]
@zhulaoliu 

1. trait 的类型不能进行变更，UI上没有限制是一个缺陷，该缺陷会在最新版本中修复。
2. 设置 Rollout 以后，需要组件的配置有变更才会产生新的版本号。

**Comment by zhulaoliu** [comment]
恩恩  目前灰度升级的问题我还没想明白 是我的操作方式不对吗

**Comment by barnettZQG** [comment]
@zhulaoliu 

你可以尝试比如修改一下镜像名称、环境变量等，然后再进行一次部署。就会发现实例名称上的版本号有变化。另外就是控制灰度的批次。Rollout 配置参数中可设置多个批次，然后可以指定 BatchPartition 控制发布的目标批次。 比如设置为0 则代表发完第一批即停止。

**Comment by zhulaoliu** [comment]
@[barnettZQG](https://github.com/barnettZQG)  这里我将第一个批次升级成功了   当我想升级全部批次时（将BatchPartition 0去掉）它貌似报错了
![image](https://user-images.githubusercontent.com/54096513/156735124-ba393cc7-0692-4fdf-8bee-3b94286525be.png)

**Comment by barnettZQG** [comment]
@zhulaoliu 这里看起来是有些问题，建议先设置为明确的数字，比如你这里有2个批次，全部发布就填写 1。

**Comment by barnettZQG** [comment]
```
{"level":"error","ts":1646386459.822005,"caller":"usecase/application.go:713","msg":"deploy app nginx failure cannot patch object: admission webhook \"validating.core.oam.dev.v1beta1.applications\" denied the request: field \"schematic\": Invalid value error encountered, cannot evaluate trait \"rollout\": invalid template of trait rollout after merge with parameter and context: parameter.batchPartition: conflicting values int and \"\" (mismatched types int and string). ","stacktrace":"github.com/oam-dev/kubevela/pkg/apiserver/rest/usecase.(*applicationUsecaseImpl).Deploy\n\t/workspace/pkg/apiserver/rest/usecase/application.go:713\ngithub.com/oam-dev/kubevela/pkg/apiserver/rest/webservice.(*applicationWebService).deployApplication\n\t/workspace/pkg/apiserver/rest/webservice/application.go:666\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:21\ngithub.com/oam-dev/kubevela/pkg/apiserver/rest/webservice.(*applicationWebService).appCheckFilter\n\t/workspace/pkg/apiserver/rest/webservice/application.go:1070\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/oam-dev/kubevela/pkg/apiserver/rest.(*restServer).requestLog\n\t/workspace/pkg/apiserver/rest/rest_server.go:215\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/emicklei/go-restful/v3.(*Container).OPTIONSFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/options_filter.go:15\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/emicklei/go-restful/v3.CrossOriginResourceSharing.Filter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/cors_filter.go:52\ngithub.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/filter.go:19\ngithub.com/emicklei/go-restful/v3.(*Container).dispatch\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/container.go:282\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2047\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2425\ngithub.com/emicklei/go-restful/v3.(*Container).ServeHTTP\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.0.0-rc2/container.go:300\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2879\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1930"}
```

**Comment by zhulaoliu** [comment]
@[barnettZQG](https://github.com/barnettZQG)  好的 期待vela继续迭代

**Comment by wangyikewxgm** [comment]
The reason is velaux pass a empty string when a int type when remove the batchPartition field. We should fix this in velaux
