### ISSUE TITLE
[Feature] vela install fail when CRD is exist but controller not run

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#340]
```
$ vela install
- Installing Vela Core Chart:
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ScopeDefinition "healthscopes.core.oam.dev" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "vela-core"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "oam-system"
```

1. We should check CRD before install chart.
2. We should give a hint to tell user CRD is already exist.

**Comment by silenceper** [comment]
This method should split `IsCoreCRDExist`
https://github.com/oam-dev/kubevela/blob/6ede8601b4025be90b3b3578f913815b26b99276/pkg/commands/system.go#L138-L145

**Comment by captainroy-hy** [comment]
I think the author of `IsCoreCRDExist` just uses it to check whether the CRDs are installed but not specific CRs. And below shows the core CR,`healthscope`, already exists, that fails `vela install`. 
> Unable to continue with install: ScopeDefinition "healthscopes.core.oam.dev" in namespace "" exists and cannot be...

We need to check CRs in charts/vela-core/templates before installing vela-core chart.

**Comment by captainroy-hy** [comment]
[As code shows](https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/action/validate.go#L40), helm will validate the resources before creating. It not only checks whether resources already exist but also whether existing ones are adoptable by helm. So maybe we can just check the error returned from `installClient.Run(...)` and refine the output notifying users there are conflict CRs, instead of adding additional checks before `installClient.Run(...)` by ourselves.

**Comment by ryanzhang-oss** [comment]
Experimented a bit and got this error, I think the correct way is to check if the helm chart exists, upgrade instead if exists.

```
go run hack/chart/generate.go | go build -o bin/vela -ldflags "-X github.com/oam-dev/kubevela/version.VelaVersion=0.1.0 -X github.com/oam-dev/kubevela/version.GitRevision=git-3b6ced2 -X main.chartTGZSource=$(cat -) -s -w" cmd/vela/main.go
~/workspace/oam/kubevela (install-helm) $ ./bin/vela install
- Installing Vela Core Chart:
Error: cannot re-use a name that is still in use
```

**Comment by captainroy-hy** [comment]
The blocking situation happens when "vela-core" helm chart isn't installed yet but one or more CRs in the chart already exist. For example, before install vela-core chart, kubectl apply `ScopeDefinition "healthscopes.core.oam.dev"` manually or install oam-k8-runtime helm chart.

**Comment by ryanzhang-oss** [comment]
I see what you mean now. TBH, it's already a bit hacky to install helm chart on a CLI and expect user to not know much about the server-side.  I think it's ok to just install the helm and return the error from the helm to the user for now. Parsing a string type error from a client is funky business.

**Comment by wonderflow** [comment]
We could give some hints ， for example: tell users to manually delete these CRDs if they really want to install.

**Comment by wonderflow** [comment]
now we use `helm install` instead of vela install
