### ISSUE TITLE
[Feature]apply app可以响应资源属性的删除修改

### ISSUE THREAD

**Issue by reckless-huang** [oam-dev/kubevela#3400]
**Is your feature request related to a problem? Please describe.**

当我试图取消一个deploy的健康检查时，vela无法在apply操作上响应这个请求，必须删除app重新应用

**Describe the solution you'd like**

可以使用apply直接应用资源属性的删除

**Describe alternatives you've considered**

应该时patch策略的问题，为某些字段使用独特的patch策略？

**Additional context**
无

**Comment by Somefive** [comment]
@reckless-huang 你可以尝试使用 https://github.com/oam-dev/kubevela/pull/3406 新的 Json-Patch 或者 Json-merge-patch 的 Trait 来解决这个问题。目前在 master 分支上，预计会在最近的 1.3 的版本中发布。
