### ISSUE TITLE
模板中无法引用k8s元数据

### ISSUE THREAD

**Issue by reckless-huang** [oam-dev/kubevela#3401]
**Describe the bug**
![image](https://user-images.githubusercontent.com/53162954/157200835-ae7ed1f3-6604-42f4-b16b-84e72012c5a3.png)
![image](https://user-images.githubusercontent.com/53162954/157200968-7d9ea4f8-206c-44b3-932a-995e5ef71485.png)

我需要在模板中引用podname，这在正常的yaml清单中是可以使用的，但时vela不能正确渲染

**To Reproduce**
![image](https://user-images.githubusercontent.com/53162954/157201076-ae2146f5-e7f7-4059-aca2-d8251225dda9.png)
创建类似的env，提交

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.2.4

**Cluster information**
1.20.9

**Additional context**
无

**Comment by FogDong** [comment]
这一块暂时没有支持，但是修改起来比较简单，有兴趣的话欢迎贡献一下。源码在这：https://github.com/oam-dev/kubevela/blob/master/vela-templates/definitions/internal/component/webservice.cue#L406

**Comment by reckless-huang** [comment]
> 这一块暂时没有支持，但是修改起来比较简单，有兴趣的话欢迎贡献一下。源码在这：https://github.com/oam-dev/kubevela/blob/master/vela-templates/definitions/internal/component/webservice.cue#L406

的确是小小的修改一下就可以了，这个内容可以提交么
`				// +usage=use environment variables to expose information about itself to Containers running in the Pod
				fieldRef?: {
					//Version of the schema the FieldPath is written in terms of, defaults to "v1".
					apiVersion?: *"v1" | string
					// Path of the field to select in the specified API version.
					fieldPath: string
				}`
这个内容可以提交么

**Comment by wonderflow** [comment]
@reckless-huang 这个可以在你们自己的 CUE 模板里修改哈，官方的 webservice 不太适合加这个，打破了抽象。在app 这一层没有 podname 的概念。

**Comment by reckless-huang** [comment]
> @reckless-huang 这个可以在你们自己的 CUE 模板里修改哈，官方的 webservice 不太适合加这个，打破了抽象。在app 这一层没有 podname 的概念。

好的
