### ISSUE TITLE
[Feature] Reconcile Application with scoped permissions

### ISSUE THREAD

**Issue by devholic** [oam-dev/kubevela#3432]
**Is your feature request related to a problem? Please describe.**

Currently, all `Application` resources are reconciled by the Roles bound to the controller service account. This behavior gives us the power to manage resources across multiple namespaces.

However, this behavior can be problematic in the soft-multitenancy environment (e.g. Namespaces as a Service or shared cluster across teams in a single organization). For example,

- Team `A` has permission on namespace `team-a-dev` (through RBAC)
- Team `B` has permission on namespace `team-b-dev` and `team-b-staging` (through RBAC)

Team `A` can deploy to or read resources in all namespaces (including non-authorized namespaces - `team-b-dev`, `team-b-staging`) by creating an `Application` resource in `team-a-dev`.

**Describe the solution you'd like**

I would like to suggest adding the `serviceAccountName` property to `ApplicationSpec`.

When the user specifies `serviceAccountName`, the controller act as a given service account so that RBAC can be performed by Kubernetes.

#3434 is an implementation for this solution.

**Describe alternatives you've considered**

Add `AppPolicy` to check if components can be deployed or not.

However, it might be complicated because:

- We should implement our own RBAC checker in cuelang (or another component)
  - I think utilizing Kubernetes native feature is safer because we don't have to validate it for every Kubernetes release.
- Policy management tool (e.g. Kyverno) or admission webhook is required to ensure that each `Application` has the `AppPolicy`

**Drawbacks**

This proposal cannot cover the multi-cluster scenarios since either `Application` namespace or `ServiceAccount` might not exist in other clusters. (We cannot guarantee that resources mirrored)

This drawback can be resolved if `Cluster` resources are managed per namespaces, not cluster-wide. Before then, I think it would be better to skip impersonating in multi-cluster scenarios.

**Open Questions**

- We may set the `default` service account when the service account name is omitted. However, this can break existing applications, so I think it would be better to give users a migration term. Should we give a migration term or take this breaking change?

**Additional context**

- [Three Tenancy Models For Kubernetes](https://kubernetes.io/blog/2021/04/15/three-tenancy-models-for-kubernetes/)

**Comment by wonderflow** [comment]
Thanks @devholic , it‘s a big feature and really needed in the community. 

I have some suggestions:

1. users can specify the accountName in the application, what if one user use another account that not belongs to him? I think the accountName should be injected by the admission webhook according [the UID from admissionReview](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#webhook-request-and-response).
2. For multi-cluster permission check, using the impersonate mechaism is fine. We need a controller to create some serviceaccount for impersonating. We also discussed it with the OCM community, they're trying to finish [that part](https://github.com/open-cluster-management-io/enhancements/pull/41/files).

**Comment by devholic** [comment]
Thanks for the comment @wonderflow 🙂 

> 1\. users can specify the accountName in the application, what if one user use another account that not belongs to him? I think the accountName should be injected by the admission webhook according [the UID from admissionReview](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#webhook-request-and-response).

I think it makes sense to assume that the user who can create `Application` also can create resources in the same namespace, so I think it is okay to let users specify all `ServiceAccount` in the same namespace.

Also, `ServiceAccount` gives more flexibility than the UID injection, when the application is managed by multiple users. For example, if the user with insufficient permission edits the Application, it might be failed to deploy because of the lack of permission.

> 2\. For multi-cluster permission check, using the impersonate mechaism is fine. We need a controller to create some serviceaccount for impersonating. We also discussed it with the OCM community, they're trying to finish [that part](https://github.com/open-cluster-management-io/enhancements/pull/41/files).

Thanks for sharing the discussion! Creating a controller for this use-case looks good, but I think it is too big for the current issue. How about considering this in the other issue?

**Comment by wonderflow** [comment]
> How about considering this in the other issue?

Sure.

Do you think it's better if the seviceaccount is specified in the annotation?

**Comment by devholic** [comment]
> Do you think it's better if the seviceaccount is specified in the annotation?

For the Application, I think defining ServiceAccount to either spec or annotation makes sense, but I prefer the spec because it's typed.
For components (resources) created by the Application, I think it's okay to specify the ServiceAccount name in the annotation for debuggability.

**Comment by wonderflow** [comment]
@devholic As puting the serviceAccount into the spec will make the OAM model change, it's better to discuss and think more. We can make it as an annotation first so we can have this feature. And once this feature widely used, we can migrate it into spec. Would it be better for now?

The annotation name can be:  `app.oam.dev/serviceAccountName` .  

\cc @Somefive @barnettZQG  any suggestions?

**Comment by devholic** [comment]
> As puting the serviceAccount into the spec will make the OAM model change, it's better to discuss and think more. We can make it as an annotation first so we can have this feature. And once this feature widely used, we can migrate it into spec. Would it be better for now?

Sure! 🙂 

Seems other labels or annotations uses dash-case, `app.oam.dev/service-account-name` is better. I'll change PR to use annotation instead of spec 🙏

**Comment by wonderflow** [comment]
yes, `app.oam.dev/service-account-name` also fine for me
