### ISSUE TITLE
velaux 和 cli 数据是不同步的吗

### ISSUE THREAD

**Issue by steinliber** [oam-dev/kubevela#3455]
使用 vela 创建了 application，使用 vela ls，显示健康且看服务是已经起来了，如下
![image](https://user-images.githubusercontent.com/13215800/158516635-813cec4d-b1b5-4de2-9c63-35c79a129b95.png)
但是网页上并没有该应用，如下
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/13215800/158516688-2f6eb870-4bf7-44bc-98b7-ff3f59af5f0b.png">
是因为两边是不同步的吗

**Comment by wonderflow** [comment]
It's going to be fixed by #3428

**Comment by wonderflow** [comment]
closing as it's duplicated
