### ISSUE TITLE
[BUG]When error is returned, it does not necessarily mean that the resource does not exist

### ISSUE THREAD

**Issue by silenceper** [oam-dev/kubevela#347]
https://github.com/oam-dev/kubevela/blob/6ede8601b4025be90b3b3578f913815b26b99276/pkg/commands/util/init.go#L46-L50

https://github.com/oam-dev/kubevela/blob/6ede8601b4025be90b3b3578f913815b26b99276/pkg/commands/util/init.go#L61-L63

When error is returned, it does not necessarily mean that the resource does not exist.

should use `errors.IsNotFound` to check.

**Comment by wonderflow** [comment]
Yes, that's a Bug, would you like to fix it?

**Comment by ryanzhang-oss** [comment]
@silenceper  please rename them to  `DoesNamespaceExist` and `DoesCRDExist` while you are at it.

**Comment by silenceper** [comment]
No problem, I will fix it later.
