### ISSUE TITLE
vela show webservice does not show exposeType

### ISSUE THREAD

**Issue by fzy-Line** [oam-dev/kubevela#3472]
In kubevela 1.2.4, the `vela show webservice` command does not show the exposeType parameter.

**Comment by fourierr** [comment]
the exposeType parameter default to ClusterIP, other options include NodePort/LoadBalancer/ExternalName

**Comment by chivalryq** [comment]
Investigating this problem.

**Comment by chivalryq** [comment]
This field is tagged by `// +ignore`. This cause it invisible in `vela show`. You can check it by 

```shell
vela def get webservice| grep -C 5 exposeType
```

If you wanna see it again. use `vela def edit webservic` to remove this tag in CUE.

Closing. Feel free to reopen it if you have more questions.
