### ISSUE TITLE
Nominate myself @JooKS-me as a Review member

### ISSUE THREAD

**Issue by JooKS-me** [oam-dev/kubevela#3481]
I'm a mentee from LFX Mentorship, and doing the issue `Enhance multi-cluster observability`.
I has been actively contributing to KubeVela and some of his pull requests have been merged:

[oam-dev/kubevela](https://github.com/oam-dev/kubevela/pulls?q=is%3Apr+author%3AJooKS-me+is%3Aclosed)
[oam-dev/catalog](https://github.com/oam-dev/catalog/pulls?q=is%3Apr+is%3Aclosed+author%3AJooKS-me)
[oam-dev/kubevela.io](https://github.com/oam-dev/kubevela.io/pulls?q=is%3Apr+author%3AJooKS-me+is%3Aclosed)
[oam-dev/cluster-gateway](https://github.com/oam-dev/cluster-gateway/pulls?q=is%3Apr+is%3Aclosed+author%3AJooKS-me)

I has met the requirement for the Review role of KubeVela membership. So nominate him as a Review member.
Please sponsor me with 👍.

**Comment by barnettZQG** [comment]
@JooKS-me Thanks for your contribution, Can you contribute to the project on an ongoing basis?

**Comment by JooKS-me** [comment]
> @JooKS-me Thanks for your contribution, Can you continuously contribute to the project?

Of course, I think this is a promising project, and I will continue to contribute :)

**Comment by wonderflow** [comment]
LGTM, thanks for the great work! Hope to see more contributions in the future.

**Comment by fourierr** [comment]
LGTM

**Comment by Somefive** [comment]
LGTM

**Comment by wonderflow** [comment]
@JooKS-me You can send a PR for that

**Comment by JooKS-me** [comment]
> You can send a PR for that

OK, thanks so much.
