### ISSUE TITLE
[Feature] full kubernetes native rbac support

### ISSUE THREAD

**Issue by zhiyuone** [oam-dev/kubevela#3505]
**Is your feature request related to a problem? Please describe.**

![20220325145328](https://user-images.githubusercontent.com/9315872/160074968-0c5844b7-f92a-4e9e-8c08-348fc15fdb41.jpg)
uesr no permisson to create deployment, but can create deployment through application.
In some scense,  it is not suitable. And in apiserver auditing log, it's hard to trace.

Desired result: core uses my account to create a deployment, prompting that the user does not have permission

some scenes to be used:
1. strict permission management to limit user release resource
2. apiserver auditing log user behavior
3. some third party webhook need user info perform certain actions

**Describe the solution you'd like**

Use admission webhook inject user/group/serviceaccount info to application anno, such as `app.oam.dev/uesr: zhiyuone` ,this field should not be controlled by the user, and vela core use user impersonate to create resource.
User can add --k8s-rbac flag to enable this feature, it's optional.

```yaml
# after application create, application in etcd is
    ~  k get application first-app -o yaml                         ✔  ali-kind-kind-zhiyu/newbis ⎈  15:39:20 
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.oam.dev/v1beta1","kind":"Application","metadata":{"annotations":{},"name":"first-app","namespace":"newbis"},"spec":{"components":[{"name":"helloworld","properties":{"env":[{"name":"TARGET","value":"KubeVela"}],"image":"oamdev/helloworld-python:v1","port":8080},"type":"webservice"}]}}
    oam.dev/kubevela-version: v1.2.4
    oam.dev/update-by-uesr: ZhiyuWang
    oam.dev/update-by-group: Ops,Newbis,Developer,system:authenticated
  creationTimestamp: "2022-03-25T06:49:17Z"
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 1
  name: first-app
  namespace: newbis
  resourceVersion: "8143076"
  uid: 1a78a8ee-f0f9-4dd3-8729-04a6665440c3
spec:
  components:
  - name: helloworld
    properties:
      env:
      - name: TARGET
        value: KubeVela
      image: oamdev/helloworld-python:v1
      port: 8080
    type: webservice
```

**Describe alternatives you've considered**

#3432 implemented the behavior of creating resources using a service account,  we can use it overwrite the default user info.

**Additional context**

**Comment by zhiyuone** [comment]
If this proposal can be accepted, i can work for this.

**Comment by wonderflow** [comment]
@zhiyuone Thanks for the proposal. Can you describe some more details about the workflow? Please gvie some example yamls, that can be helpful to understand.

**Comment by Somefive** [comment]
So I think the solution is to add a optional mutating webhook for application which will recognize ServiceAccountName in requests and inject it into application annotation.

> Use admission webhook inject user/group/serviceaccount info to application anno, such as app.oam.dev/uesr: zhiyuone
Currently I prefer to limit the injected annotation to "app.oam.dev/service-account-name" instead of adding more annotations. If you are interested in implementing it, let's work on this annotation first.

**Comment by zhiyuone** [comment]
> @zhiyuone Thanks for the proposal. Can you describe some more details about the workflow? Please gvie some example yamls, that can be helpful to understand.

yes, I have updated the description

**Comment by zhiyuone** [comment]
> So I think the solution is to add a optional mutating webhook for application which will recognize ServiceAccountName in requests and inject it into application annotation.
> 
> > Use admission webhook inject user/group/serviceaccount info to application anno, such as app.oam.dev/uesr: zhiyuone
> 
> Currently I prefer to limit the injected annotation to "app.oam.dev/service-account-name" instead of adding more annotations. If you are interested in implementing it, let's work on this annotation first.

@Somefive 
For usernames in kubernetes, username includes user's name and service account name. app.oam.dev/service-account-name is somewhat ambiguous when applied to user's name, I think it is more suitable to be put in the spec.
Users impersonate  are divided into usernames and groups, I think at least one username annotation and one group annotation are needed.

**Comment by wonderflow** [comment]
Great , I think this proposal works for me. This is also what the community needed. Thanks @zhiyuone , please go head!

**Comment by devholic** [comment]
I think this proposal sounds great to me 🙂

However, I have a concern about the Application editing scenario:

Let's assume that there are two users in the `vela` namespace.

- User `A` has admin role in the namespace
- User `B` can edit specific resources only (`Application`, `Deployment`)

If the user `A` creates an `Application`, then user `B` tries to edit this application, application might be stuck while deploying because of the lack of permission. Also, this might cause unintended downtime to the application components (e.g. `Ingress` cannot be updated). 🤔 

I think specifying user or group to the target ServiceAccount as an annotation might be helpful. Like the structure of `StatefulSet - Pod (which specified a ServiceAccount to run with)`, for the perspective of delegating the provisioning related operations. WDYT?

**Comment by wonderflow** [comment]
Hi @devholic  , good catch. But how will it works when we follow this advice in your case? 

> specifying user or group to the target ServiceAccount as an annotation might be helpful. 

Do you mean we still use service account by creating/editing application, and the User `A` and `B` use the same service account in this case? We check if user `B` has the permission to the service account in the webhook, am I right?

**Comment by zhiyuone** [comment]
@devholic Thanks for the suggestion
I've been thinking about whether impersonating users is reasonable for vela for a long time. If we look at vela as a application controller, there is no problem with using a service account.
our current scenario is more inclined to use vela as a template generator, similar to advanced helm, but this may deviate from the original intention of vela?

> If the user A creates an Application, then user B tries to edit this application, application might be stuck while deploying because of the lack of permission. Also, this might cause unintended downtime to the application components (e.g. Ingress cannot be updated). 🤔

Sometimes this is an effect we want. We are planning to abstract cloud resources into CRDs (such as rds, doamin), developers only have permission to use them, but not delete.

> I think specifying user or group to the target ServiceAccount as an annotation might be helpful. Like the structure of StatefulSet - Pod (which specified a ServiceAccount to run with), for the perspective of delegating the provisioning related operations. WDYT?

Creating a service account for each project can also solve the problem, but it is more cumbersome to manage. I think these two ways can be parallelized.

I'm not sure what I'm doing now is reasonable or this is the best way to implement it, we need more discussion.

**Comment by Somefive** [comment]
> > So I think the solution is to add a optional mutating webhook for application which will recognize ServiceAccountName in requests and inject it into application annotation.
> > > Use admission webhook inject user/group/serviceaccount info to application anno, such as app.oam.dev/uesr: zhiyuone
> > 
> > 
> > Currently I prefer to limit the injected annotation to "app.oam.dev/service-account-name" instead of adding more annotations. If you are interested in implementing it, let's work on this annotation first.
> 
> @Somefive For usernames in kubernetes, username includes user's name and service account name. app.oam.dev/service-account-name is somewhat ambiguous when applied to user's name, I think it is more suitable to be put in the spec. Users impersonate are divided into usernames and groups, I think at least one username annotation and one group annotation are needed.

I'm not sure if we need to add user/group concept into application now. /cc @wonderflow 
The ServiceAccount part is the basic natural identity mechanism in Kubernetes. IMO, application should directly use the service account but now do any further permission check in the controller right now. The User/Group part could be a third-part implementation on top of the ServiceAccount as different corporations may have different way to user RBAC. So it might be better to do the User-SA conversion in webhook as @wonderflow suggested. And this webhook part should be pluggable or extensible to some extent.

**Comment by devholic** [comment]
@wonderflow

> Do you mean we still use service account by creating/editing application, and the User `A` and `B` use the same service account in this case? We check if user `B` has the permission to the service account in the webhook, am I right?

Yes, but it might be cumbersome to manage as @zhiyuone pointed out 😢

**Comment by wonderflow** [comment]
@zhiyuone I think this won't prevent us from implementing it. As @Somefive said, this mechanism works in admission webhook and it will have feature flag that users can choose to turn it on/off. By default, it should be turned off.

**Comment by wonderflow** [comment]
@devholic we're also practicing something similar to your proposal in velaux ( #3493  ).

**Comment by zhiyuone** [comment]
done by  https://github.com/oam-dev/kubevela/pull/3713
