### ISSUE TITLE
[Feature] ignore the namespace resource when executing the application GC

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#3535]
**Is your feature request related to a problem? Please describe.**

There is a case, we enable the flux addon to an ACK cluster, which will create a namespace by component. when we want to disable this addon, it can not be GC successful as there is a can not be deleted namespace, in this namespace, ACK creates some other resources. such as `containernetworkfilesystem.storage.alibabacloud.com`.

I think the namespace is a special resource, the user or other client maybe create some other resources in the namespace. 

**Describe the solution you'd like**

ignore the namespace resource when executing the application GC.

**Comment by chivalryq** [comment]
Maybe check this? app with gc policy. Keep namespace component away from GC.
https://github.com/oam-dev/kubevela/blob/master/docs/examples/app-with-policy/gc-policy/persist-resources.md

**Comment by Somefive** [comment]
Support selecting resources by component name in #3539.

**Comment by barnettZQG** [comment]
@Somefive @chivalryq  By specifying a policy that's one way to do it, but if one component has multiple resources and includes a namespace, this approach seems to be inappropriate.

On the other hand, I'm wondering should it be something that the user should perceive?

**Comment by Somefive** [comment]
> but if one component has multiple resources and includes a namespace, this approach seems to be inappropriate.
If you want to do so, we can extend the selector by resource type and resource name. But this means users need to interact with resources directly instead of upper abstract model layer, such as traits and components.

> On the other hand, I'm wondering should it be something that the user should perceive?
IMO, we should. Why namespace should be a resource that is not expected be recycled by default? Adding implicit special rules are hacks and there is no obvious evidence that this is a good practice by now.

**Comment by barnettZQG** [comment]
I'll leave that thought for the moment.
