### ISSUE TITLE
Error: no port found in app or arguments

### ISSUE THREAD

**Issue by drozzy** [oam-dev/kubevela#3538]
Following the install instructions here:
https://kubevela.io/docs/install

When I get to this part:
`vela port-forward addon-velaux -n vela-system`

I get this error if I select the indicated in the docs menu item:
```
Error: no port found in app or arguments
```

**Comment by barnettZQG** [comment]
@drozzy are you installed by the command `vela addon enable velaux`?

**Comment by drozzy** [comment]
Yes, I followed the install procedure exactly. Not sure what went wrong.

**Comment by barnettZQG** [comment]
```
vela port-forward -n vela-system addon-velaux 9082:80
```

**Comment by drozzy** [comment]
Thanks
