### ISSUE TITLE
[Feature] vela api support multi components when create an application

### ISSUE THREAD

**Issue by guobingithub** [oam-dev/kubevela#3577]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
I think it's supported now in [v1.3.0](https://github.com/oam-dev/kubevela/releases/tag/v1.3.0), please have a try!

I'm going to close it, feel free to re-open if you still have any issues on it.
