### ISSUE TITLE
 Nominate myself @s4rd1nh4 as a Review member

### ISSUE THREAD

**Issue by s4rd1nh4** [oam-dev/kubevela#3588]
I has been actively contributing to KubeVela Core and three of his pull requests have been merged.
https://github.com/oam-dev/kubevela/pull/3408
https://github.com/oam-dev/kubevela/pull/3403
https://github.com/oam-dev/kubevela.io/pull/566
https://github.com/oam-dev/kubevela.io/pull/477
https://github.com/oam-dev/samples/pull/76
I has met the requirement for the Review role of KubeVela membership. So nominate him as a Review member.
Please sponsor me with 👍.

**Comment by wonderflow** [comment]
👍  great! Thanks! Hope to see more contributions!

**Comment by BinaryHB0916** [comment]
+1，Thanks for your efforts and let's explore more.

**Comment by FogDong** [comment]
👍Cool! Welcome to the community:)

**Comment by wangyikewxgm** [comment]
👍   Thanks for the contributions.
