### ISSUE TITLE
[feature] Natively support modern CI/CD pipeline with user friendly interface.

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#36]
For open source, we should support Tekton, and we should build abstraction for because Tekton is super hard to use.
For non-open source, we can support GitHub Actions.

In implementation, we could consider introduce a pipeline concept in the app engine, for example: https://devcenter.heroku.com/articles/pipelines

**Comment by wonderflow** [comment]
https://kubevela.io/docs/case-studies/jenkins-cicd
