### ISSUE TITLE
kubevela install error using latest intall.sh

### ISSUE THREAD

**Issue by ArenaSu** [oam-dev/kubevela#3601]
**Describe the bug**

Install message below:

> Your system is linux_amd64
> Installing Vela CLI...
> 
> Getting the latest Vela CLI...
> Installing v1.3.0 Vela CLI...
> Downloading https://github.com/oam-dev/kubevela/releases/download/v1.3.0/vela-v1.3.0-linux-amd64.tar.gz ...
> curl: (35) Encountered end of file
> failed to download https://github.com/oam-dev/kubevela/releases/download/v1.3.0/vela-v1.3.0-linux-amd64.tar.gz ...
> Failed to install Vela CLI
> For support, go to https://kubevela.io

**To Reproduce**

1. download https://kubevela.io/script/install.sh
2. bash install.sh

**Expected behavior**

Install success without error.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
@ArenaSu I think this is a network error, are there any more updates about this Issue?

**Comment by barnettZQG** [comment]
Maybe issue #3551 become more urgent.

**Comment by StevenLeiZhang** [comment]
> #3551
it is cause by network connection issue. just retry.

**Comment by barnettZQG** [comment]
@ArenaSu we have already published the new install script, install vela from OSS. so, I will close this Issue.
