### ISSUE TITLE
[Feature] Flink Workload

### ISSUE THREAD

**Issue by oeular** [oam-dev/kubevela#3610]
Use Case: flink(operator) workload for processing the big data

To improve the usability of big data processing framework, and its extendibility, so as its other business traits

**Comment by wonderflow** [comment]
great, this can be a flink addon.

**Comment by fourierr** [comment]
great work

**Comment by oeular** [comment]
@wonderflow  PR is coming, https://github.com/oam-dev/catalog/pull/332#issue-1213276527

**Comment by wonderflow** [comment]
https://github.com/kubevela/catalog/pull/337 supported
