### ISSUE TITLE
Revisit `vela system update` command

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#362]
Currently, the `vela system update` command is used to fetch remote definitions from APIServer and sink to local the Capability struct. This requires the user to manually refresh to deploy apps or fetch definitions every time (in this case there is no need to local files too).

The biggest problem is that refreshing manually is not a good user experience. This issue is to rethink about the problem and discuss better solutions.

**Comment by wonderflow** [comment]
Yes， I have discussed with @resouer , we should find some mechanism to run this command automatically background.

**Comment by wonderflow** [comment]
we could use `vela workloads` and `vela traits` to do this refresh work.

**Comment by wonderflow** [comment]
fixed by #505
