### ISSUE TITLE
[Feature] Support workload or trait CRs deploy to the specified cluster

### ISSUE THREAD

**Issue by oeular** [oam-dev/kubevela#3622]
# some workload or trait CRs intend to deploy in HubCluster, for
- make the managed cluster clean and pure as possible as we can, for future upgrade and maintainance
- make the related vela resources easy to control, upgrade and maintainance

**Comment by fourierr** [comment]
Later, we will write the concrete proposal in the comments

**Comment by wonderflow** [comment]
does this issue resolved in https://github.com/oam-dev/kubevela/pull/3774
