### ISSUE TITLE
Rename installing vela-core from `vela install` to `vela system init`

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#365]
`vela install` is better reserved for installing apps like `vela install xxx-app`.
Installing/upgrading/uninstalling vela-core as k8s plugin would be better renamed to `vela system init/update/uninstall`.

**Comment by wonderflow** [comment]
what about keep `vela install` as the old way and use `vela deploy xxx-app` for this intention？


`vela install --upgrade`

`vela uninstall`

**Comment by hongchaodeng** [comment]
First-level command line should be app centric.
Installing core runtime is system level details and should go under `system`

**Comment by hongchaodeng** [comment]
Also look at waypoint https://www.waypointproject.io/docs/getting-started

A lot of CLI tools use init to do "system init" work. We should rename install to init absolutely.
Current `init` should be renamed to `app init` or just `app`.

**Comment by wonderflow** [comment]
@hongchaodeng  I noticed waypoint  uses `waypoint install` to install server, just like our `vela install`. Cureently `vela init` is app init.

**Comment by resouer** [comment]
Let's leave this issue for next phase. I am fine to have `vela install` for now and it's easy to rename it whenever we decide to make `install` cmd for sth else.

**Comment by hongchaodeng** [comment]
> Cureently vela init is app init.

That's the issue. Most tools will use the `init` to initialize system. Just like Waypoint, Helm, etc.
I would suggest to rename app init to `vela app init` or `vela up -i`.

**Comment by hongchaodeng** [comment]
I don't have strong opinions on this. If you stick to existing ideas I'm fine with it.
