### ISSUE TITLE
can not successfully create a docker registry integration configuration

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/kubevela#3663]
**Describe the bug**

Create a docker registry integration configuration, only set registry URL, the configuration status is not ready.

**Screenshots**
![image](https://user-images.githubusercontent.com/18493394/163422568-4c264b09-bd50-4c74-9038-a35eb513d69c.png)
**KubeVela Version**
1.3.1 

**Additional context**

**Comment by StevenLeiZhang** [comment]
Are you trying to create one "kubernetes.io/dockerconfigjson" secret? I think this error may be reported by K8s, because this secret workload format is wrong.

**Comment by zzxwill** [comment]
@StevenLeiZhang Yes. For a public docker registry, I will just set the url in the data of the secret.

**Comment by s4rd1nh4** [comment]
I think for public docker it is not necessary to create secret or use imagePullSecrets. The kubelet already has access to this.

**Comment by barnettZQG** [comment]
@s4rd1nh4 It's right, but there is a context, the secret is generated by a docker registry configuration. 
Ref: https://github.com/oam-dev/kubevela/blob/master/vela-templates/definitions/internal/component/config-image-registry.cue#L37

If there is a public Docker registry, it can not generate the secret.
