### ISSUE TITLE
[BUG][Dashboard] Application details crashed

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#369]
http://localhost:8000/#/ApplicationList/appconfig-scaler/Components

>×
Error: Objects are not valid as a React child (found: object with keys {condition, enabled, name, type}). If you meant to render a collection of children, use an array instead.
    in p (at ComponentDetail/index.jsx:444)
    in div (created by Context.Consumer)
    in Col (at ComponentDetail/index.jsx:443)
    in div (created by Context.Consumer)
    in Row (at ComponentDetail/index.jsx:421)
    in div (at ComponentDetail/index.jsx:385)
    in div (created by Context.Consumer)
    in Col (at ComponentDetail/index.jsx:378)
    in div (created by Context.Consumer)
    in Row (at ComponentDetail/index.jsx:279)
    in div (created by TabPane)
    in TabPane (at ComponentDetail/index.jsx:278)
    in div (created by TabPanelList)
    in div (created by TabPanelList)
    in TabPanelList (created by ForwardRef(Tabs))
    in div (created by ForwardRef(Tabs))
    in ForwardRef(Tabs) (created by Tabs)
    in Tabs (at ComponentDetail/index.jsx:277)
    in div (at ComponentDetail/index.jsx:272)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (at ComponentDetail/index.jsx:271)
    in div (at ComponentDetail/index.jsx:270)
    in TableList (created by Connect(TableList))
    in Connect(TableList) (at Components/index.jsx:171)
    in div (at Components/index.jsx:158)
    in div (at Components/index.jsx:132)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (at Components/index.jsx:131)
    in div (at Components/index.jsx:117)
    in TableList (created by Connect(TableList))
    in Connect(TableList) (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (created by WrapContent)
    in ConfigProviderWarp (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (at BasicLayout.jsx:87)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in SecurityLayout (created by Connect(SecurityLayout))
    in Connect(SecurityLayout) (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by RouterComponent)
    in RouterComponent
    in Provider (created by _DvaContainer)
    in _DvaContainer
    in Unknown
    in _LocaleContainer
    in Unknown
▶ 39 stack frames were collapsed.
_callee$
./src/pages/ApplicationList/ComponentDetail/index.jsx:63
  60 |   },
  61 | });
  62 | if (res) {
> 63 |   this.setState({
     | ^  64 |     compDetailData: res,
  65 |   });
  66 |   const traits = await this.props.dispatch({
View compiled
▶ 5 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by woshilanren11** [comment]
fixed
