### ISSUE TITLE
[BUG][Dashbaord] Remove definition field of workloads and traits

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#370]
![image](https://user-images.githubusercontent.com/2805315/95645288-238ffd80-0af0-11eb-8957-22fc49ed0fea.png)

For background, please refer to issue #349

**Comment by woshilanren11** [comment]
ok

**Comment by zzxwill** [comment]
Please increase the font size of make workload/trait name to make it more noticable.
