### ISSUE TITLE
[Question] How to support list type in workload template, such as env .. `

### ISSUE THREAD

**Issue by Suozz** [oam-dev/kubevela#391]
This is a wrokload template in workload. If I want to supprt env parameter in `bachend`, what should I do?
```
data: {
	apiVersion: "standard.oam.dev/v1alpha1"
	kind:       "PodSpecWorkload"
	metadata:
		name: parameter.name
	spec: {
		replicas: 1
		podSpec: {
			containers: [{
				image: parameter.image
				name:  parameter.name
			}]
		}
	}
}

#backend: {
	name: string
	// +usage=specify app image
	// +short=i
	image: string
}
parameter: #backend

**Comment by wonderflow** [comment]
We‘re planning to fix this by using Appfile https://github.com/oam-dev/kubevela/pull/390

**Comment by resouer** [comment]
@Suozz Yes, for complex command parameters, we will recommend KubeVela's AppFile (#390 ), it's equivalent to vela CLI (i.e. CUE template based) but more powerful (because you can define complex structure there).

That being said, the next release of vela CLI will also support some common complex structures like env pairs and ports pairs, the UI is like below:

```console
$ vela comp deploy --env foo=bar --env db=mysql
```

**Comment by Suozz** [comment]
> We‘re planning to fix this by using Appfile #390

when this feature will be merged into master branch?

**Comment by wonderflow** [comment]
> when this feature will be merged into master branch?

In one week.

> will it support in vela apiserver mode

It definitely will, we're working on that. We can't give a specific time now.

**Comment by Suozz** [comment]
> > when this feature will be merged into master branch?
> 
> In one week.
> 
> > will it support in vela apiserver mode
> 
> It definitely will, we're working on that. We can't give a specific time now.

btw, we want to return a

**Comment by Suozz** [comment]
@hongchaodeng when will support this feature in APIServer?  It seems like it doesnot not support in current master version

**Comment by wonderflow** [comment]
Now the server side object Application has been implemented, please refer to  https://github.com/oam-dev/kubevela/blob/master/docs/en/application.md for this feature
