### ISSUE TITLE
[Feature] A developer centric user story

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#399]
Today @hongchaodeng mentioned he intends to introduce a dev centric user story to vela as the alternative to current vela CLI. Here's the thoughts in my mind:

- [P0] The vela dashboard server and glue code should be migrated to appfile implementation.
- [P0] The new vela CLI feature set:

/cc @wonderflow for review.

**Comment by hongchaodeng** [comment]
The current CLI set is not app centric, but more ops centric. It is important to note that even though we are developing tools based on k8s it is for developers.

It is fine to keep the current CLI features, but we should also have a app centric story as follows:

## 1. Initialize project

Just like `waypoint init` or `heroku create`, this is the entry point to set up build and deploy files for the project.

## 2. Deploy

This is what `vela up` targets. This should be using the Appfile to render deployment manifests, and interacting with backend system to create a **new** deployment for the app. Note that this is different from release, but more like a canary deployment. Users can manually test it or dogfood some traffic to it, and observe its behaviors before final release decision making.

## 3. Troubleshooting

Once the latest change has been deployed, users need to further test it, and debug the running process if errors occur. The following features should be provided:

- `vela logs`: Users need to view the logs of the app. See https://github.com/oam-dev/kubevela/issues/161.
- `vela port-forward`: Runtime and tools could support [remote debugging](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging), and Vela need to provide native port-forward to the app.
- `vela exec`: Users need to ssh into the containers and troubleshoot.
- Additional routing capability to direct some traffic to new deployment based on HTTP headers.

## 4. Release

If everything is fine, the app should be released to serve real world traffic. This is the final phase of the app.

**Comment by resouer** [comment]
The general idea of developer experience LGTM, note that the "release phase" is also in kubevela's roadmap.  Ref: https://github.com/oam-dev/kubevela/issues/299 which is the backend capability release phase would rely on.

**Comment by resouer** [comment]
Based on offline discussion, we will: 1. merge the current CLI and dashboard code in `pkg/application` with Appfile implementation (target on KubeCon NA timeline) and 2. migrate Appfile feature set to above user story step by step.

**Comment by wonderflow** [comment]
#173

**Comment by wonderflow** [comment]
`vela exec` #171

**Comment by wonderflow** [comment]
`vela logs ` has been done #414
