### ISSUE TITLE
[Feature] Align terms for core concept 

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#412]
Kubevela is an implementation of OAM, in OAM, we have AppConfig and Component.

In kubevela ,  we have lots of concepts, this is really confusing, we must align them.

*  `workload Name`, `component Name`, `Service Name` all represent OAM Component
* `App`, `AppGroup` all represent to OAM AppConfig.

I prefer we we `component` in vela for OAM Component and use `app` for OAM AppConfig.

\cc @hongchaodeng @resouer

**Comment by wonderflow** [comment]
After discuss with @hongchaodeng and @resouer  offline， we all agree to align to :

`service` => 'OAM Component'
`app`(appfile) => 'OAM AppConfig'

**Comment by wonderflow** [comment]
`vela comp` => `vela svc`

term "component" => "service"

**Comment by captainroy-hy** [comment]
`vela comp -t <workload-type> --app [AppName]` => `vela svc -t <workload-type> --app [AppName]`
`vela <trait> [CompName] --app [AppName]` => `vela <trait> [AppName] --svc [ServiceName]`

And these commands showing the term "component" in the outputs:`vela init`, `vela logs`, `vela exec`,`vela up`
I would like to revise these terms from "component" into "service".

But is it necessary to change the variable or function names in the code,e.g., getComponents() => getServices()?

**Comment by wonderflow** [comment]
@captainroy-hy  workload-type should be service type if we need to tell user this concept

**Comment by wonderflow** [comment]
> But is it necessary to change the variable or function names in the code,e.g., getComponents() => getServices()?

We could make it the second step, this is no high priority, please don't include them in the first step.

**Comment by captainroy-hy** [comment]
> @captainroy-hy workload-type should be service type if we need to tell user this concept

> We could make it the second step, this is no high priority, please don't include them in the first step.
Got it.
