### ISSUE TITLE
[Feature] Command 'vela up' needs 'docker', 'kubectl','kind' as prerequisite

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#413]
1. For 'docker', I can say 90% developer will have docker installed in their environment, make it as prerequisite in readme is OK.

2. For 'kubectl' and 'kind', we must remove them.

**Comment by hongchaodeng** [comment]
For 1, this could be improved by using builtkit: https://github.com/oam-dev/kubevela/issues/416

For 2, kubectl can be replaced with go client. 
kind doesn't have a go client. Before we find any alternatives we could not do it.

**Comment by hongchaodeng** [comment]
kubectl dependency has been resolved in #402

**Comment by wonderflow** [comment]
closing this one, let's focus on #416
