### ISSUE TITLE
[Feature] [Low Priority] make kubevela as brew package

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#427]
Or other ways to prevent this error

![image](https://user-images.githubusercontent.com/2173670/96949637-ee85a100-151a-11eb-9623-5a8a584d2f31.png)

**Comment by sunny0826** [comment]
like this ?
```bash
brew install kubevela
```

**Comment by wonderflow** [comment]
@sunny0826  sure, just like this

**Comment by sunny0826** [comment]
Maybe I can do this.

**Comment by wonderflow** [comment]
@sunny0826  Cool！

**Comment by sunny0826** [comment]
https://formulae.brew.sh/formula/kubevela#default

Brew has been successfully pushed

**Comment by wonderflow** [comment]
closing, thanks again @sunny0826
