### ISSUE TITLE
Provide a command to help insert cue file into extension.template field

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#430]
It is better to manage cue file separately for format validation.

Better provide a command to help insert the cue content into definition  extension.template field like the following:
```
vela template insert-cue --cue-file=a.cue --def-file=b.yaml
```

**Comment by szihai** [comment]
Can we have an option just to validate/dryrun the template file?

**Comment by resouer** [comment]
@szihai I think it makes sense to validate the template upon any definition object is installed.

**Comment by wonderflow** [comment]
supported now, just use:

```
vela system dry-run app.yaml
```

The yaml should be Application CRD object.
