### ISSUE TITLE
[BUG]vela install autoscalers.standard.oam.dev template error

### ISSUE THREAD

**Issue by szihai** [oam-dev/kubevela#464]
Git pull latest, make, and run vela install:

**Screenshots**

![image](https://user-images.githubusercontent.com/26101651/97484307-d2687200-1915-11eb-890c-1b999a868a49.png)
Vela Version
![image](https://user-images.githubusercontent.com/26101651/97484529-0ba0e200-1916-11eb-90c5-d21c82cbb9b3.png)

**Comment by hongchaodeng** [comment]
There is no template in autoscaler yet. Assign @zzxwill to catch it up.

**Comment by zzxwill** [comment]
Fixed after autoscale is merged as a built-in trait as its definition is applied when vela-core is installed.
