### ISSUE TITLE
Generating markdown reference docs for capabilities from CUE templates

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#492]
#  Background

Currently all CUE-exposed capabilities are defined in [CUE files](https://github.com/oam-dev/kubevela/tree/master/hack/vela-templates/cue). We want to let user read markdown files to understand the fields to write [Appfile](https://github.com/oam-dev/kubevela/blob/master/docs/developers/devex/appfile.md).

# Proposed Solution

## Step 1: Generate OpenAPI Schema from CUE templates

First we need to convert CUE templates into more standard API format so that we can utilize open source tooling to convert to markdown format.
Here's an [example](https://hackmd.io/eQJv25hdQW6LwMUBkViL6A) to convert CUE template into OpenAPI Schema.

## Step 2: Convert OpenAPI Schema to Markdown

Once we have OpenAPI schema, we can use [openapi-generator](https://openapi-generator.tech/docs/generators/markdown/) to generate markdown files automatically. To go one step further, we can [host the API doc on Github Page](https://peterevans.dev/posts/how-to-host-swagger-docs-with-github-pages/)

**Comment by resouer** [comment]
Additionally, besides hosting the doc on Github page, users should be able to check the doc by vela CLI at ease.

For example, `$ vela show metrics` should return the reference doc for metrics trait to me. 

> A simpler approach is opening the doc link (as Copilot is doing) but in this approach it won't work on pure terminal or offline mode .
