### ISSUE TITLE
Generate website from markdown docs and blogs

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#494]
# Background

Currently we only have markdown docs and another [website repo](https://github.com/oam-dev/kubevela.io) sort of isolated from the docs in this repo.

Comparatively, other open source projects will auto generate websites for the docs and blogs in the main repo: [waypoint](https://github.com/hashicorp/waypoint/tree/main/website), [crossplane](https://github.com/crossplane/crossplane.github.io/tree/master/docs), [kalm](https://github.com/kalmhq/docs).

# Proposal

We could: 
1. either merge the website code back into this repo to have the doc updated in one place, or
2. automatically release the doc into the website repo. 

For the second option, we could have docs of multiple releases shown in the website.

Another note is that since it is early stage, we should consider migrating from Jekyll to [Docusaurus](https://docusaurus.io/en/) or [hugo](https://gohugo.io/documentation/). Docusaurus has the easiest and best default setup, and is focused on documentation sites only. I also like hugo since it is written in Go and uses Go templating which is close to our tech stack.

**Update**: Actually [docsify](https://docsify.js.org/#/) provides the easiest and best default setup.

**Comment by hongchaodeng** [comment]
cc @zzxwill

**Comment by hongchaodeng** [comment]
cc @sunny0826

**Comment by sunny0826** [comment]
### options

* [docsy](https://www.docsy.dev/) - hugo theme([google](https://github.com/google/docsy/) opensource), showcase: [kubeflow](https://www.kubeflow.org/), [kpt](https://googlecontainertools.github.io/kpt/), [chaosblade](https://chaosblade.io/)
* [Docusaurus](https://docusaurus.io/en/) - facebook opensource, [V1](https://docusaurus.io/en/) & [V2](https://v2.docusaurus.io/), [V2 showcase](https://v2.docusaurus.io/showcase): [Algolia Docsearch](https://docsearch.algolia.com/), [Amphora Data](https://www.amphoradata.com/)
* [docsify](https://docsify.js.org/#/) - [showcase](https://docsify.js.org/#/zh-cn/awesome): [styled-wind ](https://styled-wind.netlify.app/#/)
* [Docsite](https://docsite.js.org/zh-cn/index.html) - Alibaba opensource, [showcase](https://docsite.js.org/zh-cn/index.html): [openkruise](http://openkruise.io/en-us/), [Dragonfly](https://d7y.io/en-us/), [Sentinel](https://sentinelguard.io/zh-cn/)

**Comment by hongchaodeng** [comment]
docsify +1
See my top level comment for reasoning.

**Comment by szihai** [comment]
Either docsy or docsify is good.

**Comment by sunny0826** [comment]
preview: https://sunny0826.github.io/kubevela-website

**Comment by hongchaodeng** [comment]
@sunny0826 That looks awesome!
Welcome to submit PR to either kubevela or kubevela.io repo.
