### ISSUE TITLE
[Feature]  using helm operator/ CRD registry to manage charts installation 

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#499]
Currently, we install CRD dependency by using velaconfig.yaml in charts, it will simply install helm chart，without any check/uninstall.

**Comment by hongchaodeng** [comment]
I totally agree.
Ideally, the dependency installer should be run as a separate component since there is a clear boundary from Vela Core server. We could use existing open source tool like [helm operator](https://github.com/fluxcd/helm-operator) to handle it.

**Comment by wonderflow** [comment]
prefer #1760
