### ISSUE TITLE
Sync docs between kubevela.io and this repo

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#541]
The content under [kubevela.io](https://github.com/oam-dev/kubevela.io/tree/master/en) consists of  README+ doc/ from this repo. Need to set up jobs (Github Action?) to sync it automatically.

My 2c:
- option 1: setup a new github action on new master push
- option 2: add a sync step on existing "release" action

**Comment by hongchaodeng** [comment]
Actually a simpler way is to remove all docs under this repo and redirect all doc changes to kubevela.io repo. This is what [crossplane docs](https://github.com/knative/docs) and [knative docs](https://github.com/knative/docs) do.

What do you think?
@sunny0826 @wonderflow @zzxwill

**Comment by resouer** [comment]
I am not sure how sync can keep the relative path of image work (but I recalled Kubernetes indeed do sync in early stage), so I would vote for moving docs to website repo if it's the easiest fix.

**Comment by hongchaodeng** [comment]
There will be an issue with CLI auto generated docs. Either we remove it from website or still need to sync it.

**Comment by hongchaodeng** [comment]
After offline discussion, we decided to move kubevela.io repo into a website/ under this repo.
Similar to [what waypoint does](https://github.com/hashicorp/waypoint/tree/main/website)

**Comment by wonderflow** [comment]
It's done by #551 Thanks to @sunny0826 very much!
