### ISSUE TITLE
[BUG]vela.yaml and Dockerfile path dependency?

### ISSUE THREAD

**Issue by szihai** [oam-dev/kubevela#542]
**Describe the bug**
Using the example/testapp. When running  `vela up` under the `examples/testapp`, everything is fine. However when running `vela up` from another folder, there is error message.
**To Reproduce**
go to `examples`.
run `vela up -f testapp/vela.yaml`, 
![image](https://user-images.githubusercontent.com/26101651/98583508-5d802b00-2279-11eb-9c40-75af27d11105.png)

**Comment by hongchaodeng** [comment]
Yes. The vela.yaml in example/testapp has build dependency. If you already have the image built, you need to remove/comment the build config.

**Comment by wonderflow** [comment]
I think it's by design, the vela.yaml should under the source project of app with dockerfile if you want to build from source.
