### ISSUE TITLE
[Feature] vela appfile should support no template case

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#565]
if no template specified in Definition, the schema could be arbitrary or align with CRD schema.

In other words, template should be optional.

**Comment by zzxwill** [comment]
Totally agree with this proposal. 
This will open a door for platform builders to integrate other workloads and traits into vela capabilities instead of taking a deep understanding of CUE and vela capability mechanism.

**Comment by resouer** [comment]
This doesn't make sense from any aspect. If no template provided, there's no appfile. 

And please invest time on docs about how to define CUE template, explain the grammars and schemas. This is important but missing in current docs.
