### ISSUE TITLE
[Feature] Using discoveryMapper to get apiversion and kind from definition

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#572]
![image](https://user-images.githubusercontent.com/2173670/98799029-8b1bce80-2449-11eb-9753-2faa4a8b6021.png)

**Comment by hongchaodeng** [comment]
Discovery client is only used for retrieving the resource client to do CRUD actions.
What you are proposing still needs to parse APIVersion/Kind from somewhere but not from discovery client.
