### ISSUE TITLE
[Feature] Automatically generate workload-types/traits reference docs

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#577]
Also needs to elaborate all parameter fields with frustrated type (list/struct(map)).

**Comment by zzxwill** [comment]
Working in progress.

**Comment by resouer** [comment]
Please note the reference doc should NOT be schema only like this: https://github.com/oam-dev/kubevela/blob/master/docs/en/developers/references/workload-types/web-service.md#properties

It should always include a full specification sample like this: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/ and then following by schema explaination.

**Comment by hongchaodeng** [comment]
@resouer Can you provide a automated solution for it?

**Comment by resouer** [comment]
@hongchaodeng For the sample I currently don't know a straightforward way, manually added for built-in ones for now: https://github.com/oam-dev/kubevela/pull/579 May need to check with CUE folks.

**Comment by hongchaodeng** [comment]
Please see https://github.com/oam-dev/kubevela/issues/492

I already proposed a solution based on CUE + openapi-generator. Let's converge the discussion to there.

**Comment by zzxwill** [comment]
> Please see #492
> 
> I already proposed a solution based on CUE + openapi-generator. Let's converge the discussion to there.

Sure, thanks.
