### ISSUE TITLE
[Feature] deprecate 'vela svc deploy' and delete the related code

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#644]
`vela up` should be the only way for deploy apps.

**Comment by zzxwill** [comment]
-1. I think hiding `vela svc deploy` command is enough as hiding means end-developers could not use it from CLI. But for contributors or just me, it's very helpful for svc/traits debugging, or in local development scenarios, vela.yaml file has to be modified now and then for the debug/devs, which is not convenient.

**Comment by zzxwill** [comment]
Support removing it the day it's super easy to prepare vela.yaml.
