### ISSUE TITLE
[BUG] It's not convenient to locally debug/test pkg/webhook logics 

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#652]
As there is not a way to locally run OAM Kubernetes Runtime, it's not convenient to debug/test pkg/webhook logics.
I have to deployed the runtime with webhook enabled in a Kubernetes cluster like in a black box (#651 ) and run the test.

**Comment by wonderflow** [comment]
I don't know why you're talking about OAM runtime here? Do you mean vela-core?

**Comment by zzxwill** [comment]
As the repo is moving, I think I'd better avoid creating issues/PRs in runtime repo.

**Comment by wonderflow** [comment]
@zzxwill  even we merge that repo into vela, we will not talk oam-runtime here, we will say they're all vela-core
