### ISSUE TITLE
[BUG]Refer to the kube client only when needed

### ISSUE THREAD

**Issue by sunny0826** [oam-dev/kubevela#655]
**Describe the bug**

If `kubeconfig`(.kube/config) does not exist, the following error is thrown:

```bash
$ vela -h
get kubeconfig err invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

**To Reproduce**

```bash
$ cd ~/.kube
$ mv config config.bak
$ vela -h
get kubeconfig err invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

**Expected behavior**

Refer to the client only when needed.

**Screenshots**

![image](https://user-images.githubusercontent.com/24563928/100194321-71da4e00-2f30-11eb-888a-c5343a3f8c10.png)

**Additional context**

We may need to change `github/kubevela/pkg/commands/cli.go`

```go
// github/kubevela/pkg/commands/cli.go
...
func NewCommand() *cobra.Command {
	ioStream := util.IOStreams{In: os.Stdin, Out: os.Stdout, ErrOut: os.Stderr}

	cmds := &cobra.Command{
		Use:                "vela",
		DisableFlagParsing: true,
		Run: func(cmd *cobra.Command, args []string) {
			allCommands := cmd.Commands()
			cmd.Printf("✈️  The Extensible Application Platform Based on Kubernetes and Open Application Model (OAM).\n\nUsage:\n  vela [flags]\n  vela [command]\n\nAvailable Commands:\n\n")
			PrintHelpByTag(cmd, allCommands, types.TypeStart)
			PrintHelpByTag(cmd, allCommands, types.TypeApp)
			PrintHelpByTag(cmd, allCommands, types.TypeCap)
			PrintHelpByTag(cmd, allCommands, types.TypeSystem)
			cmd.Println("Flags:")
			cmd.Println("  -h, --help   help for vela")
			cmd.Println()
			cmd.Println(`Use "vela [command] --help" for more information about a command.`)
		},
		SilenceUsage: true,
		ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			return nil, cobra.ShellCompDirectiveNoFileComp
		},
	}
	cmds.PersistentFlags().StringP("env", "e", "", "specify environment name for application")

        // We may need to change here 
	restConf, err := config.GetConfig()
	if err != nil {
		fmt.Println("get kubeconfig err", err)
		os.Exit(1)
	}
...
```

**Comment by wonderflow** [comment]
Thanks for reporting, to fix this issue, we need to move **GetConfig** into specify commands who need this config instead of create before all commands.

**Comment by horis233** [comment]
@zzxwill I create a PR for this issue. If you already have a plan for it, feel free to close it.

**Comment by zzxwill** [comment]
@horis233 Are you working on Windows? If yes, could you please try to install the Cli by the powshellscript https://kubevela.io/#/en/install?id=_2-get-kubevela? Thanks.

**Comment by zzxwill** [comment]
I hit the same issue on Windows Server. It would be better If it could be verified in Windows Desktop.

**Comment by wonderflow** [comment]
This PR was not contained in the latest release, make sure you're clear about it? @zzxwill

**Comment by zzxwill** [comment]
@wonderflow Yes, you are right. Thanks for the kind remind.
I will close this one and follow up the Windows issue after a new release is out.
