### ISSUE TITLE
[Feature] Add controller startup parameters to allow disbale inner workload/trait controller

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#658]
By default, vela-core will start all inner controllers. We could add some prameters such as:

```
./vela-core --disable-cap "route,metrics"
```

To disable these inner controller to run.

Note: we should also distinguish them in webhook part.

**Comment by zzxwill** [comment]
For what purpose were some builtin capabilities be disabled?

**Comment by wonderflow** [comment]
@zzxwill  we should allow users can only use oam-framework, especially for user who are migrated from oam-runtime
