### ISSUE TITLE
[Feature] Use CUE module to package non-k8s resources

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#662]
Besides Kubernetes resources, it should be possible that we use same mechanism (CUE definition objects) to package any other IaC based capabilities into KubeVela.

For example, Cloud Formation for AWS, Azure Resource Manager for Microsoft, and ROS for Alibaba, and of course Terraform, etc.

This should be the direction we explore.

/cc @zzxwill @hongchaodeng @wonderflow

**Comment by wonderflow** [comment]
According to our new design, cue will be one of the template schematic, so we can define new schematic if we want to add new IaC resources.

For example, we should use hcl for terraform integration

closing
