### ISSUE TITLE
 add usage for Route's parameters

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#672]
## Properties

Name | Description | Type | Required | Default 
------------ | ------------- | ------------- | ------------- | ------------- 
 domain |  Domain name | string | true | empty 
 issuer |  | string | true | empty 
 rules |  | [[]rules](#rules) | false |  

### rules

Name | Description | Type | Required | Default 
------------ | ------------- | ------------- | ------------- | ------------- 
 path |  | string | true |  
 rewriteTarget |  | string | true | empty

**Comment by wonderflow** [comment]
it's added
