### ISSUE TITLE
[Feature] Vela cli for printing generating manifests

### ISSUE THREAD

**Issue by anarcher** [oam-dev/kubevela#674]
**Is your feature request related to a problem? Please describe.**

For use with existing CI/CD solutions (e.g., ArgoCD), Vela CLI requires the ability to return the configuration manifest to stdout or file.
Because `vela up` applies built manifests directly to the cluster, it is difficult to use with argocd or `kubectl apply -f -` or something else.

**Describe the solution you'd like**

`vela export` or `vela build` or `vela show` or `vela up --dry-run`?
I'm not sure exactly which subcommand name is appropriate. :)

**Describe alternatives you've considered**

**Additional context**

**Comment by zzxwill** [comment]
Thanks for describing the feature. Could you please help give an example to help us better understand it? 
BTW, do you think it's better to `vela` directly comparing to `argocd` or `kubectl`? Thanks.

**Comment by hongchaodeng** [comment]
This sounds a good enhancement. In general, `vela` cli already emits deploy.yaml during `up` lifecycle. What we should do is probably output the manifests available into stdout.

I think `vela export --format yaml/json` would be the best choice. The other three doesn't really mean printing the config manifest.

**Comment by hongchaodeng** [comment]
@anarcher 
I have generally make `vela export` work as an Argo plugin with only one yaml generated. But with multiple yamls (AppConfig, Component, Scopes) it would fail. See more details in issue https://github.com/argoproj/argo-cd/issues/4958. Please help with that.
