### ISSUE TITLE
Pull Request Tips：package json is not in GOROOT (/opt/hostedtoolcache/go/1.14.12/x64/src/json) [Question]  why？

### ISSUE THREAD

**Issue by lllwan** [oam-dev/kubevela#692]
![image](https://user-images.githubusercontent.com/32893806/100845270-ee80a580-34b7-11eb-9da7-aa8da737ca3b.png)

**Comment by zzxwill** [comment]
Refer to #691. Please make sure the package `json` has been added in `go.mod`.

**Comment by lllwan** [comment]
> Refer to #691. Please make sure the package `json` has been added in `go.mod`.

Does the built-in package also need to be added?

**Comment by wonderflow** [comment]
```
"encoding/json"
```
