### ISSUE TITLE
volunteered to be a maintainer of kubevela

### ISSUE THREAD

**Issue by sunny0826** [oam-dev/kubevela#693]
@sunny0826 is bootstrap contributors of kubevela, Initiators of the website https://kubevela.io 

volunteer @sunny0826 as maintainer of kubevela，management docs and Installation.

**Comment by wonderflow** [comment]
+1  I'm glad to see @sunny0826  to be a maintainer to maintain our repo and contribute more!

**Comment by resouer** [comment]
+1, thank you for continuous contribution to vela! 

We will also need to publish a blog post for adding new maintainer

/cc @hongchaodeng for review

**Comment by zzxwill** [comment]
+1. Excellent work on KubeVela official site. Thanks. Looking forward to your more contribution to the new Dashboard.

**Comment by hongchaodeng** [comment]
Hi @sunny0826 ,

I would fully support you to become a maintainer. But your contribution so far has not reached a certain level to have impact on any specific component. Comparatively, when @captainroy-hy was [promoted maintainer](https://github.com/crossplane/oam-kubernetes-runtime/issues/219), he has contributed a couple of features and bug fixes to impact the project.

I would like to make the process more transparent and fair to the whole community -- to become a maintainer requires commitment and contribution.

By all means I have seen your commitment to the project. I would highly encourage you to continue working on dashboard component. Once that's done your contribution will be demonstrated as well. At that time I would like to grant you ownership as well.

Thanks for your persistence and hard work!

**Comment by wonderflow** [comment]
closing as @sunny0826  has already be one of the reviewer.
