### ISSUE TITLE
[BUG] You have reached your pull rate limit

### ISSUE THREAD

**Issue by lmxia** [oam-dev/kubevela#695]
**Describe the bug**

the image can't be pulled.
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**To Reproduce**
just `docker pull oamdev/vela-core:latest`

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

as descirbed: https://www.docker.com/increase-rate-limits, the docker hub set limit to the accont.

**Comment by wonderflow** [comment]
This is not kubevela's issue, it's because docker hub policy.

You can use github container registry instead, we also provide images there:

```
docker pull ghcr.io/oam-dev/kubevela/vela-core:latest
```

**Comment by wonderflow** [comment]
@lmxia please help close this issue if the alternative registry could work
