### ISSUE TITLE
[Question] how about add a change log file for each release

### ISSUE THREAD

**Issue by shaobo322** [oam-dev/kubevela#734]

**Comment by wonderflow** [comment]
Can you descirbe more detail about the workflow?

**Comment by hongchaodeng** [comment]
Hi @shaobo322

That's a good point!

Currently KubeVela is under heavy development. Releases roll out frequently and our developers work closely together on Ding Group. Our roadmap is also a big one which includes major features across releases.

Once hitting BETA KubeVela would have more formal release process including roadmap and changelog for each release.

**Comment by wonderflow** [comment]
Closing, we will add a breif release note. Thanks for reminding.
