### ISSUE TITLE
[Question] Vela cli supports running on anywhere

### ISSUE THREAD

**Issue by Cweiping** [oam-dev/kubevela#751]
**Is your feature request related to a problem? Please describe.**

I found that `Vela cli` can only run on the node of install, and cannot be used in another node.

**Describe the solution you'd like**

For this, I think it should be worth fixing, like `helm V3` or `kubectl` relying only on `kubeconfig`. Or am I using it the wrong way?
**Describe alternatives you've considered**

I suggest that you move these contents to `Secrets` under `Namespace/vela-system`.
```shell
[root@10-6-125-10 .vela]# tree *
capabilities
├── autoscale.cue
├── metrics.cue
├── rollout.cue
├── task.cue
├── webservice.cue
├── worker.cue
└── workloads
    ├── task
    ├── webservice
    └── worker
centers
curenv [error opening dir]
deploy.yaml [error opening dir]
envs
└── default
    ├── applications
    │   └── first-vela-app.yaml
    ├── config.json
    └── configs
```

**Additional context**

**Comment by wonderflow** [comment]
I agree, these information can be stored in serverside, but they should not be strong rely on K8s.

All storage should be alternative.

1. (The current working way) Standalone mode, use local file system to store metadata.
2. K8s Storage Mode: use K8s CRD or just use `Configmap/Secret`.
2. DB Stroage Mode: use a DB like mysql

**Comment by Cweiping** [comment]
Similar to the implementation of `helm`，support four ways to store`Release` related information. https://github.com/helm/helm/tree/master/pkg/storage/driver

If there are details, I am willing to participate in implementing it.

**Comment by wonderflow** [comment]
Glad to hear that. The first thing is we should implement the interface layer. @resouer @hongchaodeng @ryanzhang-oss  Do you have more information for this?

**Comment by resouer** [comment]
+1000 on decoupling all vela user interfaces from target cluster and I personally think the helm storage concept is great.

We can start from two modes maybe? 1. Kubernetes mode which will require a kubeconfig (either local or remote) 2. Local mode (we can choose from local file or embedded sql ).

This feature will also needed for https://github.com/oam-dev/kubevela/issues/759, i.e. we want to deploy KubeVela model layer itself anywhere.

**Comment by wonderflow** [comment]
@Cweiping  You could draft the interface layer implementation if you want.

**Comment by Cweiping** [comment]
> @Cweiping You could draft the interface layer implementation if you want.

OK.
/assign （not working!!!）

**Comment by Cweiping** [comment]
1. Add [storage common interface](https://github.com/oam-dev/kubevela/blob/master/pkg/appfile/storage.go)
2. Support storage type configuration, use the environment variable of `STORAGE_DRIVER` and `--storage-driver` flags to modify the storage type and use `Local` by default. [Reference code](https://github.com/oam-dev/kubevela/tree/master/pkg/appfile/driver).Example: `Local` or `ConfigMap`
