### ISSUE TITLE
K8S service and ingress not create

### ISSUE THREAD

**Issue by lklkxcxc** [oam-dev/kubevela#755]
**Describe the bug**

**To Reproduce**

1. vela.yaml:
```
name: diff-database

services:
  diff-database:
    # this image will be used in both build and deploy steps
    image: harbor.test.cn/daq/cechealth-daq-tools-mysqldiff:latest
    config: prod

    # build:
      # Here more runtime specific build templates will be supported, like NodeJS, Go, Python, Ruby.
      # docker:
        # file: Dockerfile
        # context: .

      # Uncomment the following to push to local kind cluster
      #push:
        #local: cechealth

    # type: webservice (default) | worker | task

    #cmd: ["node", "server.js"]
    port: 8080

    scaler:
       replicas: 1

    route:
      domain: diff.cechealth.cn
      rules:
        - path: /
    #     rewriteTarget: /
```
2. vele up success
3.kubectl get svc and kubectl get ingress is none
4.vela status diff-database --svc diff-database
```
About:

  Name:         diff-database                          
  Namespace:    default                                
  Created at:   2020-12-09 15:17:21.016677214 +0800 CST
  Updated at:   2020-12-09 15:17:21.016677433 +0800 CST

Services:

  - Name: diff-database
    Type: webservice
    HEALTHY Ready:1/1 
    Traits:

    Last Deployment:
      Created at: 2020-12-09 15:01:45 +0800 CST
      Updated at: 2020-12-09T15:17:21+08:00
```
6. vela traits
```Error: capability 'rollout' was not ready: no matches for flagger.app/, Resource=canaries ```

**Expected behavior**

**Screenshots**

**Cluster information**

Vela Version:0.1.2
Kubernetes Version :1.16.4
**Additional context**

**Comment by wonderflow** [comment]
> Error: capability 'rollout' was not ready: no matches for flagger.app/, Resource=canaries

It means the dependency is still installing, maybe wait a few more time and re-try `vela traits`

After `vela traits ` works, try `vela up` again then you will create ingress successfully.

This issue remind us that we should block `vela up` to run before `vela traits` success.

**Comment by resouer** [comment]
And the messaging is misleading in this log.

**Comment by lklkxcxc** [comment]
@wonderflow
