### ISSUE TITLE
[question] Can‘to join to slack

### ISSUE THREAD

**Issue by Cweiping** [oam-dev/kubevela#760]
**Describe the bug**
https://cloud-native.slack.com/archives/C01BLQ3HTJA
I was not invited to join the working group.

**To Reproduce**

**Expected behavior**

For example: 

http://slack.k8s.io/  

 Join me on Slack — it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/cloud-nativeworld/shared_invite/zt-jri61dkn-xfuUkE1vV8NgNSuA~xBjXA

But the slack invitation link has an expiration time limit, which should be the reason for k8s reverse generation。
<img width="499" alt="invitationlink" src="https://user-images.githubusercontent.com/33973679/101713099-e9cc7a80-3ad1-11eb-9429-d78e153a45a6.png">

**Screenshots**

**Cluster information**

**Additional context**

**Comment by resouer** [comment]
@Cweiping Are you able to find #kubvela channel in CNCF slack? That's the working group.

**Comment by Cweiping** [comment]
OK, It does exist. It is suggested to update the process.
[CNCF Slack](https://slack.cncf.io/) #kubevela channel

https://github.com/cncf/sig-security#communications
