### ISSUE TITLE
[Feature]Integrate swagger

### ISSUE THREAD

**Issue by majian159** [oam-dev/kubevela#763]
Add this feature to ensure the sync of code and api documents.

**Comment by zzxwill** [comment]
@majian159 To help others better understand the feature, please elaborate the feature description. Thanks.

On my side, I support this feature. I spent much time on the old r[estful api doc](https://github.com/oam-dev/kubevela/blob/master/design/api/vela-restful-api-reference.md) and it will be easy to become out-of-date.

**Comment by hongchaodeng** [comment]
fixed by #764
