### ISSUE TITLE
Restful API status tracking issue

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#772]
There has been discussions about using Restful API to interact with Vela. On the main track, we have been building and exposing rest API to support UI components. Here I create this issue to demonstrate how to use it and collect feedback if anyone wants anything.

## Swagger Doc

Currently the rest API  documentation are automatically generated via [swaggo](https://github.com/swaggo/swag). It is available in [pkg/server/docs/swagger.json](https://github.com/oam-dev/kubevela/blob/master/pkg/server/docs/swagger.json).

If you make any changes to the API, just run in the project dir:
```
make swagger-gen
```

## Exposed Endpoints

There is a Vela backend to serve rest endpoints. To deploy it, you have two options:
```
vela dashboard
```
Or in the project dir:
```
make start-dashboard
```

The swagger UI endpoint is available at `/swagger/index.html`:

<img width="704" alt="swagger" src="https://user-images.githubusercontent.com/920884/102132043-f4f01500-3e07-11eb-9442-6df98fe32ebd.png">

You can get the swagger json at `/swagger/swagger.json` to discover all exposed endpoints.

**Comment by ryanzhang-oss** [comment]
We need to move the RESTful service to the server side
