### ISSUE TITLE
[Bug] The manually added detail explanation of rollout trait is overriden

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#777]
**Describe the bug**

The generated ref doc is great, though it will override the manually added detail explanation of rollout trait, i.e.: https://github.com/oam-dev/kubevela/blob/efb76ee5ee16a09aaba4b4e612b3165436852e0e/docs/en/developers/references/traits/rollout.md#how-rollout-works

We need to improve the doc gen, or move that section to somewhere else (for example, the user doc of rollout).

**Comment by zzxwill** [comment]
I moved the special part of rollout `Conflicts With` and `how-rollout-works` to the design section https://github.com/oam-dev/kubevela/blob/master/design/vela-core/rollout.md.

**Comment by resouer** [comment]
@zzxwill It's not correct to me, all those information are not design doc, especially the conflictsWith section. They are part of user facing doc.

Doc gen should come from the whole definition object. For example, including description, conflictsWith, appliesTo etc. The how-to section could be a link to a separate file under same dir. 

Please revise this issue or handle them manually for now.
