### ISSUE TITLE
[Feature]Time use RFC3339 form and is in UTC

### ISSUE THREAD

**Issue by majian159** [oam-dev/kubevela#782]
**Is your feature request related to a problem? Please describe.**
The current time format is confusing, and javascript date not compatible.  
ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
```javascript
new Date("2020-12-17 15:54:02 +0800 CST")
"Fri Dec 18 2020 05:54:02 GMT+0800 (中国标准时间)"
```

**Describe the solution you'd like**
use RFC3339 and UTC

**Describe alternatives you've considered**
```go
appConfig.CreationTimestamp.UTC().Format(time.RFC3339)
// replace
applicationMeta.CreatedTime = appConfig.CreationTimestamp.String()
```

**Additional context**

**Comment by hongchaodeng** [comment]
Which API endpoints dd you hit this problem?

**Comment by majian159** [comment]
> Which API endpoints dd you hit this problem?
> 
> 

like application list "/api/env/{env}/apps"
