### ISSUE TITLE
The error message during installation is misleading

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#783]
**Describe the bug**

This error message during installation is misleading:
```
Error: capability 'rollout' was not ready: no matches for flagger.app/, Resource=canaries
```

**To Reproduce**

**Expected behavior**

```
Warning: installing capability 'rollout' ... expected provider: flagger.app/, Resource=canaries
```

and timeout if capability installation fail after certain time (let's say `30m`).

**Screenshots**

**Cluster information**

**Additional context**

**Comment by zzxwill** [comment]
In fact, @wonderflow removed `Error` from the installation error message by printing it via `isStreams.Info` at https://github.com/oam-dev/kubevela/pull/637/files#diff-e2bac7c400ef955a432ad1b32b6f241344b8ba98b18ddbd219ca3fd4c176a1a9R159-R160.
So I just refined the error message, increased timeout to 5 minutes from 2 minutes to allow more time for controllers to get ready, and did some code refactoring.
