### ISSUE TITLE
[Feature] The Appfile supports `backend` or called `driver`, such as etcd, mysql

### ISSUE THREAD

**Issue by LeoLiuYan** [oam-dev/kubevela#788]
**Is your feature request related to a problem? Please describe.**

When deploying multiple Vela as restful servers,  the Appfile requires shared storage. The `Capability` and `Center` should also share same storage.

**Describe the solution you'd like**

The Appfile struct support `backend` or  called `driver` field, which is a interface type.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Closing as it's dup with #789
