### ISSUE TITLE
[Feature] Sync kubevela api types to a separate repo

### ISSUE THREAD

**Issue by LeoLiuYan** [oam-dev/kubevela#793]
**Is your feature request related to a problem? Please describe.**

When use kubevela to build private `PaaS` platform,  we need import kubevela api types. So, it's better to sync kubevela api types to a separate repo just like kubernetes do to avoid import all kubevela packages into private project. If a project import all kubevela packages may cause  version conflicts.

**Describe the solution you'd like**

Sync kubevela api types to a separate repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Hi, @LeoLiuYan  Thanks for your advice. I have created https://github.com/oam-dev/kubevela-core-api for this use case. 

Feel free to reopen this issue if there's still any probelm.

**Comment by LeoLiuYan** [comment]
Could `kubevela-core-api` repo also include `kubevela/apis/types` package which define the `Capability` object?

**Comment by LeoLiuYan** [comment]
@wonderflow

**Comment by wonderflow** [comment]
@LeoLiuYan already included

**Comment by LeoLiuYan** [comment]
Oh... I missing it. 

Thanks.
