### ISSUE TITLE
Fail to run `vela install`

### ISSUE THREAD

**Issue by webup** [oam-dev/kubevela#794]
**Describe the bug**

After running `vela install`, we got following errors:

```
- Installing Vela Core Chart:
install chart vela-core, version v0.2.1, desc : A Helm chart for Kube Vela core, contains 36 file
Failed to install the chart with error: MutatingWebhookConfiguration "mutating-webhook-configuration" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kubevela"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "vela-system"
rendered manifests contain a resource that already exists. Unable to continue with install
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/runner/go/pkg/mod/helm.sh/helm/v3@v3.2.4/pkg/action/install.go:274
github.com/oam-dev/kubevela/pkg/commands.InstallOamRuntime
	/home/runner/work/kubevela/kubevela/pkg/commands/system.go:259
github.com/oam-dev/kubevela/pkg/commands.(*initCmd).run
	/home/runner/work/kubevela/kubevela/pkg/commands/system.go:162
github.com/oam-dev/kubevela/pkg/commands.NewInstallCommand.func2
	/home/runner/work/kubevela/kubevela/pkg/commands/system.go:119
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/runner/work/kubevela/kubevela/cmd/vela/main.go:16
runtime.main
	/opt/hostedtoolcache/go/1.14.13/x64/src/runtime/proc.go:203
runtime.goexit
	/opt/hostedtoolcache/go/1.14.13/x64/src/runtime/asm_amd64.s:1373
Error: rendered manifests contain a resource that already exists. Unable to continue with install: MutatingWebhookConfiguration "mutating-webhook-configuration" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "kubevela"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "vela-system"
```

**To Reproduce**

**Expected behavior**

`vela install` could success.

**Screenshots**

**Cluster information**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Here is current helm version info:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

**Comment by captainroy-hy** [comment]
@webup `vela install` will try to install a helm chart, as shown [here](https://github.com/oam-dev/kubevela/blob/fbe93dc847b8127bc06f9e26c2882190363844ac/charts/vela-core/templates/webhook.yaml#L6), a MutatingWebhookConfiguration is included in the chart.  According to your error log, there already existing a MutatingWebhookConfiguration named "mutating-webhook-configuration" installed in your cluster. You may have to delete that conflict resource before re-run `vela install`.

**Comment by captainroy-hy** [comment]
@wonderflow Since "mutating-webhook-configuration" and "validating-webhook-configuration" are pretty frequently-used names, to avoid conflicts during installing helm chart, maybe we can use kubevela-specific names, e.g., "mutating.webhook.kb.io", "validating.webhook.kb.io".

**Comment by wonderflow** [comment]
@captainroy-hy  yes, please naming it `kubevela-mutating-webhook-configuration`, add a `kubevela-` prefix for both.  Would you like to fix?

**Comment by captainroy-hy** [comment]
> @captainroy-hy yes, please naming it `kubevela-mutating-webhook-configuration`, add a `kubevela-` prefix for both. Would you like to fix?

Sure, let me fix it.

**Comment by webup** [comment]
> @webup `vela install` will try to install a helm chart, as shown [here](https://github.com/oam-dev/kubevela/blob/fbe93dc847b8127bc06f9e26c2882190363844ac/charts/vela-core/templates/webhook.yaml#L6), a MutatingWebhookConfiguration is included in the chart. According to your error log, there already existing a MutatingWebhookConfiguration named "mutating-webhook-configuration" installed in your cluster. You may have to delete that conflict resource before re-run `vela install`.

Got u, thx~

**Comment by wonderflow** [comment]
@zzxwill  please help add it to FAQ, thanks !

**Comment by webup** [comment]
Btw, we've found the conflict was introduced by KubeSphere DevOps system, since we need that system we are looking forward to the above mentioned patch, thanks.

**Comment by captainroy-hy** [comment]
@webup Yep, the change is already merged along with #781

**Comment by zzxwill** [comment]
> @zzxwill please help add it to FAQ, thanks !

@webup Would you like to contribution this case to FAQ https://github.com/oam-dev/kubevela/blob/master/docs/en/developers/references/devex/faq.md?

**Comment by zzxwill** [comment]
Added this case in FAQ https://github.com/oam-dev/kubevela/pull/831.
