### ISSUE TITLE
[Feature] Integration with developing time

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#795]
**Is your feature request related to a problem? Please describe.**

Developing micro services is also challenging.

**Describe the solution you'd like**

Have a integration with Tilt: https://github.com/tilt-dev/tilt

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Yes, the idea is interesting, we can easily contribute vela as a tilt-extension. But it's hard to show what's the value of kubevela if users are already using tilt.

vela and tilt are very similar in deveper interface. If user uses tiltfile, they won't want to learn appfile. If we give up appfile and directly use tiltfile, It's hard to show using vela is better than using K8s. The complexity of K8s can be easily hidden by tilt-extension.

**Comment by wonderflow** [comment]
Let's hold until we have more Capability such as rolling update with traffic management.

**Comment by wonderflow** [comment]
[Nocalhost](https://github.com/nocalhost/nocalhost) is also an option to integrate, it's a developing tool similar with tilt.

**Comment by wonderflow** [comment]
Let's re-visit this issue, I think it's a good time to integrate tilt with KubeVela now.

Developing tools such as Tilt and Nocalhost can help users using KubeVela easily by integrate with IDE doing local development. By using KubeVela, users can have a consistent experience from local development, testing to production deploy. The same KubeVela application yaml with components/traits/workflow specified can work in all these environments.

So what's benifit for users who are already using tilt to manage K8s resources?

1. KubeVela can help launch an environment very easily. The environment includes a new K8s cluster, cloud resources or anything that need to be prepared previously.
2. KubeVela has a very good workflow mechanism, it can help developers to manage dependencies, especially for micro services. The developer may need to setup a lot of microservices that was maintained by other teams. With the help of KubeVela, these dependency and resources lifecycle  can be managed easily with only one KubeVela application yaml.
3. One KubeVela  application can orchestrate and manage as many K8s resources as you need, you can bundle them as a whole in one application yaml.
4. KubeVela has lots of operational management capabilities, such sa rollout, traffic management, etc.. These capabilities can help developers to test the real production deployment.

**Comment by Lakshya8066** [comment]
Hey @wonderflow, this seems pretty interesting! I would like to work on it. Could you guide me where to start from?

**Comment by wonderflow** [comment]
I suggest these steps:

1. Get familiar with what KubeVela and tilt is. Read docs of both projects.
2. Deploy KubeVela by using kind or minikube, run application.
3. Try write a tilt plugin to integrate with KubeVela.

The final goal is users using tilt developing with a KubeVela application yaml locally and any change could deployed in the K8s cluster and preview.

**Comment by MarcaWitt** [comment]
@wonderflow I would like apply for this project under the LFX mentorship program. I have read the previous comments and the requirements you mentioned. Looking forward to it.

**Comment by wonderflow** [comment]
@Lakshya8066 @MarcaWitt  Thanks for your interest, you could write a proposal for your plan on this issue.

**Comment by Lakshya8066** [comment]
Thank you @wonderflow. I am working on that.

**Comment by MarcaWitt** [comment]
thank you @wonderflow.I am working on that too.

**Comment by kaustubhsharma-009** [comment]
The issue looks pretty interesting. I have a few ideas regarding the same based on whatever I have worked on or have some experience about. I'd like to apply for this project under LFX if possible. Hope I get the opportunity 
Thanks!!

**Comment by wonderflow** [comment]
@kaustubhsharma-009  Sure, you're welcome and please send your proposal here.

**Comment by MarcaWitt** [comment]
@wonderflow  sorry teacher,I have submitted the proposal to LFX.

**Comment by kaustubhsharma-009** [comment]
I had submitted my proposal along with a cover letter on the LFX mentorship application @wonderflow 
Thanks!

**Comment by wonderflow** [comment]
ref #2577 #2545
