### ISSUE TITLE
[Feature] route trait 

### ISSUE THREAD

**Issue by huolunl** [oam-dev/kubevela#806]
Can you support a service with multiple domains, when I use route traits

**Comment by wonderflow** [comment]
Can you clarify your use case?

**Comment by huolunl** [comment]
`name: nginx
services:
  nginx:
    type: webservice
    image: nginx:1.8
    port: 80
    route:
      domain: www.nginx.com`


There's an example where I can visit my nginx  through www.nginx.com, Now I'd like to add an extra domain to my nginx as well, route trait don't support it now

**Comment by wonderflow** [comment]
In your case, the nginx is not an App, it's API-Gateway. This should use api-gateway as a capability instead of an app. We will consider support api-gateway in the near future.

**Comment by huolunl** [comment]
I just accidentally wrote a nginx。 Actually I need an app with multiple domain

**Comment by wonderflow** [comment]
@huolunl Why do your  app need two domain?

**Comment by wonderflow** [comment]
We can add K8s nginx as a trait, and set conflictWith field with route trait. So you will be able to use multiple domain route by raw ingress.

**Comment by wonderflow** [comment]
This issue can be resolved now, you can define a customized ingress trait by using cue @huolunl 

please read the doc: 

https://kubevela.io/#/en/platform-engineers/advanced-cue?id=trait-generate-multiple-resources
