### ISSUE TITLE
Application CRD should have basic schema

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#829]
**Describe the bug**

The current Application CRD is a raw extension type, this seems not correct to me.

Application CRD is designed as the application definition and a "framework" to assemble capability abstractions into an app. Think about how you will define its schema if you are reinventing Component + ApplicationConfiguration. /cc @wonderflow . It's basically a embedded version of Comp + AppConfig, w/o datainput/output.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
Yes, I will refactor the current structure before taking it in real usage by using it in `vela up`.
