### ISSUE TITLE
[Feature] IngressClass  support for route

### ISSUE THREAD

**Issue by Incubator4th** [oam-dev/kubevela#849]
Environment: RKE 1.19.2 with traefik v2.2 as ingress controller

Well,in the process of referring to the installation guide, some problems were encountered.

Which is the same issue with #632 

After a series of problem diagnosis,I found that the route trait create ingress with annotations `kubernetes.io/ingress.class=nginx`,but I used traefik, this is why this service is pending and route got timemout.

Later, after researching, I understood how resources are called by chain.

`Vela.yml route ->  route of TraitDefinition.core.oam.dev/v1alpha2 ->  Route.standard.oam.dev/v1alpha1`

Well I know that I can define my own parameter using TraitDefinition for another ingress or others.But problem is in offical route traitdefinition,it should support ingressclass to set which ingress controller shound use.

Such as:

```yaml
services:
  web:
    route:
      ingressclass: nginx
```

and then auto add annotation `kubernetes.io/ingress.class`

**Comment by wonderflow** [comment]
Thanks for your advice. I totally agree the `ingressclass` could be an option(with default value 'nginx'), would you like to send a PR for it? @Incubator4th

**Comment by Incubator4th** [comment]
> Thanks for your advice. I totally agree the `ingressclass` could be an option(with default value 'nginx'), would you like to send a PR for it? @Incubator4th

Thanks for appreciation.It's interest to modify by myself. 

Before doing that,in my understanding, add parameter ingressclass requires modify crd define yaml , main controller and trais crd value. It would has a chain change.And I would like to try it.

By the way,on the one hand this project kubevela aims to let  developers to understand kubernetes less.
But on the other hand, inevitably,some services need tcp or udp port,and what follows is the need to define service type like clusterIP.

I'm not sure if this is against the purpose of the project,cause of just like docker-compose have port mapping.

Can ask about the development route in this regard ?

**Comment by wonderflow** [comment]
Hi, @Incubator4th  really good thoughts! Thanks.

> kubevela aims to let developers to understand kubernetes less.

Yes, so we use WorkloadDefinition/TraitDefinition along with cuelang template to help reduce the complexity. 

>  inevitably,some services need tcp or udp port,and what follows is the need to define service type like clusterIP.

Yes. This requires the platform to have enough extensibility. With the help of kubevela, you can easily change the Workload/TraitDefinition of define a new one to meet the requirement.
 
>  Can ask about the development route in this regard ?

If you are saying KubeVela, you can view [our roadmap](https://github.com/oam-dev/kubevela/projects/1) . The main purpuse is 1) give platform builder good framework to build PaaS; 2) give end user developers good experience to run apps.

If you are saying the route trait controller, we build it just beacuse the ingress and k8s service can't meet our full requirements while there're so many ingress solutions with different spec. We need a more clean spec. But I have to say it's not mature and we need users to give feedback just like this issue.

**Comment by Incubator4th** [comment]
@wonderflow I agree with point  `the ingress and k8s service can't meet our full requirements`.One controversial function is path rewrite,which is not a standard function in ingress controller.In vela file,it called `rewriteTarget`.

In fact,different ingress controller have different implementations.But it doesn't have a standard configuration as ingressclass.
Which configuration in nginx use special annotations and others may not.

I thought it would be a important point, and I wish both kubernetes and kubevela cound be better
