### ISSUE TITLE
[Feature] Package mgmt should be a must have for app engine

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#85]
As the title said.

The package should be discoverable by CRD and automatically installation is a must have.

If helm can be used to solve this, we use it; if it's flaw, we create our own.

**Comment by wonderflow** [comment]
Currently, we already support `install helm` in definition.

And in our design, we will finally use a CRD Registry plugin https://github.com/oam-dev/kubevela/blob/master/DESIGN.md#solution-1

So let's close it.
