### ISSUE TITLE
[Feature] improve the way AppConfig handle workloads changed by others

### ISSUE THREAD

**Issue by captainroy-hy** [oam-dev/kubevela#865]
A workload is rendered and created in AppConfig controller. After the workload is created in the cluster, AppConfig controller will reconcile it periodically to make it matching the desired state.

Besides AppConfig controller, there are other two kinds of controllers, workload controllers and trait controllers, with interest in workloads. They are both possible to change the state of workloads in the cluster, namely, to break the state expected by AppConfig controller. To avoid making conflicting decisions on workloads, it's necessary for the builders of workload/trait controllers to be clear with how AppConfig reconciles workloads.

Currently, AppConfig controller uses `Patch` method to update the workloads: the patch type is  `application/merge-patch+json` and the patch data is the whole workload object the same as the one it's created. As a result of no diff calculation, AppConfig controller cannot remove the fields that are not included in the original workload object. 
For example, below workload object is created by AppConfig controller. 
```yaml
spec:
  f1: v1
  f2: v2
```
Afterward, a trait controller changed it into below.
```yaml
spec:
  f1: vX # change value of f1
  # remove f2
  f3: v3 # add f3
```
Then AppConfig controller will change it into below in the following round of reconciliation.
```yaml
spec:
  f1: v1 # revert value of f1
  f2: v2 # restore f2
  f3: v3 # still retain f3
```
- For changed fields like f1, AppConfig controller will replace the changed value with the original one, no matter it's a normal JSON object or array type object.
- For removed fields like f2, AppConfig controller will revert it.
- For latter-added fields like f3, AppConfig controller has NO way to handle them now.

For latter-added fields, the same situation also happened to trait but it's fixed through replacing `Patch` with `Update`, related [issue ](https://github.com/crossplane/oam-kubernetes-runtime/issues/272) and [PR](https://github.com/crossplane/oam-kubernetes-runtime/pull/283).

If we allow others except AppConfig controller to changed the state of workloads, especially the spec, how does AppConfig controller handle those latter-added fields?

**Comment by captainroy-hy** [comment]
Currently, if controllers except AppConfig controller changed the configuration of a workload, it depends on whether the changed fields are touched by workload renderer. 
If touched, AppConfig controller will revert it. 
If not touched, AppConfig controller has no effect on it.  Furthermore, even if AppConfig spec is changed later, AppConfig controller cannot revert previous changes either. But users may expect AppConfig controller to "gc" those changes, e.g., a trait is removed from the AppConfig spec, accordingly, changes the trait controller brought are supposed to be reverted.

Here's a proposal for AppConfig applying mechanism.
It allows users to choose a specific mechanism while starting up an AppConfig controller. That may help users and workload/trait controllers to reach a consensus on the behavior of AppConfig controller.

| mode                  | reconcile (no spec change)                            | spec changed          | Privileges of other controllers                                                                   |
|-----------------------|-------------------------------------------------------|-----------------------|----------------------------------------------------------------------------|
| strict                | use `Update` to apply workloads/traits                | use `Update` to apply | Not allow to change ANY configuration of workloads/traits                  |
| default               | use `Patch` to apply workloads/traits                 | use `Update` to apply | Only allow to change the configuration that is not touched by renderer     |
| apply-once-only       | skip applying after created, create if deleted        | use `Update` to apply | Allow to change any configuration but not allow to delete workloads/traits |
| apply-once-only-force | skip applying after created, skip creating if deleted | use `Update` to apply | Allow to change any configuration or delete workloads/traits               |

**Comment by ryanzhang-oss** [comment]
I wonder when does a trait need to "remove" a field from the workload? This seems to be a rather rare case.

**Comment by ryanzhang-oss** [comment]
On a different note, it seems there should be some way for the component/workloadDefinition to indicate what fields can be changed and what fields are immutable. The render should maintain those immutable ones in the reconciliation loop and leave the other fields alone.

**Comment by captainroy-hy** [comment]
> I wonder when does a trait need to "remove" a field from the workload? This seems to be a rather rare case.

trait rarely needs to remove a field but is possible to add a field. e.g., VolumeMount trait has to add Volumes field to the workload.

**Comment by wonderflow** [comment]
> VolumeMount trait has to add Volumes field to the workload. If the trait is removed, currently, there's no way to remove the Volumes field it added.

I think the trait controller can use finalizer mechanism, if it was removed, the finalizer should clean the fields added to workload.

**Comment by wonderflow** [comment]
> Currently, if controllers except AppConfig controller changed the configuration of a workload, it depends on whether the changed fields are touched by workload renderer.
> If touched, AppConfig controller will revert it.
> If not touched, AppConfig controller has no effect on it. Furthermore, even if AppConfig spec is changed later, AppConfig controller cannot revert previous changes either. But users may expect AppConfig controller to "gc" those changes, e.g., a trait is removed from the AppConfig spec, accordingly, changes the trait controller brought are supposed to be reverted.
> 
> Here's a proposal for AppConfig applying mechanism.
> It allows users to choose a specific mechanism while starting up an AppConfig controller. That may help users and workload/trait controllers to reach a consensus on the behavior of AppConfig controller.
> 
> mode	reconcile (no spec change)	spec changed	Privileges of other controllers
> strict	use `Update` to apply workloads/traits	use `Update` to apply	Not allow to change ANY configuration of workloads/traits
> default	use `Patch` to apply workloads/traits	use `Update` to apply	Only allow to change the configuration that is not touched by renderer
> apply-once-only	skip applying after created, create if deleted	use `Update` to apply	Allow to change any configuration but not allow to delete workloads/traits
> apply-once-only-force	skip applying after created, skip creating if deleted	use `Update` to apply	Allow to change any configuration or delete workloads/traits

We have merged 3-way-merge patch now, this is not correct any more.

**Comment by wonderflow** [comment]
I mark this issue as `wontfix`, the appconfig controller should not change the fields managed by others.

**Comment by captainroy-hy** [comment]
> I mark this issue as `wontfix`, the appconfig controller should not change the fields managed by others.

Agreed!  Closed since current appconfig already works as expected.
