### ISSUE TITLE
[Feature]Generate Kubernetes resource yaml from vela cli with appfile

### ISSUE THREAD

**Issue by Incubator4th** [oam-dev/kubevela#866]
During trying to use vela with CI/CD pipeline.We found that vela file might not be friendly to customize.Although just do something like add label or annotations,replace image tag,which is easy for kustomize.

I know these are different,and vela is not a tool for CICD.With communication in gitter,I got that appfile have equivalent Applications CRD.

One thing is that,should cli tool have command to trans appfile to Application yaml,just like kustomize.For Example:
```bash
vela build -f vela.yaml
```
and output 
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
spec:
  components: []
```

that can be used by kubectl like this:
`vela build -f vela.yaml | kubectl apply -f -`

I notice that file `pkg/controller/core.oam.dev/v1alpha2/application/parser/service.go` in line 165 has one function to trans Application into Appfile
```go
func (pser *Parser) Parse(name string, app *v1alpha2.Application) (*Appfile, error) {

	appfile := new(Appfile)
	appfile.name = name
	var wds []*Workload
	for _, comp := range app.Spec.Components {
		wd, err := pser.parseWorkload(comp)
		if err != nil {
			return nil, err
		}
		wds = append(wds, wd)
	}
	appfile.services = wds

	return appfile, nil
}
```
and it should be reversible to trans Applicaiton file back.Just like
```go
func (pser *Parser) Unparse(appfile *Appfile) (*v1alpha2.Application, error)  {}
```

~~And advance problem is that,can applicaiton CR trans to atomic resource.For offical example,it can be generated into deployment,service,ingress,or only get Route CRD and deployment cause of route parameter trans to Route CRD.~~

**Comment by resouer** [comment]
@Incubator4th Hi, check out `vela export` command ^^

Note that it is still WIP to make appfile rendered into `Application`: https://github.com/oam-dev/kubevela/pull/846, so for now, `vela export` will only export `Component` + `AppConfig` objects instead.

**Comment by Incubator4th** [comment]
@resouer well,I have seen and I tried `vela export`,it works as reported.But I wonder why not use `Application` object rather and `Component` + `AppConfig` objects,cause of one object is easy to mange.

Or it haven't been implemented yet,is there a plan to export `Applicaiton` resource,and even make appfile and Applicaiton related?

Well,I noticed that in function `Reconcile` of  Applicaiton Controller file.`Application` reousrce trans to `appfile` object first,then trans `appfile` to `Component` and `AppConfig`.Is it designed to be like this,or it can be optimized,and I still think that one `appfile` corresponds to one `Application` is a good idea.

**Comment by resouer** [comment]
@Incubator4th Sorry, just didn't fully get your point. The PR #846 I linked in previous comment is exactly rendering Appfile to Application CRD (as its title said).

**Comment by Incubator4th** [comment]
@resouer I've seen,but it seem not ready yet. And would `vela export` export `Application` ? Cause of manage one object is easier.

**Comment by resouer** [comment]
@Incubator4th Yes, the intention of PR #846  is exactly as what you mentioned (use Application CRD to replace C/AC as the app descriptor).  

Btw, welcome send a PR to update `$vela export` command after #846 is merged ^^

**Comment by Incubator4th** [comment]
@resouer whatever,I wish I can help after I totally read about that part of PR #846

**Comment by resouer** [comment]
@Incubator4th Note that PR #846 has been merged and the `Application` object is now online. Feel free to give it a try and let us know the feedback.

/cc @wonderflow to check if this issue is fully fixed by now.

**Comment by wonderflow** [comment]
I think it has been done, you could try `vela export` by using the master branch. @Incubator4th
