### ISSUE TITLE
[Feature] Refactor vela cli to interact with Application instead of AppConfig and Component

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#877]
Now we have successfully built `Application` Object which has done most appfile logic in controller. Our CLI should work with the Application object instead of AppConfig and Component.

## Commands should be refactored

- [x]     init   	Create scaffold for an application
- [x]     delete APP_NAME                           	Delete an application  @zzxwill 
- [x]     exec [flags] APP_NAME -- COMMAND [args...]	Execute command in a container
- [x]     logs                                      	Tail logs for application
- [x]     ls                                        	List services of all applications
- [x]     port-forward APP_NAME                     	Forward local ports to services in an application
- [x]     status APP_NAME                           	Show status of an application, including workloads and

## Commands should be deprecated

we should use appfile instead of these commands.

- [x] vela svc deploy
- [x] vela route APP_NAME
- [x] vela scale APP_NAME
- [x] vela metrics APP_NAME
- [x] vela rollout APP_NAME

**Comment by captainroy-hy** [comment]
/assign
- [ ]  exec [flags] APP_NAME -- COMMAND [args...] Execute command in a container
- [ ]  logs Tail logs for application
- [ ]  port-forward APP_NAME Forward local ports to services in an application

**Comment by TomorJM** [comment]
/assign

- [ ] status APP_NAME Show status of an application, including workloads and traits

**Comment by LeoLiuYan** [comment]
/assign

*[] ls List services of all applications
*[] show APP_NAME Show details of an application

**Comment by LeoLiuYan** [comment]
/assign

* [ ]  ls List services of all applications
* [ ]  show APP_NAME Show details of an application

**Comment by wonderflow** [comment]
@LeoLiuYan  Hi, are you still working on this? We have made `vela show ` command to print how traits and workloads schema is, so don't do this command any more, thanks!

**Comment by LeoLiuYan** [comment]
> @LeoLiuYan Hi, are you still working on this? We have made `vela show ` command to print how traits and workloads schema is, so don't do this command any more, thanks!

Got it. Yes, I am still working on this.

**Comment by wonderflow** [comment]
@LeoLiuYan @captainroy-hy Hi，any progress on this issue？
