### ISSUE TITLE
Have an automatic way to sync KubeVela with oam-runtime repo

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#883]
Currently the Vela repo has OAM Runtime which is forked from https://github.com/crossplane/oam-kubernetes-runtime and not synced with it automatically.

As we are having more OAM runtime features and bug fixes, like https://github.com/crossplane/oam-kubernetes-runtime/issues/272 and https://github.com/crossplane/oam-kubernetes-runtime/pull/317/, we need to either implement twice or  have diverged OAM runtimes.

Raise this issue to discuss an automatic way to sync KubeVela with oam-runtime repo.

**Comment by wonderflow** [comment]
I don't think there's any easy way to sync, I hope we implement new feature in kubevela only and keep the bugfix synced manually

**Comment by wonderflow** [comment]
Will not sync, and now oam-k8s-runtime was contained in KubeVela.
