### ISSUE TITLE
[Feature]`vela traits` should show "*" when trait can be applied to all workloads

### ISSUE THREAD

**Issue by TomorJM** [oam-dev/kubevela#884]
![image](https://user-images.githubusercontent.com/11410549/104543186-f65b6a00-565f-11eb-8540-734ab7e33436.png)
[kubewatch](https://github.com/oam-dev/catalog/blob/master/registry/kubewatch.yaml) trait can be applied to any workloads. But the command `vela traits` information doesn't show it.I suggest completing this information.

**Comment by TomorJM** [comment]
> ![image](https://user-images.githubusercontent.com/11410549/104543186-f65b6a00-565f-11eb-8540-734ab7e33436.png)
> `kubewatch` trait can be applied to any workloads. But the command `vela traits` information doesn't show it.I suggest completing this information.

**Comment by TomorJM** [comment]
@wonderflow @zzxwill What do you think of this proposal?

**Comment by wonderflow** [comment]
@TomorJM  Sure, good idea!

**Comment by zzxwill** [comment]
Thanks for proposing this feature. It's exactly what we talked the last problem of #731 yesterday.
