### ISSUE TITLE
[Feature] `vela status app` display trait status information with customized style

### ISSUE THREAD

**Issue by TomorJM** [oam-dev/kubevela#885]
The current Vela Status app command can output information such as applying traits, but there are the following problems
1. Built-in traits display normally because of their clear semantics and functionality
![image](https://user-images.githubusercontent.com/11410549/104555688-3d098e00-5679-11eb-8ce2-89ff04487c75.png)

2. The status of traits extended by CRD shows problems. CRD has a high degree of functional and semantic freedom. Vela status is not clear about what content should be displayed

Therefore, we need to extend the template and standard for defining trait state when extending the CRD of traits.

#877 
#731

**Comment by TomorJM** [comment]
@wonderflow @zzxwill

**Comment by wonderflow** [comment]
@TomorJM For built-in traits, we must give clear status. For custom traits, we can define some rules in TraitDefinition to let the user to define what status should be show in the status.

Let me use a K8s service trait as an example:

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "K8s service"
  name: kservice
spec:
  definitionRef:
    name: services
  extension:
    customStatus: |-
       output: "type: "+ context.trait.spec.type +",\t clusterIP:"+ context.trait.spec.clusterIP+",\t ports:"+ context.trait.spec.ports[0].port+"/"+context.trait.spec.ports[0].protocal
     
    template: |-
      patch: {spec: template: metadata: labels: app: context.name}
      output: {
        apiVersion: "v1"
        kind: "Service"
        metadata: name: context.name
        spec: {
          selector:  app: context.name
          ports: [
            for k, v in parameter.http {
              port: v
              targetPort: v
            }
          ]
        }
      }
      parameter: {
        http: [string]: int
      }
```

We add a field `customStatus` in trait definition. Then the vela cli can read the template and render it by puting the trait Object as `context.trait`.

**Comment by TomorJM** [comment]
> @TomorJM For built-in traits, we must give clear status. For custom traits, we can define some rules in TraitDefinition to let the user to define what status should be show in the status.
> 
> Let me use a K8s service trait as an example:
> 
> ```
> apiVersion: core.oam.dev/v1alpha2
> kind: TraitDefinition
> metadata:
>   annotations:
>     definition.oam.dev/description: "K8s service"
>   name: kservice
> spec:
>   definitionRef:
>     name: services
>   extension:
>     customStatus: |-
>        output: "type: "+ context.trait.spec.type +",\t clusterIP:"+ context.trait.spec.clusterIP+",\t ports:"+ context.trait.spec.ports[0].port+"/"+context.trait.spec.ports[0].protocal
>      
>     template: |-
>       patch: {spec: template: metadata: labels: app: context.name}
>       output: {
>         apiVersion: "v1"
>         kind: "Service"
>         metadata: name: context.name
>         spec: {
>           selector:  app: context.name
>           ports: [
>             for k, v in parameter.http {
>               port: v
>               targetPort: v
>             }
>           ]
>         }
>       }
>       parameter: {
>         http: [string]: int
>       }
> ```
> 
> We add a field `customStatus` in trait definition. Then the vela cli can read the template and render it by puting the trait Object as `context.trait`.

Yes and right.
It should be like this with design for semantic extensibility. And how this feature is going? Is it assigned to anyone?

**Comment by wonderflow** [comment]
The implementation of this issue should focus on `vela status` command.

The workflow should like below:

1. user run `vela status myapp`
2. cli client get `Application Object`(myapp)
3. if no customStatus defined, run as the current logic.
4. if customStatus defined, get the trait CR and evaluate with the customStatus

```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: ingress
spec:
  extension:
    customStatus: |-
       output: "type: "+ context.trait.service.spec.type +",\t clusterIP:"+ context.trait.service.spec.clusterIP+",\t ports:"+ context.trait.service.spec.ports[0].port+"/"+context.trait.service.spec.ports[0].protocal+",\t domain"+context.trait.ingress.rules[0].host
     
    template: |
      parameter: {
        domain: string
        http: [string]: int
      }
      // trait template can have multiple outputs in one trait
      outputs: service: {
        apiVersion: "v1"
        kind: "Service"
        spec: {
          selector:
            app: context.name
          ports: [
            for k, v in parameter.http {
              port: v
              targetPort: v
            }
          ]
        }
      }
      outputs: ingress: {
        apiVersion: "networking.k8s.io/v1beta1"
        kind: "Ingress"
        metadata:
          name: context.name
        spec: {
          rules: [{
            host: parameter.domain
            http: {
              paths: [
                for k, v in parameter.http {
                  path: k
                  backend: {
                    serviceName: context.name
                    servicePort: v
                  }
                }
              ]
            }
          }]
        }
      }
```
