### ISSUE TITLE
[Feature]How to create multiple resource objects with trait

### ISSUE THREAD

**Issue by kang007** [oam-dev/kubevela#893]
How to create multiple resource objects with trait, Thanks.

Workload Defintion:
--------
```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: gateway
  annotations:
    definition.oam.dev/description: "Gateway workload"
spec:
  definitionRef:
    name: gateways.test.com
  extension:
    template: |
      output: {
        apiVersion: "test.com/v1"
        kind:       "Gateway"
        spec: {
          nodes: parameter.nodes
          ports: parameter.ports
        }
      }
      
      parameter: {
        nodes: [string]
        ports: [int]
      }
```

Service Trait Definition:
--------
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "service the app"
  name: innerservice
spec:
  appliesToWorkloads:
    - gateway
  definitionRef:
    name: "services.test.com" 
  extension:
    template: |-
      output: {
        apiVersion: "v1"
        kind: "List"
        metadata: {
          resourceVersion: ""
          selfLink: ""
        }
        items: [
          for _, s in parameter.services {
            apiVersion: "test.com/v1"
            kind: "Service"
            metadata:{ 
              name: s.name
            }
            spec: {
              serviceName: s.serviceName
              serviceNamespace: s.serviceNamespace 
              servicePorts: [
                for _, p in s.ports {
                  port: p
                  type: "HTTP"
                }
              ]
            }
          }
        ]
      }
      parameter: {
        services: [...{
          name: string
          serviceName: string
          serviceNamespace: string
          ports: [int]
        }]
      }
```

Route Trait Definition:
--------
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: gatewayrouter
  annotations:
    definition.oam.dev/description: "Add a route for a service"
spec:
  appliesToWorkloads:
    - "gateway"
  workloadRefPath: spec.workloadRef
  definitionRef:
    name: routers.test.com
  extension:
    template: |-
      output: {
        apiVersion: "test.com/v1"
        kind:       "Router"
        spec: {
          gatewayServiceName: context.name 
          gatewayNamespace: parameter.gatewayNamespace
          host: parameter.host
          port: parameter.port
          routers: [
            for _, r in parameter.routers {
              match: {
                url: { 
                  type: "Prefix"
                  value: r.url
                }
              }
              weightedServices: [
                for _, w in r.weightedServices {
                  innerService: {
                    serviceName: w.serviceName
                    serviceNamespace: w.serviceNamespace
                    servicePort: w.servicePort
                  }
                  serviceWeight: w.serviceWeight                
                }
              ]
            }
          ]
        }
      }
      parameter: {
        gatewayNamespace: string
        host: *"*" | string
        port: int
        routers: [...{
          url: *"/" | string
          weightedServices: [...{
            serviceName: string
            serviceNamespace: string
            servicePort: int
            serviceWeight: int
          }]
        }]
      }
```
Expected a trait can produce multiple services.

**Comment by wonderflow** [comment]
Add some details after offline discussion with @jamila07 

1. There is an Operator that handles three CRD，Gateway、Service and Route. The Gateway CR will create Gateway for App, the Service CR will register to K8s which gateway proxy will be used, the Route CR will configure  Gateway port and the proxy lists.
2. KubeVela can help create gateway as workload, create multiple servces and route as trait.
3. It's better if KubeVela can help pass through information from workload and services to route. Currently, it's predefined in route CR manually.

**Comment by wonderflow** [comment]
Hi @kang007  you can see the example here https://github.com/oam-dev/kubevela/blob/61e83c1c894b742aa1656298892b948b026aba13/docs/en/platform-engineers/advanced-cue.md#generate-multiple-resources-by-using-for-loop

**Comment by resouer** [comment]
I am fully aware what this issue is asking for but the use case/example is confusing.

Shouldn't the `Gateway` a application scope? Gateway in general is not per workload or per revision, it has an independent lifecycle. 

Also, `Service` should be part of the component IMO.

**Comment by kang007** [comment]
> Hi @kang007 you can see the example here https://github.com/oam-dev/kubevela/blob/61e83c1c894b742aa1656298892b948b026aba13/docs/en/platform-engineers/advanced-cue.md#generate-multiple-resources-by-using-for-loop

OK， Thanks.

**Comment by kang007** [comment]
> I am fully aware what this issue is asking for but the use case/example is confusing.
> 
> If we are trying to model a Istio powered app, then shouldn't the `Gateway` be a application scope (i.e. it's at the edge of the cluster, shared by apps, not per workload instance)? We also need [catalog design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md) to host these templates alongside with the existing templates.
> 
> Or, we are actually discussing about modeling Istio Operator itself (i.e. the `Gateway` means the gateway controller of Istio)? Then what service and route stands for? `VirtrualService` controller?



> I am fully aware what this issue is asking for but the use case/example is confusing.
> 
> If we are trying to model a Istio powered app, then shouldn't the `Gateway` be a application scope (i.e. it's at the edge of the cluster, shared by apps, not per workload instance)? We also need [catalog design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md) to host these templates alongside with the existing templates.
> 
> Or, we are actually discussing about modeling Istio Operator itself (i.e. the `Gateway` means the gateway controller of Istio)? Then what service and route stands for? `VirtrualService` controller?

**Comment by kang007** [comment]
> I am fully aware what this issue is asking for but the use case/example is confusing.
> 
> If we are trying to model a Istio powered app, then shouldn't the `Gateway` be a application scope (i.e. it's at the edge of the cluster, shared by apps, not per workload instance)? We also need [catalog design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md) to host these templates alongside with the existing templates.
> 
> Or, we are actually discussing about modeling Istio Operator itself (i.e. the `Gateway` means the gateway controller of Istio)? Then what service and route stands for? `VirtrualService` controller?

This is the case now. We are not using Istio. It is a set of Envoy-based Operators developed by us. We will deploy the gateway through the Gateway CR. Service is the service that the gateway needs to proxy, and Route is the routing strategy set for the gateway.
