### ISSUE TITLE
Vela APIServer environment design

### ISSUE THREAD

**Issue by baxiaoshi** [oam-dev/kubevela#895]
Hi @linfan

> I think for the first step we will implement the catalog API and format first. Currently there is no roadmap doc here. I am working on that right now and will follow up in another PR.

_Originally posted by @hongchaodeng in https://github.com/oam-dev/kubevela/issues/881#issuecomment-759286667_

**Comment by baxiaoshi** [comment]
I have a few questions about this design：
1.In the design, an application can only be long to one environment. I can't understand why it is designed in this way. In a company, an application is usually deployed in multiple environments
2.The current data storage is not all stored in MySQL. When will it be implemented
3.How to describe how to place multiple applications in multiple clusters in workload

**Comment by hongchaodeng** [comment]
For roadmap please see https://github.com/oam-dev/kubevela/pull/891

**Comment by hongchaodeng** [comment]
> 1.In the design, an application can only be long to one environment. I can't understand why it is designed in this way. In a company, an application is usually deployed in multiple environments

Could you provide an example?
In current design, environments are actually used to isolate applications and their dependencies. For example, staging and production.

> 2.The current data storage is not all stored in MySQL. When will it be implemented

What's the question?

> 3.How to describe how to place multiple applications in multiple clusters in workload

This is supported in the design. I will provide more details to cover it in the doc.

**Comment by baxiaoshi** [comment]
1.An application has three environments: test, staging and production. The application needs to be deployed in these three environments, and the resources of each environment are isolated
2.I didn't find much time to implement the design in roadmap

**Comment by baxiaoshi** [comment]
1.An application has three environments: test, stage and produc. The application needs to be deployed in these three environments, and the resources of each environment are isolated
2.I didn't find much time to implement the design in roadmap

**Comment by baxiaoshi** [comment]
![image](https://user-images.githubusercontent.com/11749031/104969440-5e74cc00-5a23-11eb-85bd-b26c1e62c34c.png)

Why is the definition not designed to be global, so that it only needs to be defined once and then published to different clusters

**Comment by baxiaoshi** [comment]
In my current company, an environment has multiple clusters, users can choose to deploy in a single cluster or multiple clusters. In one environment, I expect the API design

```
/application/<app>
{
    "id": "app-1",
    "environment": "test/stage/product",
    "clusters": ["cluster1", "cluster2"],
    "workloads": [
    ],
    "components": [
    ]
}
```

**Comment by hongchaodeng** [comment]
I'm getting a little bit lost in your comments.. So feel free to use Chinese if you want to :)

Let me summarize your points to see if I understand it correctly:

- Definition should be top level API so that one definition could be published to different clusters. This is like having a Definition template.
- An application could be deployed to multiple clusters. Good news! This is exactly the scope of the current design.
- An application could have multiple environments. This is something I don't understand why? In your above example, it seems you only have one environment for an application. Just like the current design.

**Comment by hongchaodeng** [comment]
Here is the update base on offline discussion 
- An application could be deployed to multiple environments and thus multiple clusters. I will update the design doc to reflect this.
- A definition is enabled via installing a package. So the global template will be stored and retrieved via catalog. I'm working on a detailed design on this. Might update on existing design doc or put up a new one.

**Comment by hongchaodeng** [comment]
@baxiaoshi Based on our discussion I have update the design in https://github.com/oam-dev/kubevela/pull/926
