### ISSUE TITLE
[Feature] Support multiple resources outputs in cue template for workloadDefinition

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#903]
Now our TraitDefinition can support output multiple K8s resources by define `outputs` in TraitDefinition. But we don't support this way in workloadDefinition. The main reason is we convert the resource in workloaddefinition into Component which can only hold only one K8s object.

We can support this feature after  #867

**Comment by kinsolee** [comment]
We are running kubevela based on Openshift platform. And we want to create a `WorkloadDefinition` which consists of `[DeploymentConfig](https://docs.openshift.com/container-platform/4.6/applications/deployments/what-deployments-are.html)` and `Service` resource. This feature will easily tackle this problem, or we have to create a TraitDefinition exclusively for Service resource, which violate `OAM`'s principle as the developer(appfile user) has to know the concept of `Service`.

**Comment by hongchaodeng** [comment]
@kinsolee 
I agree. WorkloadDefinition is just an encapsulation of all the nitty-gritty behind what makes the workload runs for developers. Whether just Deployment or Deployment + Service are the details that would be hidden by the parameters exposed to users.
