### ISSUE TITLE
the user of vela doesn't know what is contour or nginx ingress. So there won't be a 'type' field in trait spec.

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#908]
Note that the user of vela doesn't know what is contour or nginx ingress. So there won't be a 'type' field in trait spec.

Instead, the provider of ingress is a platform admin's concern that should be decided by:

1. trait definition, and be configurable by vela install config
2. or, auto discover by whether contour or nginx ingress is available (default provider should be defined in this case)

1 is simplest though 2 is favorable, leave to @wonderflow for final decision

_Originally posted by @resouer in https://github.com/oam-dev/kubevela/issues/646#issuecomment-732443528_

**Comment by wonderflow** [comment]
We have made 1 as a quick fix, but we are lacking of way to fix as 2

**Comment by resouer** [comment]
For 1, since we now have catalog design: https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md, it also makes sense to maintain multiple set of definitions in catalog. Platform team will make the decision by choosing which set to apply to cluster (environment).

**Comment by wonderflow** [comment]
> For 1, since we now have catalog design: https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md, it also makes sense to maintain multiple set of definitions in catalog. Platform team will make the decision by choosing which set to apply to cluster (environment).

Yes, I'll close this issue, it's related with #870
