### ISSUE TITLE
[Feature] support namespace scope WorkloadDefinition/TraitDefinition CRD

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#918]
**Is your feature request related to a problem? Please describe.**

Currently, workloadDefinition and traitDefinition are all cluster scope, but it seems block some our features:

* Use Case 1: For some security reason, we can't easily create or update cluster-scope object, a cluster scope object will widely affect the system which can be dangerous. On the other hand, user extended capability should not mix with system level capability, users shouldn't be able to update the system level definition.
* Use Case 2: There're two OAM based PaaS in the same cluster, they can conflict with each other if the Definition CRD is cluster scope.
* Use Case 3: when we want to use env as a scope of capability, then we shoud find capabilities from an environment, which need us to make the definition object to be namespace scoped as a precondition. #176

So we need to make the definition objects to be namespace scoped.

In my view, we should have at least two level of capabilities(definition object):

1. **system level**:  1) These capabilities can be provided by the system admin( the basic platform builder). 2) They should be very common and low level. They can be widely used in the system even in different user namespaces, just like what it is now as cluster scoped definition. 3) They can be updated only by system admin, and it should be cautious and rarely operation.
2. **user level**: 1) These capabilities can be defined by different user in different environments. 2) They should not affect each other.  Usually these capabilities are scenario specific, maybe they are built by the second party platform builder on top of the base platform. 3) Users can easily create/update the workload/trait definition by thier own. 4) User level capability should have higher priority than the system level if it can be installed. (If some platform builder don't want user level capbility to cover theirs, they should deny the same name capability to be installed.)

**Describe the solution you'd like**

We're not going to solve all these problems described above, but we must leave enough extensibility. In this issue, I think we can do following steps:

1. Change CRD of WorkloadDefinition/TraitDefinition/ScopeDefinition to be namespace scoped.
2. Support a launch parameter for vela core controller, that parameter can specify a namespace as system-level, the launch parameter should also include system ENV（we have supported one named `DEFINITION_NAMESPACE`, please make sure the compatibility）.
3. All other capabilities which are not in the system level namespace should be  user level. It can be in the same namespace with the user's application. So functions like `GetDefinition` must support namespace as an argument, they search capability from the specified namesapce first, if not found, search the system level namesapce.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
This issue is also related with #176

After Env become a CRD, the env may contain a namespace and the workloadDefinition/traitDefinition list.

The system level workload/trait is actually in a system ENV that can be used by default.

**Comment by WangYikewyk** [comment]
Several questions for the steps:
1.For step 2, It seems to be vela cli and api-server also need to know which namespace is admin specified system-namespace? So can we use a k8s configMap to store the info?
2.Also for step 2,I don't understand how do we support DEFINITION_NAMESPACE env, because I can't find it in our code. maybe you mean second platform use this env to solve this supporting namespace problem, thus  I think we need more details about their solutions to make sure the compatibility.
3. Because of the ****spec.scope**** field of CRD is  immutable, the workload/trait/ definition CRD must be deleted and recreated, and the CR will be deleted, that means  user need backup and migrate their data, and  there is no need  for us to writing hack code to handle their old CR ?

**Comment by WangYikewyk** [comment]
I thought about some details about solution.
1.Add a launch parameter named "system-definition-namespace" for vela core to specify which namespace is system level.
2.User still use "DEFINITION_NAMESPACE"

**Comment by WangYikewyk** [comment]
IMO, the priority of namespace search order should be **DEFINITION_NAMESPACE** env > user-level > system-level.If vela-core-controller specify os env  **DEFINITION_NAMESPACE**, we should search definition from this namespace(for compatibility reason),If not found we will search from user-level namespace(application's namespace).If still cannot found search it from system-level namespace.
