### ISSUE TITLE
[Feature] cert-manager install optional

### ISSUE THREAD

**Issue by hprotzek** [oam-dev/kubevela#928]
**Is your feature request related to a problem? Please describe.**
Trying to install kubevela into our existing gke dev cluster, which already has the cert-manager installed, results in an error.

```
Failed to install the chart with error: ClusterRole "cert-manager-cainjector" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "kubevela": current value is "cert-manager"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "vela-system": current value is "ee-system"
rendered manifests contain a resource that already exists. Unable to continue with install
```

**Describe the solution you'd like**
Make the cert-manager optional in the helm chart.

**Comment by resouer** [comment]
I am fully supporting this. 

As a plus, I think we should make default installation of KubeVela does not include any 3rd party dependency, and only support basic traits (ingress, hpa, simple rollout etc.) since now we are pretty good on modeling any built-in capabilities.

And as the next step, user can choose to install different capabilities step by step.

/cc @hongchaodeng @wonderflow

**Comment by wonderflow** [comment]
kubevela webhook depends on cert-manager, do you mean we should disable webhook by default? @resouer

**Comment by resouer** [comment]
@wonderflow webhook should be there, but we should allow user install cert-manager by himself.

**Comment by LeoLiuYan** [comment]
> kubevela webhook depends on cert-manager, do you mean we should disable webhook by default? @resouer

Maybe `KubeVela` can generate certs by itself, just like `Kruise` do?

**Comment by wonderflow** [comment]
I have supported cert-manager as optional, by default we will install it.  I suggest we raise a new issue for this.

> I would support this.
> 
> As a plus, I think we should make default installation of KubeVela does not include any 3rd party dependency, and only support basic traits (ingress, hpa, simple rollout etc.) since now we are pretty good on modeling any built-in capabilities.
> 
> And as the next step, user can choose to install different capabilities step by step.
> 
> /cc @hongchaodeng @wonderflow

**Comment by hprotzek** [comment]
Can all dependencies, be optional? Because while testing kubevela in our existing gke cluster, also the already existing `kube-prometheus-stack` got broken due duplicate installed webhooks from the prometheus operator. 

So maybe https://github.com/oam-dev/kubevela/pull/934 can be extended to make the other helm chart dependencies from  `velaConfig` also optional?

**Comment by resouer** [comment]
@hprotzek All 3rd-party dependencies are configurable via a `ConfigMap`, have you tried to follow the `"Customize Your Installation"` section in [this gude](https://kubevela.io/#/en/install?id=_3-initialize-kubevela)?

i.e.
```console
$ kubectl -n vela-system edit cm vela-config
# remove already installed the 3rd-party dependencies
...

# reinstall vela
$ helm uninstall -n vela-system kubevela
$ helm install -n vela-system kubevela```

**Comment by wonderflow** [comment]
we have supported vela install with helm args and make cert-manager optional in #934 
 closing this one, I have made a new one for the following work #939
