### ISSUE TITLE
Modification to comand `vela show WORKLOAD_TYPE or TRAIT`

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#929]
The following modifications are suggested to be made on command `vela show`. /cc @wonderflow 

## Using Browser
`vela show WORKLOAD_TYPE/TRAIT`  --> `vela show WORKLOAD_TYPE/TRAIT --web` 

## Using Terminal
`vela show WORKLOAD_TYPE/TRAIT --no-website`  --> `vela show WORKLOAD_TYPE/TRAIT`

**Comment by wonderflow** [comment]
fixed by #948
