### ISSUE TITLE
make default installation of KubeVela does not include any 3rd party dependency

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#939]
we should make default installation of KubeVela does not include any 3rd party dependency, and only support basic traits (ingress, hpa, simple rollout etc.) since now we are pretty good on modeling any built-in capabilities.

And as the next step, user can choose to install different capabilities step by step.

/cc @hongchaodeng @wonderflow

_Originally posted by @resouer in https://github.com/oam-dev/kubevela/issues/928#issuecomment-766493795_

**Comment by wonderflow** [comment]
This job should work step by step:

- [ ] promethus: remove the default metrics trait, refactor the document to tell how to add it as an Capability.
- [ ] flagger: remove the default Rollout trait, refactor the document to tell how to add it as an Capability.
- [ ] keda: remove the default scaler trait, refactor the document to tell how to add it as an Capability.

**Comment by resouer** [comment]
@wonderflow, just to clarify, for the existing end user docs, I think we only need to leave them there and mark them as `Extension Capabilities`, and ref https://kubevela.io/#/en/developers/cap-center about how to install the capability.

We can clarify the needed 3rd-party dependency in the capability center/catalog and let user install them by themselves.
