### ISSUE TITLE
Rename project to vela

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#94]
According to the latest poll, the name `vela` has the most votes. Let's rename the project before announcement.

**Comment by resouer** [comment]
Agree, I personally like the name `vela` very much!

**Comment by wonderflow** [comment]
Sure, I will do that!

**Comment by wonderflow** [comment]
- [x] renamae rudr/rudrx -> vela
- [ ] rename project name to openvela

**Comment by wonderflow** [comment]
done, we have kubevela here 👏
