### ISSUE TITLE
vela up -f https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml

### ISSUE THREAD

**Issue by zhangb191** [oam-dev/kubevela#941]
Parsing vela appfile ...
Error: Get "https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml": dial tcp 0.0.0.0:443: connect: connection refused

**Comment by wonderflow** [comment]
can you try 

```
curl https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml
```

Make sure you're not blocked by GFW

**Comment by zhangb191** [comment]
> 你能试一下吗
> 
> ```
> curl https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml
> ```
> 
> 确保您没有被GFW阻止

curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by wonderflow** [comment]
I can't reproduce it, closing, feel free to reopen if it's still happening.
