### ISSUE TITLE
deprecate vela install to use helm install for vela controller installation

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#942]
- [x] 1. setup alibaba cloud OSS bucket
- [x] 2. sync and upload chart to OSS bucket for every release
- [x] 3. update docs to `helm install` from the oss bucket (do we need a domain for that?)
- [ ] 4. deprecate `vela install`

**Comment by hprotzek** [comment]
I like that, as the `vela install` is nice to test and play with vela, but to install into a running cluster, using just plain helm is much more trustworthy. I killed our dev cluster yesterday by running `vela install` because of the dependencies I wasn't aware of, which wouldn't happen for a normal helm chart, that can be easily checked.

**Comment by jriguera** [comment]
Also -in my opinion-  in a production setup, from the point of view of the end users (developers), does not make sense to provide a cli which is used to deploy apps and potentially break/modify a running platform. vela cli is perfect if it focus on end users needs, platform operators need to know a bit more about the internals of the platforms and be able to debug (with kubectl) or install new traits/software, which in most cases, is released as helm charts.

**Comment by legendtkl** [comment]
With `helm install` we can utilize more power from the helm eco-system, and this is no doubt a  very good point.

Also, we need to be aware that once we introduce this, we are some kind of bound to `helm`. At this stage, this seems to be not a big problem.

I am new here. Correct me if I misunderstood this.

**Comment by wonderflow** [comment]
@jriguera @hprotzek  @legendtkl  Very much appreciate for your comments, that's very useful, and it also make me believe that deprecate vela install will be a good choice.

Using helm install instead of `vela install` will not let us bound to `helm`, it will be platform builder's choice , helm chart is only a package format, the platform builder can even clone the repo and build from source by themselves.

**Comment by legendtkl** [comment]
@wonderflow, make sense, thanks for the reply.

**Comment by wonderflow** [comment]
I have finished 1 and 2 steps. The rest steps will be done after we have a new release.

**Comment by Cweiping** [comment]
Nice. At the same time, the suggestions are uploaded to the [helm hub](https://hub.helm.sh/).
