### ISSUE TITLE
minikube addons enable ingress

### ISSUE THREAD

**Issue by zhangb191** [oam-dev/kubevela#949]
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by wonderflow** [comment]
It seems to be the minikube issue？

**Comment by wonderflow** [comment]
closing as it does not seems to be an issue of kubevela
