### ISSUE TITLE
[Feature] Add Arm64 binary  release support

### ISSUE THREAD

**Issue by tangx** [oam-dev/kubevela#961]
Could you add release `arm64` arch binary file ？

thank you

**Comment by wonderflow** [comment]
sure, was `linux/arm64` enough?

**Comment by wonderflow** [comment]
please help to try, don't care about the version, I randomly tag it, it follows the master branch now. https://github.com/wonderflow/kubevela/releases/tag/v0.1.16

**Comment by wonderflow** [comment]
It seems currently the gox don't support build arm64 https://github.com/mitchellh/gox/issues/92 and our release pipeline broken: https://github.com/oam-dev/kubevela/runs/2019563379?check_suite_focus=true

**Comment by wonderflow** [comment]
Hope someone good at compling for Arm64 can help.

**Comment by wonderflow** [comment]
supported after v1.2.0 https://github.com/oam-dev/kubevela/releases/tag/v1.2.0-rc.2
