### ISSUE TITLE
mark `vela install` as deprecated

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#978]
the `cobra` has a deprecate flag, we should add a message to say:
  > we will remove this command after `Kubevela 1.0`.

And refactor all related message to use `helm install` instead:

![image](https://user-images.githubusercontent.com/2173670/106411302-e7f2b800-647f-11eb-95a2-8b70f9fd9440.png)

part of #942

**Comment by wangkai1994** [comment]
@wonderflow done

**Comment by wonderflow** [comment]
@wonderflow You should fix all these places included in my screenshot

**Comment by wangkai1994** [comment]
@wonderflow Thanks , should replace `bin/vela install` to `helm install -n vela-system kubevela charts/vela-core
` in README.md ? OR do nothing in README.md

**Comment by wonderflow** [comment]
@wangkai1994  don't change the readme file in demo, thanks

**Comment by wangkai1994** [comment]
ok,done
