### ISSUE TITLE
fix wrong chart name from `oam-kubernetes-runtime` to `kubevela`

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#979]
1. https://github.com/oam-dev/kubevela/blob/0e987a08b65c2ae51581872263b388c0762f90df/pkg/commands/system.go#L97
2. https://github.com/oam-dev/kubevela/blob/0e987a08b65c2ae51581872263b388c0762f90df/pkg/commands/system.go#L285

**Comment by 96RadhikaJadhav** [comment]
@wonderflow Can I work on the issue?

**Comment by wonderflow** [comment]
@96RadhikaJadhav  sure, assigned
