### ISSUE TITLE
demo Error: applicationconfigurations.core.oam.dev "first-vela-app" not found

### ISSUE THREAD

**Issue by jchalex** [oam-dev/kubevela#980]
$ vela status first-vela-app
About:

  Name:      	first-vela-app                         
  Namespace: 	default                                
  Created at:	2021-02-01 12:10:23.56777251 +0800 HKT 
  Updated at:	2021-02-01 12:10:23.567772602 +0800 HKT

Services:

Error: applicationconfigurations.core.oam.dev "first-vela-app" not found

other info:
$ vela ls
SERVICE       	APP           	TYPE      	TRAITS 	STATUS 	CREATED-TIME                           
testsvc       	first-vela-app	webservice	ingress	Staging	2021-02-01 12:10:23.56777251 +0800 HKT 
express-server	testapp       	webservice	       	Staging	2021-02-01 12:13:22.952577971 +0800 HKT

$ kind get clusters
kind

$ kubectl get pods
No resources found in default namespace.

$ kubectl get pods -n vela-system
NAME                                  READY   STATUS              RESTARTS   AGE
kubevela-vela-core-5885f549cd-cgqnx   0/1     ContainerCreating   0          84m

**Comment by wonderflow** [comment]
It seems your vela-core was not running? Make sure you have cert-manager

**Comment by wonderflow** [comment]
https://github.com/oam-dev/kubevela/pull/981 I found we build the chart with wrong image tag, and we have created a new release to fix it, please help try the new one. https://github.com/oam-dev/kubevela/releases/tag/v0.3.2

**Comment by jchalex** [comment]
same error

$ vela version
Version: refs/tags/v0.3.2
GitRevision: git-18f184d
GolangVersion: go1.14.14

$ vela up -f https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela.yaml
Parsing vela appfile ...
Load Template ...

Rendering configs for service (testsvc)...
Writing deploy config to (.vela/deploy.yaml)

Applying application ...
Checking if app has been deployed...
App exists, updating existing deployment...
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward first-vela-app
             SSH: vela exec first-vela-app
         Logging: vela logs first-vela-app
      App status: vela status first-vela-app
  Service status: vela status first-vela-app --svc testsvc

$ vela status first-vela-app
About:

  Name:      	first-vela-app                         
  Namespace: 	default                                
  Created at:	2021-02-01 14:37:10.959287311 +0800 HKT
  Updated at:	2021-02-01 14:37:10.959287459 +0800 HKT

Services:

Error: applicationconfigurations.core.oam.dev "first-vela-app" not found

**Comment by wonderflow** [comment]
@jchalex  can you print log of the pod? do you install cert-manager?

**Comment by jchalex** [comment]
> It seems your vela-core was not running? Make sure you have cert-manager

$ kubectl get pods --namespace vela-system
NAME                                  READY   STATUS    RESTARTS   AGE
kubevela-vela-core-6785bc9c79-rtsnx   0/1     Running   0          46s

$ kubectl get pods --namespace cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-5597cff495-sh8d7             1/1     Running   0          10m
cert-manager-cainjector-bd5f9c764-85wr6   1/1     Running   0          10m
cert-manager-webhook-5f57f59fbc-7nhz4     1/1     Running   0          10m

**Comment by jchalex** [comment]
Now is ok, but just vela status so many times.

$ vela status first-vela-app
About:

  Name:      	first-vela-app                         
  Namespace: 	default                                
  Created at:	2021-02-01 14:59:54.320069323 +0800 HKT
  Updated at:	2021-02-01 14:59:54.320069434 +0800 HKT

Services:

  - Name: testsvc
    Type: webservice
    HEALTHY Ready:1/1 
    Traits:
      - ✅ ingress: domain=testsvc.example.com
		http=map[/:8000]
      - ✅ ingress: domain=testsvc.example.com
		http=map[/:8000]
		
    Last Deployment:
      Created at: 2021-02-01 15:00:34 +0800 HKT
      Updated at: 2021-02-01T14:59:54+08:00

**Comment by wonderflow** [comment]
@jchalex  yes, we're fixing `vela status`
