### ISSUE TITLE
"vela show" does't generate complete cli reference for trait "env"

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#984]
Applying TraitDefinition `env` https://github.com/oam-dev/catalog/blob/master/registry/podenv.yaml, run `vela show env` and it didn't generate list type env parameter.

![image](https://user-images.githubusercontent.com/2805315/106436964-b5f94a00-64af-11eb-93eb-205e8a630551.png)

/cc @wonderflow

**Comment by wonderflow** [comment]
The type of  env  is a map, I doubt there's some bug that basic format was not displayed.

**Comment by WangYikewyk** [comment]
The problem happen in https://github.com/oam-dev/kubevela/blob/da523678977f630465b16d502231cf092345aee8/pkg/plugins/references.go#L300.
This is a general bug for  map struct ,eg(map[string]string , map[int]string....),this kind of struct doesn't have any field, so the "arguments.Len()" = 0.I thought we can add a func handle this situation.
