### ISSUE TITLE
Roadmap of Rewriting The Vela Control Plane

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#987]
# Background

We are trying to rewrite the APIServer based on [the new design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md).

Why rewrite?
1. Currently part of the data is stored in local storage (e.g. env, staged apps, etc.). We should store them in a more persistent storage like a database. What about storing them as Custom Resources (CR)? First, CR might not fit for cross-cluster APIs. Second, CR & operator-pattern might be over-kill for some use cases (env, catalogs).
2. The CLI talks to k8s APIServer directly and a lot of code are written on the client side. This is not easy to integrate for others, e.g. UI dashboard. Some logic is not good to implement on client side either, e.g. catalog management. We should develop a new backend server based on GRPC services. In this way we can simplify CLI building and put a lot of logic on the server side.
3. The old API is bound to one cluster. But the new API design is based on multi-clusters, multi-environments. The whole user experience needs to be change and it might affect the CLI/UI in overall.

# Introduce VelaCP

Based on the above reasons, we have started a new sub-project called [velacp](https://github.com/oam-dev/velacp) to rewrite the Vela control plane components (CLI, UI, APIServer):

![velacp-arch](https://user-images.githubusercontent.com/920884/106567948-7189a080-64e7-11eb-983e-b606859298cd.png)

Why create a new project?
- There are a lot of work and we want to develop quickly to rewrite the whole control plane. Our sprint would span only one and a half months.
- The components are well-isolated and not conflicting with existing code in KubeVela repo.

# What's Next?

Here's the concrete plan:
- 02/01 -- 03/15: The CLI and APIServer of the new control plane will be developed in velacp project. It will include the new APIs based on the [new design](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md) and  satisfy existing APIs as much as possible.
- 03/15 -- 03/30: Update the documentation, add test coverage for critical path, finish QA, update release pipelines (release new vela CLI and server tool).
- 04/01 -- 04/30: Rewrite dashboard based on the new API and UX story.
- 05/01 -- 05/07: Merge the code back to the main repo.

**Comment by hongchaodeng** [comment]
cc @wonderflow @resouer @zzxwill @majian159 @sunny0826

**Comment by Cweiping** [comment]
According to [its](https://github.com/oam-dev/kubevela/issues/751#issuecomment-741544904) plan, it will support multiple types of storage, including `Local` and `MySQL`. According to this architecture, I think storage should also have subprojects and a general Grpc interface.

Then, what type of DB source do we support? `MySQL` or `mongodb`.

**Comment by LeoLiuYan** [comment]
Should `cli` and `ui` all talk to `grpc gateway`?

**Comment by hongchaodeng** [comment]
@Cweiping https://github.com/oam-dev/kubevela/issues/751 is more about changing the storage interface on the client side. The DB referred to here are for the server side.

> Then, what type of DB source do we support?

We will implement mongodb backend first.
But there is a generic interface and contributions of other storage backends are welcome

**Comment by hongchaodeng** [comment]
@LeoLiuYan 
grpc gateway is for exposing RESTful services. If CLI talk to grpc gateway it will only complicate things.

velacp will be released in vela 1.0 . We will merge it back to this repo once the new design is implemented.

**Comment by hongchaodeng** [comment]
Closing in favor of https://github.com/oam-dev/kubevela/issues/883
