### ISSUE TITLE
vela svc not found

### ISSUE THREAD

**Issue by jchalex** [oam-dev/kubevela#996]
https://kubevela.io/#/en/developers/port-forward

![image](https://user-images.githubusercontent.com/11224001/106695904-8a44a400-6616-11eb-8b91-7124a37aca9f.png)

but

![image](https://user-images.githubusercontent.com/11224001/106696061-d7c11100-6616-11eb-8ae3-34913ad28207.png)

**Comment by wonderflow** [comment]
thanks for reporting, will fix it. You can use `vela ls` instead of `vela svc ls`.

**Comment by jchalex** [comment]
ok, thanks
