### ISSUE TITLE
add `vela workloads` to sync Capability from cluster in installation guide

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#997]
https://kubevela.io/#/en/install

![image](https://user-images.githubusercontent.com/2173670/106708967-b4a25b80-662e-11eb-9b2f-82cecc926a85.png)

**Comment by 96RadhikaJadhav** [comment]
@wonderflow Can I work on the issue?

**Comment by wonderflow** [comment]
@96RadhikaJadhav  sure, please also print the output of that command in the doc, thanks!

**Comment by 96RadhikaJadhav** [comment]
@wonderflow  Please check if this is fine or need to add anything else?

![image](https://user-images.githubusercontent.com/56536997/106848094-42855180-66d6-11eb-9c6e-d6149943187f.png)

**Comment by wonderflow** [comment]
@96RadhikaJadhav Can you print the output of the command `vela workloads`?

**Comment by vnzongzna** [comment]
@wonderflow can you assign this issue to me?
